### ISSUE TITLE
openvpn 可以将tcp流转成udp流?

### ISSUE THREAD

**Issue by ldaochen** [wangyu-/UDPspeeder#1]
在你readme图中看到openvpn可以将tcp转成udp

**Comment by wangyu-** [comment]
这个可以的呀。openvpn tun 模式可以承载任何ip 以上的协议。openvpn本身靠tcp/udp连接。 任何ip层以上协议都能被openvpn 转成tcp或者udp。  openvpn udp模式是标准用法，tcp模式从原理上有性能问题，不建议这样用。

**Comment by ldaochen** [comment]
有测过流量消耗吗？ 例如采用默认的配置，播放1个视频，实际消耗流量多少？ kcp耗流量太可怕了。

**Comment by wangyu-** [comment]
你是说openvpn带来的流量消耗还是UDPspeeder的？
openvpn带来的额外流量消耗不会超过5%。
UDPspeeder(目前)是靠多倍发包加速的。应用场景是加速游戏、网页、语音等小流量的应用，降低丢包率。
如果设置成发2倍的包，流量消耗是2倍，3倍的包流量就是3倍。看视频不会比kcptun好，还是用kcptun吧。以后会做FEC改善这个问题。

kcp耗流量太可怕也许是你的配置问题吧，你可以去kcptun项目里提issue贴出配置让别人帮你参考。

**Comment by ldaochen** [comment]
好的，谢谢。

在 2017年8月10日 下午9:51，wangyu- <notifications@github.com>写道：
