### ISSUE TITLE
如何复用本代码中的FEC算法

### ISSUE THREAD

**Issue by woniu17** [wangyu-/UDPspeeder#102]
您好，
向参考该代码实现UDP的FEC冗余发包机制，由于不了解RS算法的实现原理，能否提供简单例子说明。
对于FEC冗余发包机制，我的理解是：
Client端有以下4个UDP包要发送到Server端，内容分别为：
"aaaaaaaaaaaaaaaaaaaa"
"bbbbbbb"
"cccccccccccccccccccccccccccc"
"ddddddddddddddd"
通过FEC冗余机制，会生成2两个冗余包，内容假设为：
"xxxxzzzzzzzzzzzqqqqqq"
”yyyyyyxxxxxxqqqqzzzziiiiiii“
如果没有丢包的情况，Server端会收到6个包，分别为：
"aaaaaaaaaaaaaaaaaaaa"
"bbbbbbb"
"cccccccccccccccccccccccccccc"
"ddddddddddddddd"
"xxxxzzzzzzzzzzzqqqqqq"
”yyyyyyxxxxxxqqqqzzzziiiiiii“

我的理解可能有误，能否提供简单例子说明，谢谢~

**Comment by wangyu-** [comment]
>对于FEC冗余发包机制，我的理解是：
Client端有以下4个UDP包要发送到Server端，内容分别为：
"aaaaaaaaaaaaaaaaaaaa"
"bbbbbbb"
"cccccccccccccccccccccccccccc"
"ddddddddddddddd"
通过FEC冗余机制，会生成2两个冗余包，内容假设为：
"xxxxzzzzzzzzzzzqqqqqq"
”yyyyyyxxxxxxqqqqzzzziiiiiii“
如果没有丢包的情况，Server端会收到6个包，分别为：
"aaaaaaaaaaaaaaaaaaaa"
"bbbbbbb"
"cccccccccccccccccccccccccccc"
"ddddddddddddddd"
"xxxxzzzzzzzzzzzqqqqqq"
”yyyyyyxxxxxxqqqqzzzziiiiiii“

差不多，不过rs算法要求各个包的长度相同。`--mode 0`模式下的解决办法是把数据切割到等长，`--mode 1`模式下的解决办法是把数据包填0补齐到相同长度。

>如何复用本代码中的FEC算法

可以参考tinyFecVPN的实现。tinyFecVPN就是复用了UDPspeeder的代码，实现了一个带FEC的VPN。以后我可能会把UDPspeeder的底层代码单独作为一个lib发布出来并附上文档。目前想要了解细节，只能看代码。

**Comment by woniu17** [comment]
```
int unit_test()
{
	int i,j,k;
	void *code=fec_new(3,6);
	char arr[6][100]=
	{
		"aaa","bbb","ccc"
		,"ddd","eee","fff"
	};
	char *data[6];
	for(i=0;i<6;i++)
	{
		data[i]=arr[i];
	}
	rs_encode2(3,6,data,3);
	//printf("%d %d",(int)(unsigned char)arr[5][0],(int)('a'^'b'^'c'^'d'^'e'));

	for(i=0;i<6;i++)
	{
		printf("<%s>",data[i]);
	}

	data[0]=0;
	//data[1]=0;
	//data[5]=0;

	int ret=rs_decode2(3,6,data,3);
	printf("ret:%d\n",ret);

	for(i=0;i<6;i++)
	{
		printf("<%s>",data[i]);
	}
	fec_free(code);
```
这一段代码中，rs_encode2、rs_decode2是何作用呢？

能否指出FEC算法的主要接口？

```
// 1. 使用4个数据包生成2个冗余包的接口
// 传入4个UDP数据包，返回2个FEC冗余包
fec_data_t []
get_fec_data(udp_data_t data_arr[4])
{
    // ....
}
// 2. 使用数据包+FEC冗余包恢复丢失的数据包接口
```

感谢~

**Comment by wangyu-** [comment]
>这一段代码中，rs_encode2、rs_decode2是何作用呢？

rs_encode2(3,6,data,3); //编码。(3，6)表示输入3个包，输出6个包，也就是对3个数据生成6-3个冗余包；data是数组指针，最后一个3是数据长度。

rs_decode2(3,6,data,3);//解码，参数含义相同。

关于细节，你先看一下这个文件，这是Luigi Rizzo版的原版fec接口：

https://github.com/wangyu-/UDPspeeder/blob/master/lib/fec.h

然后我在上面做了简单的封装，代码几十行左右：

https://github.com/wangyu-/UDPspeeder/blob/master/lib/rs.c
https://github.com/wangyu-/UDPspeeder/blob/master/lib/rs.h

>能否指出FEC算法的主要接口？

看一下fec_encode_manager_t和fec_decode_manager_t这两个类。

我最近比较忙，不好意思，其他细节你自己看一下代码吧。

**Comment by woniu17** [comment]
好的，非常感谢~
不知道有没有其他算法，可以应对非等长数据包，不用对数据包进行切割或补全？

**Comment by wangyu-** [comment]
>不知道有没有其他算法，可以应对非等长数据包，不用对数据包进行切割或补全？

在编码时，在逻辑上把每个字符当成一个数据包，而不是真正拆开。比如“abc" ”de“ "gfhi" ，把里面的每个字符当成一个数据包。在编码时用rs_encode2(9,xxxx,data,1)。

在数据很长的时候可能有性能问题，比如rs_encode(3000,xxxx,data,1)会非常慢。需要把rs换成raptor一类性能更高的编码才能避免性能问题。
