### ISSUE TITLE
作者你好 你项目所说的S_S端口是本地的端口还是外部连接的端口？

### ISSUE THREAD

**Issue by Dreamone1** [wangyu-/UDPspeeder#103]
作者你好 你项目所说的S_S端口是本地的端口还是外部连接的端口？

**Comment by Dreamone1** [comment]
在VPS服务端上，默认的端口是127.0.0.1:1080
我自己设置的外部连接端口是XXX.XXX.XXX.XX:8080
我该使用哪一个端口？
我使用的是S_S-libve

**Comment by keeno1982** [comment]
8080
