### ISSUE TITLE
udpspeederV2+udp2raw 串联 NATl类型 失败

### ISSUE THREAD

**Issue by allenking1028** [wangyu-/UDPspeeder#107]
折腾了好久，路由器上面2个都已经运行
<img width="752" alt="2017-12-31 1 52 57" src="https://user-images.githubusercontent.com/34980980/34461171-b4762696-ee5e-11e7-8b6c-de847bf17036.png">

串联的帖子翻了好多个，也各种试，就是不行。PC游戏会黑屏 PS4会NAT失败
![img_1252](https://user-images.githubusercontent.com/34980980/34461173-b95da940-ee5e-11e7-86d8-c1b475d3d24a.JPG)
我感觉我还是服务器端没有同时运行导致的。。。因为我看一个哥们的帖子 问题和我的一模一样
<img width="897" alt="2017-12-31 7 12 02" src="https://user-images.githubusercontent.com/34980980/34461185-ed0bb070-ee5e-11e7-896f-796f4caa1fbf.png">
求解

**Comment by wangyu-** [comment]
`netstat -nlp`结果是什么

**Comment by allenking1028** [comment]
Connected, host fingerprint: ssh-rsa 2048 BC:42:0A:39:1F:92:8D:98:02:A4:A9:BF:46:E8:98:00:00:
D7:F3:E8
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Dec 31 12:27:52 2017 from 173.194.93.33
veilolin@instance-4:~$ sudo -i
root@instance-4:~# netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program n
ame
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      783/sshd     
   
tcp6       0      0 :::22                   :::*                    LISTEN      783/sshd     
   
tcp6       0      0 :::456                  :::*                    LISTEN      814/python   
   
udp        0      0 0.0.0.0:47678           0.0.0.0:*                           628/dhclient 
   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           628/dhclient 
   
udp        0      0 0.0.0.0:10335           0.0.0.0:*                           814/python   
   
udp        0      0 10.140.0.4:123          0.0.0.0:*                           710/ntpd     
   
udp        0      0 127.0.0.1:123           0.0.0.0:*                           710/ntpd     
   
udp        0      0 0.0.0.0:123             0.0.0.0:*                           710/ntpd     
   
udp6       0      0 :::456                  :::*                                814/python   
   
udp6       0      0 fe80::4001:aff:fe8c:123 :::*                                710/ntpd        
udp6       0      0 ::1:123                 :::*                                710/ntpd        
udp6       0      0 :::123                  :::*                                710/ntpd        
udp6       0      0 :::17050                :::*                                628/dhclient    
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING     10751    1/init              /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     12307    1/init              /run/uuidd/request
unix  2      [ ACC ]     STREAM     LISTENING     12310    1/init              /run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING     22079    3211/0              /tmp/ssh-6geHwsWuTB/agent.3211
unix  2      [ ACC ]     STREAM     LISTENING     10726    1/init              /run/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     10749    1/init              /run/udev/control
root@instance-4:~#

**Comment by wangyu-** [comment]
服务端没有运行。

你的问题是不会用linux，不是不会用udp2raw和UDPspeeder。 关了

**Comment by allenking1028** [comment]
我是不会用啊。。我又不是编程的。所以才大哥你啊
