### ISSUE TITLE
如果想同时兼顾上网/视频/下载/游戏 设置为 -f2:1 -q1 和 -f20:10 --timeout 1 怎么样？

### ISSUE THREAD

**Issue by kagurainroy** [wangyu-/UDPspeeder#109]
我的VPS丢包不算严重 基本不会超过5%的样子 现在这个时间点（北京10:46am）是1%以内 平时基本2%-3% 高峰期大概可能会达到10% 

推荐设置里只给出了分别的两种方案 一种是 -f20:10 用于下载，网页，视频
一种是 -f2:4 -q1 用于玩游戏
因为我比较懒。。设置好了开机启动就不想再动了 所以想问一下
-f2:1 -q1 和 -f20:10 --timeout 1 这种设置 可行/有效么？
看了一下默认的-f20:10 是积攒200个包/积攒8MS 再发包 感觉8ms还是有点影响的 
而-f2:4 -q1 又是多倍发包 看视频下载又跑得快。。
但是如果是  -f20:10 --timeout 1 又怀疑1MS内能不能积攒20个包 然后发30个包出去
如果是-f2:1 -q1 因为是只发3个包 最多丢1个 有怀疑稳定性有没有影响

**Comment by wangyu-** [comment]
>如果是-f2:1 -q1 因为是只发3个包 最多丢1个 有怀疑稳定性有没有影响

有严重的影响，算一下概率就可以了：

%5丢包下3个包丢1+个的概率是0.72%，10%丢包下3个包丢1+个的概率是2.8%。
%5丢包下30个包丢10+个的概率是0.0001%，10%丢包下30个包丢10+个的概率是0.0089%。

>但是如果是 -f20:10 --timeout 1 又怀疑1MS内能不能积攒20个包 然后发30个包出去

` -f20:10 --timeout 1 --mode 0`准确来说不是攒20个udp包，然后发30个包出去。是在1ms内攒尽可能多的udp包，然后切成20个包，再发30个出去。 因为20个包是切出来的，不会出现包不够的情况。但是如果1ms内攒的包太少了，会造成overhead过大，浪费流量；不影响程序正常工作。

从省流量的角度，我建议你就用`-f20:10 --timeout 3`吧。

**Comment by kagurainroy** [comment]
数学不好。。让我算3个包丢1个包以上的概率我还会算。。30个包丢10个以上我就懵了。。
（如果可以的话麻烦指点一下计算30个包丢10个+概率的思路。。）
目前延迟比较低 那么考虑 -f20:4 -f20:5 -f10:2 -f10:5 -f15:5 应该会更节省流量一点吧？ 
在这些情况的下 --timeout 可不可以调到2或者1呢？
@wangyu-

**Comment by wangyu-** [comment]
>如果可以的话麻烦指点一下计算30个包丢10个+概率的思路。。

![capture](https://user-images.githubusercontent.com/4922024/35317492-e3448258-008b-11e8-8676-6336aa95f727.PNG)

`f(20,10,10%)=0.0089%` 就是`10%丢包下使用-f20:10参数后的丢包率`，也就是`30个包丢10+个的概率`

>目前延迟比较低 那么考虑 -f20:4 -f20:5 -f10:2 -f10:5 -f15:5 应该会更节省流量一点吧？

如果不考虑overhead，-fx:y就是 (x+y)/x倍流量。 

考虑overhead以后就不好算了。overhead跟承载的流量特点有关，不能简单地计算出一个数值来。 `-f20:10 --timeout 8`时，就我自己实际使用来说，overhead基本可以忽略了。

>在这些情况的下 --timeout 可不可以调到2或者1呢？

需要自己测试。

**Comment by HSXX** [comment]
可以多开几个
