### ISSUE TITLE
延迟增加一倍这样正确嘛？

### ISSUE THREAD

**Issue by EasonSummer** [wangyu-/UDPspeeder#11]
./speeder_amd64 -l0.0.0.0:8855 -r127.0.0.1:17952 -s -d0 -k "passwd" &
./speeder_arm -l0.0.0.0:17952 -r 44.55.66.77:8855 -c  -d0 -k "passwd" &
按上面命令配置的 延迟增加一倍 如何能调低延迟呢？

**Comment by wangyu-** [comment]
解决了？

能不能简单说下怎么解决的，以供别人参考
