### ISSUE TITLE
如何保持UDP加速

### ISSUE THREAD

**Issue by kusotom** [wangyu-/UDPspeeder#110]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)
我的服务器只有在这个窗口运行的情况下才能加速UDP，一旦关闭这个ssh访问窗口，加速就会失效
系统是debian  已经在启动项写入了/udpspeeder/speederv2_amd64 -s -l0.0.0.0:4096 -r127.0.0.1:ssr端口  -f2:4 -k "密码自定义" --mode 0 -q1 &
但是还是不行，能告知一下问题出在哪吗
![0 i cyrzl3 y xc0f 7 k](https://user-images.githubusercontent.com/34085967/35336899-c0987e2a-0154-11e8-865a-63be9559032d.png)

**Comment by ekucn** [comment]
你要用nohup方式运行 直接运行就是你这个情况

**Comment by kusotom** [comment]
好的，已解决，谢谢
