### ISSUE TITLE
OPENVPN+UDPspeeder+udp2raw成功连接，但网页打开反而变慢

### ISSUE THREAD

**Issue by wzdhws** [wangyu-/UDPspeeder#113]
openvpn的配置文件等都根据wiki里的示例来，openvpn成功连接上后，所有的网站都打开缓慢，但都能打开。

而且服务端的openvpn一直会出现这类错误：

Wed Jan 31 21:37:17 2018 along/127.0.0.1:43000 AEAD Decrypt error: bad packet ID (may be a replay): [ #91 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Jan 31 21:37:18 2018 along/127.0.0.1:43000 AEAD Decrypt error: bad packet ID (may be a replay): [ #96 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Jan 31 21:37:18 2018 along/127.0.0.1:43000 AEAD Decrypt error: bad packet ID (may be a replay): [ #97 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
Wed Jan 31 21:37:18 2018 along/127.0.0.1:43000 NOTE: --mute triggered...

请问是不是跟这个有关，该如何解决。

**客户端配置文件**
client
dev tun100  
proto udp 
remote 192.168.0.102 2500
resolv-retry infinite 
nobind
persist-key 
persist-tun  
ca ca.crt
cert along.crt
key along.key
redirect-gateway def1
dhcp-option DNS 8.8.8.8
keepalive 3 20
verb 3
mute 20
comp-lzo no
cipher none 
auth none
fragment 1200
mssfix 1200
sndbuf 4000000
rcvbuf 4000000
#txqueuelen 4000
mute-replay-warnings

**服务端配置文件**
local 0.0.0.0
port 6633
proto udp
dev tun100
ca /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key /etc/openvpn/server.key
dh /etc/openvpn/dh.pem
server 10.222.2.0 255.255.255.0
ifconfig 10.222.2.1 10.222.2.6
client-to-client
duplicate-cn
keepalive 10 60
cipher none
comp-lzo no
auth none
max-clients 50
persist-key
persist-tun
status /var/log/openvpn/openvpn-status.log
verb 3
mute 20
mssfix 1200
fragment 1200
sndbuf 4000000
rcvbuf 4000000
txqueuelen 4000

**虚拟机：**
./udp2raw_x86 -c -l0.0.0.0:8800  -r***.*.***.**:4020   -k "passwd" --raw-mode faketcp -a 
./speederv2_x86   -c -l0.0.0.0:2500   -r 127.0.0.1:8800   -f20:10 --mode 0 --report 10 

**vps：**
./udp2raw_amd64 -s -l0.0.0.0:4020  -r127.0.0.1:6610   -k "passwd" --raw-mode faketcp -a 
./speederv2_amd64   -s -l127.0.0.1:6610  -r 127.0.0.1:6633 -f20:10 --mode 0 --report 10

**Comment by wangyu-** [comment]
网页打开变慢是和什么环境对比的？是和直连对比的，还是和单独用openvpn对比的？

我建议你分别用openvpn+udp2raw 、openvpn+ udpspeeder测试，缩小问题的范围。

>所有的网站都打开缓慢

可否把主观感受换成可以量化的数据？比如ping的丢包率，scp/iperf3的速率

**Comment by leepoi** [comment]
我猜是openvpn导致变慢，因为使用了8.8.8.8 的dns解析，访问所有网站都不能走国内的CDN。

**Comment by wzdhws** [comment]
今天把服务端的openvpn换了个版本重装下，再串联试了下，正常了。
