### ISSUE TITLE
udp2raw + openVPN eat full traffic

### ISSUE THREAD

**Issue by alaa2003** [wangyu-/UDPspeeder#118]
hi
-- i configured both server + client for udp2raw as you explained
also configured udp2raw + openvpn followed guide: https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/openvpn_guide.md
-- i used your openvpn config for both server+client

-- i can ping 10.222.2.1 from client side 
1) how can i forward all traffic in client side , all traffic go through openvpn??
2) i think you said we should add "redirect-gateway" , but where we put that parameter server or client & what is full line we should add?
3) ip route add 44.55.66.77 via 44.55.66.1
how can add that line inside openvpn client config instead of enter it manually?
4) ip route add 44.55.66.77 dev XXX
XXX = eth0 or virtual TAP device card which related to openvpn ?
also how can add it manually inside ovpn client config
http://prntscr.com/ihhxcx

i hope you give full config for both  sides server + client which allow route all traffic

here are my full config:
Server:
udp2raw: http://prntscr.com/ihi0jt
server.conf  http://prntscr.com/ihhz5v
iptables http://prntscr.com/ihhzls
after run: http://prntscr.com/ihi1ys

client:
udp2raw: http://prntscr.com/ihi1b6
ovpn client: http://prntscr.com/ihi1ly
iptables: http://prntscr.com/ihi2m7

**Comment by wangyu-** [comment]
Hi, alaa2003.

1. This is the repo of UDPspeeder, you used the wrong repo.   
2. I noticed you are using third party image hosting site.  Those links will eventually expire, and this issue will be un-read-able for others. You can upload image directly to github, just drag image in to the input box and it works like a magic.

So, I suggest you to reopen this issue in udp2raw repo, and fix the image issue. I will give you some suggestions by then.

Thank you very much.

**Comment by alaa2003** [comment]
dear wangyu
thanks a lot for mention and great notice about drag/drop .. its amazing !
please delete this post
regards
Alaa

**Comment by wangyu-** [comment]
https://github.com/wangyu-/udp2raw-tunnel/issues/142
