### ISSUE TITLE
能麻烦作者说下UDPspeeder + openvpn + ss方案的大体步骤吗？多谢

### ISSUE THREAD

**Issue by w12928293** [wangyu-/UDPspeeder#12]
Server环境：GoogleCloud-Ubuntu 14.4
本地：树莓派+Win10
目的：吃鸡~~
试过做主的另一个项目udp2raw配合kcptun，感觉在大流量上面有不少提升，因为看到作者说UDPspeeder + openvpn + ss方案对跨服游戏很有帮助，想试试，不过没搞明白具体是怎么连，这个openvpn是起什么作用的

**Comment by wangyu-** [comment]
先配置好openvpn。

openvpn连通了之后，在中间串联个udpspeeder。openvpn client--->speeder client ---->speeder server---->openvpn server， 这样就是`udpspeeder+openvpn`。

配好了`udpspeeder+openvpn`之后，你可以用openvpn的ip（比如10.0.0.1）访问ss，这样ss的流量也会被加速。这就是`udpspeeder+openvpn+ss`了。

>这个openvpn是起什么作用的

ss同时会用到tcp和udp。udpspeeder只加速udp，所以你不能用udpspeeder这单独一个程序来加速ss；openvpn底层用的是udp协议，可以被udpspeeder加速，而openvpn上层可以承载任何流量，所以你用udpspeeder+openvpn一起配合就可以加速ss了。

**Comment by liyuhanaljlj** [comment]
请问一下udpspeeder+openvpn+ss是都配置在一台vps上面吗？

**Comment by myliyifei** [comment]
连海外主机  用openvpn 会直接墙掉IP吧。

**Comment by 346673164** [comment]
老哥。你ss如何转发udp的呢。

**Comment by recall704** [comment]
@myliyifei openvpn 的流量已经被 udpspeeder 封装了。
