### ISSUE TITLE
udpspeeder的其他使用方法

### ISSUE THREAD

**Issue by FH0** [wangyu-/UDPspeeder#124]
能不能不套用其他的代理软件，直接使用udpspeeder进行udp转发

**Comment by wangyu-** [comment]
可以，这样只能转发一个端口。

**Comment by FH0** [comment]
那server怎么设置启动命令呢，只转发一个端口的问题可以用iptables来解决吧

**Comment by FH0** [comment]
我在服务端运行

./speederv2_amd64 -s -l0.0.0.0:1190 -f2:4 -k "passwd"

提示缺少-r参数，要怎么样才能单独使用udpspeeder呢？

**Comment by FH0** [comment]
@wangyu- 

找了很久还是没有找到关于单独使用udpspeeder的例子

[https://github.com/wangyu-/UDPspeeder/blob/master/images/en/udpspeeder.PNG](url)

你的readme中第一张图的效果怎么实现呢，主要是server端怎么设置启动命令，麻烦解答一下吧

**Comment by wangyu-** [comment]
https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/kcptun_step_by_step.md

你看一下这个，udp2raw+kcptun。 udpspeeder原理上一样。
