### ISSUE TITLE
透明代理，油管QUIC走不通，chrome QUIC日志里却有连通日志，会是哪里的问题呢

### ISSUE THREAD

**Issue by imess** [wangyu-/UDPspeeder#126]
![snap1](https://user-images.githubusercontent.com/31499998/38677858-0dbbd7d6-3e92-11e8-812b-90208ff0fc68.jpg)

拓补如图，走ssredir，chrome关闭quic改走tcp能通，或者server端封住udp80 443出口也能通，200M电信y2b最高能跑到70多M，显然这时走的是kcptun这条通道，说明tcp透明代理成功。

chinadns能正常解析，说明ss-tunnel - udpspeeder这条道（udp53）也能通，同时speeder日志显示无异常。

iperf - speeder client - udp2rawclient2 - udp2rawserver2 - speeder server - iperf，20M/s速率测udp，结果满速，

redir - ss-server直连貌似可以走通，但速度实在不想提。

唯独QUIC udp443 走ssredir通不了，redir/speeder/ssserver日志都显示收发成功，并没有什么mtu之类的错误，用tcpdump 在应用和代理客户端抓包，有往返记录（inbound多过outbound），mtu1350貌似也无异常，但应用端就是通不了（感觉是握手问题？），局域网内y2b app和chrome网页转半天都出不来，但chrome quic页面里却有google家的quic连接成功记录（但不是y2b的）。路由、防火墙规则测遍了都没发现问题所在。所以请教高手，问题会出现在哪里，如何解决ss透明代理配合udp加速及raw穿透防火墙的问题。

**Comment by imess** [comment]
已解决。貌似油管QUIC会绕过TPROXY，其它udp流量却能正常流经透明代理。目前单独对QUIC的outbound udp443用nat redirect解决。油管QUIC打通任督二脉后，发现是TCP和UDP流量都在走，udpspeeder和kcptun都有log，反应明显快了不少。供后来者参考

`# SHADOWSOCKS - route marked udp traffic to local
	while ip rule delete from 0/0 to 0/0 table 100 2>/dev/null; do true; done
	ip route flush table 100 2>/dev/null
	ip rule add fwmark 0xf1/0xfd lookup 100
	ip route add local 0.0.0.0/0 dev lo table 100
	
	# Flush previous rules, delete chains and reset counters
	iptables -t nat -F  2>/dev/null
	iptables -t mangle -F  2>/dev/null
	iptables -Z
	
	# Default policies
	iptables -P FORWARD ACCEPT
	iptables -P INPUT 	ACCEPT
	iptables -P OUTPUT ACCEPT

	iptables -t mangle -D PREROUTING -j SHADOWSOCKS 2>/dev/null
	iptables -t nat    -D PREROUTING -j SHADOWSOCKS 2>/dev/null
	
	iptables -t mangle -F SHADOWSOCKS_MARK 2>/dev/null
	iptables -t mangle -N SHADOWSOCKS_MARK 2>/dev/null
	iptables -t mangle -A SHADOWSOCKS_MARK -m set --match-set bypass_dst dst -j RETURN
	iptables -t mangle -A SHADOWSOCKS_MARK -p tcp -j MARK --set-mark 0xfd/0xfd
	iptables -t mangle -A SHADOWSOCKS_MARK -p udp -j MARK --set-mark 0xfd/0xfd
	iptables -t mangle -A SHADOWSOCKS_MARK -j CONNMARK --save-mark
	
	iptables -t mangle -F SHADOWSOCKS 2>/dev/null
	iptables -t mangle -N SHADOWSOCKS 2>/dev/null
	iptables -t mangle -A SHADOWSOCKS -m conntrack --ctstate NEW -j SHADOWSOCKS_MARK
	iptables -t mangle -A SHADOWSOCKS -m conntrack --ctstate ESTABLISHED,RELATED -j CONNMARK --restore-mark
	iptables -t mangle -A SHADOWSOCKS -p udp ! --dport 443 -m mark --mark 0xfd/0xfd -j TPROXY --on-port 41673 --tproxy-mark 0xf1/0xfd
	#iptables -t mangle -A SHADOWSOCKS -p udp -m mark --mark 0xfd/0xfd -m limit --limit 30/min -j LOG --log-prefix 'UDP marked: ' --log-level debug
	
	iptables -t nat -F SHADOWSOCKS 2>/dev/null
	iptables -t nat -N SHADOWSOCKS 2>/dev/null
	iptables -t nat -A SHADOWSOCKS -p tcp -m mark --mark 0xfd/0xfd -j REDIRECT --to-ports 41673
	iptables -t nat -A SHADOWSOCKS -p udp -m mark --mark 0xfd/0xfd --dport 443 -j REDIRECT --to-ports 41673
	#iptables -t nat -A SHADOWSOCKS -p tcp -m mark --mark 0xfd/0xfd -m limit --limit 30/min -j LOG --log-prefix 'TCP marked: ' --log-level debug
	
	iptables -t mangle -A PREROUTING -j SHADOWSOCKS
	iptables -t nat    -A PREROUTING -j SHADOWSOCKS
	
	# udp2raw-tunnel rules
	iptables -D INPUT -j UDP2RAW 2>/dev/null
	iptables -F UDP2RAW 2>/dev/null
	iptables -N UDP2RAW 2>/dev/null
	iptables -A UDP2RAW -s serverip/32 -p tcp -m tcp --sport 43477 -j DROP
	iptables -A UDP2RAW -s serverip/32 -p tcp -m tcp --sport 53477 -j DROP
	
	iptables -I INPUT -j UDP2RAW`

**Comment by imess** [comment]
Forget it. NAT udp443 只是加快了quic失败应答，使得chrome或y2b之类的quic应用改走tcp，quic协议本身对nat方式支持并不友

好，两天测试下来，总结还是mtu的问题，由于套用多层加密，各层的分片不一和vps isp线路的不确定性，反复调试还是无法使得

线路path mtu始终接近quick要求的1350（ipv4），最络还是选择放弃quic，block掉了udp443和80。目前除QUIC之外的正常udp流量

还是能透明转发及加速的。防火墙规则有大调整，代理客户端现非网关，上面的仅供大体参考

**Comment by wangyu-** [comment]
>好，两天测试下来，总结还是mtu的问题，由于套用多层加密，各层的分片不一和vps isp线路的不确定性，反复调试还是无法使得

贴一下udp2raw和UDPspeeder的参数看看。

>redir - ss-server直连貌似可以走通，但速度实在不想提。

我看你的描述，可能QUIC直连就没通。如果你想继续追这个问题，最好确认一下直连的时候通不通。

如果你不想继续追了，只是想让QUIC工作，可以换个方法。 直接用udp2raw+UDPspeeder+openvpn做透明代理（或者udp2raw+tinyfecVPN）。 配置起来简单很多，而且我测试过QUIC是没问题的。

**Comment by imess** [comment]
udp2raw和udpspeeder的参数基本都是默认的，udpspeeder也只有用mode 0， chrome://net-internals/#quic才能刷出quic sessions。mode1的话，mtu从1100到1600试了个遍，chrome完全刷不出quic。$$redir和$$server的mtu必须硬性指定为1490以上，否则log里会出现大量fragment（$$直连确认过，可以通，但速度感人，y2b是几百k/s的级别，然后慢慢被qos至无速度）。

另外本地抓包发现，quic应用发起连接时有部分是走shanghai的google节点，故为防止直连，除了根据ip列表分流外，网关也显式地将udp443和80 route至内网的透明代理端，故quic不大可能走直连。
 
今天又换了个server测试，udp2raw和speeder用默认参数，quic一开始也是通的，最高飙到37Mbps，然后又慢慢降至无速度，最后chrome的quic session消失，y2b又自动切换至tcp，tcp则一直稳定在20-30Mbps左右，10几个高清视频下来都无断流现象。难不成是没绕过qos？或者是vps服务商那边的问题?

## **UDPspeeder和udp2raw-tunnel的设置**
![snap21](https://user-images.githubusercontent.com/31499998/38808641-7bf206d4-41b3-11e8-99b1-32d9aa03908c.jpg)

## ** UDPspeeder和udp2raw-tunnel的连接log和chrome quic sessions **
![snap11](https://user-images.githubusercontent.com/31499998/38808694-a38c73fa-41b3-11e8-8338-a38f17fc816c.jpg)

## ** y2b quic 表现**
![snap16](https://user-images.githubusercontent.com/31499998/38808730-c51861aa-41b3-11e8-8979-62c5b28e93f5.jpg)

## ** 最后无论怎么打开y2b都是这样的 **
![snap24](https://user-images.githubusercontent.com/31499998/38808780-e77a2ca6-41b3-11e8-827d-686eaf006089.jpg)

## ** 本地和server抓包 **
![snap15](https://user-images.githubusercontent.com/31499998/38808859-33d65804-41b4-11e8-9794-2ad47fb2b685.jpg)

## ** $$ **
![snap25](https://user-images.githubusercontent.com/31499998/38808897-4d86d08a-41b4-11e8-93a0-cbb91b31273c.jpg)

## ** 网关将特定流量route至本地代理 **
![snap30](https://user-images.githubusercontent.com/31499998/38809041-c90684ee-41b4-11e8-9e07-391b2a6c4399.jpg)

## ** 本地代理分流国外流量 **
![snap29](https://user-images.githubusercontent.com/31499998/38809072-e5229c8a-41b4-11e8-84f3-5176655e18f8.jpg)

**Comment by wangyu-** [comment]
你的$$有没有用`--port-reuse`选项（或者其他的不常用选项）。有人反馈开了`--port-reuse`的情况下，串联UDPspeeder后UDP会不稳定。 去掉`--port-reuse`就正常了。把不常用/非必需的选项都去掉。

另外试一下把没用的iptables清理掉。

https://github.com/wangyu-/tinyfecVPN/wiki/清空iptables的方法

>udp2raw和udpspeeder的参数基本都是默认的，udpspeeder也只有用mode 0， chrome://net-internals/#quic才能刷出quic sessions。

就用mode 0，不需要改mtu。配合$$这种没用户态分片能力的程序，不要用mode 1。

>今天又换了个server测试，udp2raw和speeder用默认参数，quic一开始也是通的，最高飙到37Mbps，然后又慢慢降至无速度，最后chrome的quic session消失，y2b又自动切换至tcp，tcp则一直稳定在20-30Mbps左右，10几个高清视频下来都无断流现象。难不成是没绕过qos？或者是vps服务商那边的问题?

如果kcptun+udp2raw正常，应该不是QOS的问题。

>$$redir和$$server的mtu必须硬性指定为1490以上，否则log里会出现大量fragment

在kcptun和udpspeeder里面，设置了mtu以后，程序会帮你把数据包分片到mtu的值。 貌似$$里面的mtu设置是没用的。

作者在这个issue里说：https://github.com/shadowsocks/shadowsocks-libev/issues/1956 

```
This option is only for debug, which is planed to remove in the future release.
```
(作者说这个选项仅供debug用，以后可能会被去掉。)

这个issue里说：https://github.com/shadowsocks/shadowsocks-libev/pull/1959
```
Applications using UDP protocol is responsible for decreasing packet size when observing fragmentation. The mtu here is only for debug.
```

(作者说，上层应用应该 **自行** 减小数据包的大小；mtu这个选项只是打印debug信息用的，所以你调了MTU只是后只是log里不报错了，实际上没有作用)

>$$直连确认过，可以通，但速度感人，y2b是几百k/s的级别，然后慢慢被qos至无速度

你在加上UDPspeeder+udp2raw的情况下，用udp的netcat测试一下udp通不通。先试一下发送几个字符，再试一下一次发送1350个字符。两个方向都测试一下，看到底通不通。  再跟$$redir直连的情况对比一下，看看netcat的测试结果有什么区别。

$$-redir搭透明代理我没试过。 我试过$$tap+$$-libev server+kcptun+UDPspeeder, Chrome的quic是正常的。

**Comment by imess** [comment]
> 你的$$有没有用--port-reuse选项（或者其他的不常用选项）。有人反馈开了--port-reuse的情况下，串联UDPspeeder后UDP会不稳定。 去掉--port-reuse就正常了。把不常用/非必需的选项都去掉。

默认参数并没有开启端口复用

> 在kcptun和udpspeeder里面，设置了mtu以后，程序会帮你把数据包分片到mtu的值。 貌似$$里面的mtu设置是没用的。

原来是多余的，不过去掉$$两端的mtu选项，结果也还是一样。

>可以用udp的netcat测试一下udp(在串联udpspeeder和udp2raw的情况下)。先试一下发送几个字符，再试一下一次发送1350个字符(手工发送和quic一样长的数据包)。两个方向都测试一下，看到底通不通、哪个方向不通。 再跟$$redir直连的情况对比一下，看看有什么区别。

其实nc早就测过了，包括iperf之类的，双向都是通的，昨晚单独用nc串在udpspeeder两端（中间是udp2raw），fec调到3倍(20:40)，nc两边收到的字符依然是完整无缺，但油管的quic死活不灵。

>我有个问题，既然你都配了openvpn了，全流量加速这种事情为什么不交给vpn，配置起来比$$简单很多也稳定很多，不需要tcp udp dns分开处理

主要是痴迷kcp的惊艳效果吧，毕竟几年来一直稳定使用。图片可能存在误导，openvpn其实是为了在外面和家里无缝对接的，也方便集中验证（公司的同事有需求）。实在调试不出问题所在，下一步会尝试你给的方案。

刚才把fec调到3倍，用上面的参数又抓了几次QUIC包，来回的包都能如数收到，但有checksum error，会不会是数据包的完整性存在问题。感谢你的解答。

## 特定流量去程：lan host GT1 -> lan gateway -> lan host NS1（proxy）  -> lan gateway -> vps
![snap33](https://user-images.githubusercontent.com/31499998/38860702-62148c18-4263-11e8-996c-f441e22e57fd.jpg)

## 回程： vps -> lan gateway -> lan host NS1 -> lan host GT1
![snap32](https://user-images.githubusercontent.com/31499998/38860709-68ef2b60-4263-11e8-8732-1603900f6b7f.jpg)

**Comment by wangyu-** [comment]
>主要是痴迷kcp的惊艳效果吧，毕竟几年来一直稳定使用。图片可能存在误导，openvpn其实是为了在外面和家里无缝对接的，也方便集中验证（公司的同事有需求）。实在调试不出问题所在，下一步会尝试你给的方案。

想保留kcp的话，可以用kcp+$$加速tcp，udpspeeder+openvpn加速udp和icmp。我个人感觉，openvpn对udp的支持比$$要稳很多。

大概的方法：
在wiki里的教程基础上，加一条iptables，对于udp和icmp流量用`-j --set-mark <mark>`，然后再ip rule的规则里用from xxxx fwmark <mark>，这样只有udp和icmp会被路由到openvpn。tcp流量用你原来的办法$$+kcptun做透明代理。 kcp+$$ 和 udpspeeder+openvpn这俩组合独立工作，互不影响。

我没测试过，不过原理上应该没问题。

**Comment by imess** [comment]
看来quic走$$还是行不通，谢谢你的方案，我去研究研究。

**Comment by fbion** [comment]
mark
