### ISSUE TITLE
用这个能降低游戏延迟？还是反而增加了？

### ISSUE THREAD

**Issue by QiXianPu** [wangyu-/UDPspeeder#13]
( ⊙ o ⊙ )想找个能降低游戏延迟的方案。

**Comment by wangyu-** [comment]
根据你怎么定义延迟，有不同答案。

常见的两种定义：

1.物理延迟，不考虑丢包的影响。

2.逻辑上的延迟，考虑丢包后重传（可能是tcp重传，也可能是游戏自己实现的udp重传）。

对于1，不能降低。

对于2，可以有效降低。

不论是对于1还是2，只要配置合理，不会增加延迟。

**Comment by QiXianPu** [comment]
解释的真好，我先去看看如何配置

**Comment by QiXianPu** [comment]
@wangyu- ʕ•ᴥ•ʔ
我用来加速ss代理的游戏数据的话该怎么配置参数，我看啦参数，-d -t -j 这些参数该怎么设置才好勒？求教。

**Comment by wangyu-** [comment]
>我用来加速ss代理的游戏数据的话该怎么配置参数，我看啦参数，-d -t -j 这些参数该怎么设置才好勒？

如果不知道怎么设置就用-d1或者d2，其他参数默认。

>使用后用的流量大概是没用时的几倍？

-d1 是2倍流量，-d2是3倍流量，依次类推

>我用的x86-64的openwrt，还需要自己编译不

不用，认真读readme和release里的说明。

**Comment by QiXianPu** [comment]
ʕ⊙ᴥ⊙ʔ
谢了
