### ISSUE TITLE
加入-i参数之后udp不通

### ISSUE THREAD

**Issue by zardonc** [wangyu-/UDPspeeder#130]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)

使用的搬瓦工vps
不加-i参数一切正常,单独用udpspeeder或串联udp2raw都可以正常连接，加入-i参数后服务器端除了正常启动参数之后没有任何输出，检测nat类型显示udpblocked，此时和vps依旧是连接的状态好像是只有udp包不通，尝试过清空iptables问题依旧

server
./speederv2 -s -l0.0.0.0:2712 -r127.0.0.1:科学端口 -k "passwd" --mode 0 -f10:10 --timeout 3 --disable-obscure -i10

client用的梅林:
./speederv2 -c -l0.0.0.0:1092 -r我的ip:2712 -f10:10 -k "passwd" --mode 0 -i10

[2018-05-15 00:55:04][INFO]argc=13 ./speederv2_amd64 -s -l0.0.0.0:2712 -r127.0.0.1:科学端口 -k 7c391af8 --mode 0 -f10:10 --timeout 3 --disable-obscure -i10 
[2018-05-15 00:55:04][INFO]obscure disabled
[2018-05-15 00:55:04][INFO]jitter_min=0 jitter_max=0 output_interval_min=10 output_interval_max=10 fec_timeout=3 fec_data_num=10 fec_redundant_num=10 fec_mtu=1250 fec_queue_len=200 fec_mode=0

**Comment by wangyu-** [comment]
试一下把两边的udpspeeder更新到20171125这个版本。

**Comment by zardonc** [comment]
都更新到了最新的版本，还是老样子，不加-i就是正常的

**Comment by wangyu-** [comment]
```
server
./speederv2 -s -l0.0.0.0:2712 -r127.0.0.1:科学端口 -k "passwd" --mode 0 -f10:10 --timeout 3 --disable-obscure -i10

client用的梅林:
./speederv2 -c -l0.0.0.0:1092 -r我的ip:2712 -f10:10 -k "passwd" --mode 0 -i10
```

我注意到了一个问题，你一边用 --disable-obscure 另一边边不用，是不行的。readme里面有说这个参数两边必须相同。

**Comment by zardonc** [comment]
抱歉，我没有黏贴全client这边是加上--disable-obscure 的，应该是./speederv2 -c -l0.0.0.0:1092 -r我的ip:2712 -f10:10 -k "passwd" --mode 0 --disable-obscure  -i10 反正不加-i就正常，加了就不行udpblocked

**Comment by wangyu-** [comment]
你分别贴一下加`-i`和不加`-i`的完整命令（两端），,除了密码外，什么也不要改，原样贴过来。

你的路由器用的是哪个版本的client，是arm版吗？

**Comment by zardonc** [comment]
加了-i的
server
./speederv2 -s -l0.0.0.0:2712 -r127.0.0.1:16821 -k "passwd" --mode 0 -f10:10 --timeout 3 --disable-obscure -i10
client用的梅林:
./speederv2 -c -l0.0.0.0:1092 -r23.106.137.18:2712 -f10:10 --timeout 3  -k "passwd" --mode 0 --disable-obscure -i10

不加的
server
./speederv2 -s -l0.0.0.0:2712 -r127.0.0.1:16821 -k "passwd" --mode 0 -f10:10 --timeout 3 --disable-obscure
client用的梅林:
./speederv2 -c -l0.0.0.0:1092 -r23.106.137.18:2712 -f10:10 --timeout 3  -k "passwd" --mode 0 --disable-obscure

我是吧命令保存下来原样复制的，所以除了-i其他是一模一样的，换端口我也试过，结果一样

**Comment by wangyu-** [comment]
>你的路由器用的是哪个版本的client，是arm版吗？

**Comment by zardonc** [comment]
是的arm

**Comment by wangyu-** [comment]
我用你给的参数试了一下(几乎就是原样不动)，复现不了这个问题。我的client是arm版，server amd64版和x86版都试过。

>都更新到了最新的版本，还是老样子，不加-i就是正常的

你是同样的VPS和路由器，同样的端口，把-i加上就不行，去掉就立即可以了？

多尝试几次是否也一样，可以稳定复现这个问题？

**Comment by zardonc** [comment]
是的，我换了不同的端口，不同的server ip(我有几个不同的vps在美国，但是线路不同，不是同一个城市的)，然后我本地的电信重新拨号换了ip，结果都是这样，不加-i都ok，加了就不行，我的路由器是网件R7000刷了koolshare的梅林，应该很多人都是这个，觉的很奇怪

**Comment by wangyu-** [comment]
你的路由器空闲内存有多少？贴一下`free -m`的结果

**Comment by zardonc** [comment]
![20180516223301](https://user-images.githubusercontent.com/21338963/40123932-f0900c58-5959-11e8-8f00-8c26ca0c48f1.png)
应该不是内存的问题吧

**Comment by zardonc** [comment]
应该是我这边什么设置的问题，我再看看，刚才我试了一下只在server端加上-i参数client不加依旧是正常的，client加上就不通了。先问下像这种情况只在server端加上-i会产生什么效果 ?

**Comment by wangyu-** [comment]
>先问下像这种情况只在server端加上-i会产生什么效果 ? 

只有server 到client方向有抗突发性丢包的功能。

**Comment by zardonc** [comment]
你好，问题解决了，刚才想了下基本是路由器设置的问题，后来我看了下梅林内置的脚本，结合之前另一个issue，总算发现了问题所在，梅林内置的脚本-i的参数填的是-interval按照另一个issue里你说的，interval暂时不生效，我把它改成-i重启一下就好了.....我去koolshare那边反馈下

**Comment by wangyu-** [comment]
@zardonc 

我看你client端贴的是命令，我以为你是敲命令测试的。 

在插件作者修复这个问题之前，暂时可以把 `-i 10`加到梅林的`其他参数`那里。

**Comment by wangyu-** [comment]
稍后我更新一个版本吧，把缺失的`--interval`补上。这样梅林插件那边就不用改脚本了，只要更新下UDPspeeder程序就可以了。

**Comment by zardonc** [comment]
好的，辛苦啦，搞了半天是这个原因真没想到，还有真的谢谢这个工具，否则我几个美国的vps真的是要废了

**Comment by wangyu-** [comment]
我已经更新了，修复了`--interval`的问题。如果你使用起来没问题，就可以反馈给插件作者了。
