### ISSUE TITLE
UDP加速双兄弟是否支持单server多client

### ISSUE THREAD

**Issue by lcpp1123** [wangyu-/UDPspeeder#134]
作者好，抱歉又有一个问题。单VPS已经部署好OPENvpn+UDP加速2兄弟，并在另一个liunxA上实现了联通。想问一下在机器A一直开着的情况下。同样配置信息的liunx机器B能否连接上server使用？

**Comment by wangyu-** [comment]
没问题的。readme里有写。

目前我写的几个网络相关的程序里，只有tinyfecVPN不支持单server多client。

**Comment by lcpp1123** [comment]
抱歉，尝试后可以连接上，现在还有个问题。感觉自己伸手党了，抱歉。
在之前成功的场景里，我使用的是台式PC机A虚拟安装liunxA+，然后用同局域网台式PC机B去连接A+，成功连接并上网成功。在VPS没有变化的情况下，使用现在的场景，台式PC机B虚拟安装liunxB+，然后直接使用台式PC机B上的openvpn连接B+端口，成功连接。但是发现没有网络。本地IP 10.0.8.6，无法ping通10.0.8.5及VPS的实际IP地址，也无法上网。可以ping通虚拟机B+的IP。您知道是什么方便的问题吗？

**Comment by wangyu-** [comment]
参考一下:

https://github.com/wangyu-/UDPspeeder/wiki/win10系统UDPspeeder-OpenVPN的完整设置

https://github.com/wangyu-/UDPspeeder/issues/108

**Comment by lcpp1123** [comment]
嗯嗯，问题解决了。您知道原因吗？就是BUG？

**Comment by wangyu-** [comment]
>ISSUE中多次有人遇到了openvpn连接以后，ping不通虚拟机的问题。疑似是openvpn push "redirect-gateway def1"选项的BUG（不过我自己没有遇到过，有可能这个BUG跟openvpn的版本有关）。

**Comment by lcpp1123** [comment]
好吧，我的openvpn server版本
OpenVPN 2.4.0 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul 18 2017
library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
openvpn client版本
OPENVPN GUI V11.10.0.0
两套环境除了虚拟机的IP获取方式不同，其他都一样。
可能也是偶发性的BUG吧。

**Comment by wangyu-** [comment]
@lcpp1123  你是用`route ADD` 手动添加路由解决的还是用后来的新方法解决的？

**Comment by lcpp1123** [comment]
希望大佬顺便出一个openvpn分流的客户端，哈哈，方便吃鸡玩游戏

**Comment by lcpp1123** [comment]
大佬，从加速游戏的角度来看，AnyConnect和openvpn，使用哪个更合适呢？
