### ISSUE TITLE
分流方案问题请教

### ISSUE THREAD

**Issue by gemhowie** [wangyu-/UDPspeeder#135]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)

你好，最近看到了你的 UDPSpeeder ，想尝试改善一下丢包的问题，但是切换过程中有些疑问，有空的话希望能够帮我解答一下，谢谢

在 ubuntu 上，我原本的方案是 $$ + redsocks2 + overture，iptables 设置 cn_list_ip 只将国外 tcp 流量转给 redsocks2 ，redsocks2 再转给 $$-client，你可以忽略 redsocks2 这层，就当做 iptables 将国外 tcp 流量转给 $$-client ，我加 redsocks2 主要是用它的 autoproxy 功能自动记录黑名单。

现在加入 UDPSpeeder 和 udp2raw

TCP/UDP -->

-->fork1-> iptables (国外udp流量) --> $$-redir --> UDPSpeeder client -->  udp2raw client ->  udp2raw server -> UDPSpeeder server ->  $$-server

-->fork2-> iptables (国外tcp 流量) --> $$-local -->  $$-server 

1）我没用过 kcptun，只用BBR，开两个 $$-client ，上面的方案 是不是就可以省掉 tinymapper ? 

更新…我傻了，iptables转发或者tinymapper都比上面用屁股想出来的方案靠谱，不用回答这个问题了
 
想了下，如果不用 kcptun 感觉有点蠢，在 ubuntu 上只加速 udp ，又不玩游戏，意义不大，我知道 kcptun 可以把 tcp 伪装成 udp ，然后多倍发包来提速，但是太拥堵带宽，udpspeeder的 FEC 可以接受，然后 kcptun 要和 UDPSpeeder 串联才能加速 tcp 吗?(不是指暴力发包这种加速，指的是前置纠错这种)， kcptun 发一倍的包给 UDPSpeeder client，UDPSpeeder client 发1.5倍 给 UDPSpeeder server ,   UDPSpeeder server 进行前置纠错，减少丢包重传的时间。

TCP/UDP --> iptables (国外tcp/udp流量) --> $$-redir -->

-->fork1-> Kcptun client --> UDPSpeeder client -->  udp2raw client ->  udp2raw server -> UDPSpeeder server ->  Kcptun server --> $$-server

-->fork2-> UDPSpeeder client -->  udp2raw client ->  udp2raw server -> UDPSpeeder server ->  $$-server 

这样连的话，两条通道的UDPSpeeder 和 udp2raw 都要分别开独立进程？

2）我好像在哪看到过 kcptun  好像也支持 FEC，如果支持，是不是就可以不用串联 UDPSpeeder 从而实现 FEC 方式的加速 ?
 
TCP/UDP --> iptables (国外udp流量) --> $$-redir -->

-->fork1-> Kcptun client ( FEC )--> udp2raw client ->  udp2raw server ->  Kcptun server --> $$-server

-->fork2-> UDPSpeeder client -->  udp2raw client ->  udp2raw server -> UDPSpeeder server ->  $$-server

3）像这种架构的加速方案，怎么测试网络的丢包率，iptables 没有转发icmp的流量，本身的丢包率应该能够直接ping出来，加速后的丢包率，只能用UDPping或者其他tcpping工具检测吗？

4）从推荐上看 UDPspeeder 基本都是配合 openVPN 来用，openVPN的优势是所有流量能走加速通道，但是我要实现智能分流，就像上面的方案，国内直连，国外加速，毕竟开了openVPN后，访问国内只加速本机到服务器的路段意义不大且耗费流量。或者是不是我对openvpn理解不够，有其他方案，比如iptables 也能转发 国外流量给 openvpn 通道 之类的....
简单点问，就是openvpn的优势及常见使用场景

**Comment by wangyu-** [comment]
>1）我没用过 kcptun，只用BBR，开两个 $$-client ，上面的方案 是不是就可以省掉 tinymapper ?

>更新…我傻了，iptables转发或者tinymapper都比上面用屁股想出来的方案靠谱，不用回答这个问题了

也没什么不靠谱。很多人都开2个$$-redir用。

>TCP/UDP --> iptables (国外tcp/udp流量) --> $$-redir -->

>-->fork1-> Kcptun client --> UDPSpeeder client --> udp2raw client -> udp2raw server -> UDPSpeeder server -> Kcptun server --> $$-server

>-->fork2-> UDPSpeeder client --> udp2raw client -> udp2raw server -> UDPSpeeder server -> $$-server

>这样连的话，两条通道的UDPSpeeder 和 udp2raw 都要分别开独立进程？

对，两个通路分别开udp2raw和UDPspeeder

>2）我好像在哪看到过 kcptun 好像也支持 FEC，如果支持，是不是就可以不用串联 UDPSpeeder 从而实现 FEC 方式的加速 ?

是。 用kcptun自己的FEC就可以了。加UDPspeeder收益不大，kcptun+UDPspeeder只是有更多的可调参数。

>3）像这种架构的加速方案，怎么测试网络的丢包率，iptables 没有转发icmp的流量，本身的丢包率应该能够直接ping出来，加速后的丢包率，只能用UDPping或者其他tcpping工具检测吗？

直接ping是ICMP流量，只能测出来ICMP的丢包。 TCP/UDP/ICMP的丢包可能相差很大，以至于直接ping测出来的没有参考性。

测TCP的“丢包”。tcpping只是发个syn包等对面回复ack包。用这种测法测TCP的“丢包”，不太靠谱。这只能测出来建立握手连接阶段的“丢包”。 TCP是可靠传输协议，一般都是用测iper3测TCP的传输速度来测TCP连接的质量。 好像很少有人会测TCP的丢包。

测UDP的丢包。以前我都是串联个VPN上去，然后通过VPN来ping，这样Ping出去的流量是UDP的。后来我觉得太麻烦，也没找到其他的好的工具，就写了个UDPping，建议你就用这个吧。

>4）从推荐上看 UDPspeeder 基本都是配合 openVPN 来用，openVPN的优势是所有流量能走加速通道，但是我要实现智能分流，就像上面的方案，国内直连，国外加速，毕竟开了openVPN后，访问国内只加速本机到服务器的路段意义不大且耗费流量。或者是不是我对openvpn理解不够，有其他方案，比如iptables 也能转发 国外流量给 openvpn 通道 之类的....
简单点问，就是openvpn的优势及常见使用场景

你对VPN理解不够。用VPN(包括openVPN)+ ip rule+ ip route + tables，可以实现各种复杂的分流。 $$能实现的VPN也能实现，通常VPN的实现更简洁。

>简单点问，就是openvpn的优势及常见使用场景

openvpn转发udp连接比$$稳，配置简单，奇怪的问题少。openvpn支持tcp/udp/icmp，$$不能转发icmp。  

$$可以配合kcptun，kcptun是kcp协议+FEC，加速TCP理论上来说比纯FEC的UDPspeeder好。openvpn基本上不能配合kcptun。

**Comment by gemhowie** [comment]
感谢解答，我转openvpn了
