### ISSUE TITLE
Udpspeeder与Udp2raw串联之后，PS4不支持ip碎片封包

### ISSUE THREAD

**Issue by cyrilliao** [wangyu-/UDPspeeder#138]
现象（分了三种情况测试）：
1. Udpspeeder与Udp2raw串联之后，PS4测速之后，不支持ip碎片封包，MHW也无法联机，具体设置如下：
[<img src='http://i2.bvimg.com/647356/eee69a8ef36d0855.png'>](url)
[<img src='http://i2.bvimg.com/647356/88c4d97ca29f7963.png'>](url)
[<img src='http://i2.bvimg.com/647356/e5329ae87702031d.png'>](url)

2. 分在服务端和路由端单独运行Udpspeeder或者Udp2raw也不行，情况如下：
   2.1 在服务端和路由端只都开了Udpspeeder，PS4测试NAT失败
[<img src='http://i2.bvimg.com/647356/0189485de8cc4a73.png'>](url)
[<img src='http://i2.bvimg.com/647356/5a10d286ec93429e.png'>](url)
[<img src='http://i2.bvimg.com/647356/17c80e7fa58116fe.png'>](url)
   
  2.2 在服务端和路由端只都开了Udp2raw，PS4不支持ip碎片封包
[<img src='http://i2.bvimg.com/647356/1aad10ae41c0e137.png'>](url)
[<img src='http://i2.bvimg.com/647356/6cf5360beca22f14.png'>](url)
[<img src='http://i2.bvimg.com/647356/b57485d86668cd3a.png'>](url)

机器情况：
Centos 6.9 64位，
内核版本：4.11.8-1.el6.elrepo.x86_64
使用魔改BBR加速（Lotsever和BBR也尝试过）
服务器udpspeeder版本为：W大大在20171125发布的版本
路由器是AC68u，梅林7.9，科学插件版本为3.9.9

附上本人的SSR设置（不知道是否有影响）：
[<img src='http://i2.bvimg.com/647356/d53531878c97bd4a.png'>](url)
[<img src='http://i2.bvimg.com/647356/8a6fb3a8dc3147bb.png'>](url)

之前在论坛也看到有一个基友也同样遇到这个问题（帖子原地址：[http://koolshare.cn/thread-132711-1-1.html](url)），W大大也给了一些建议（包括增加参数如：--mtu 400、udpspeeder加上--mtu 350、udp2raw加上 --hb-len 350），我也试过了，但是依旧没有解决问题。这个帖子的最后也没有一个方法可以解决的，所以就来这里发issue请教各位大大了。

**Comment by wangyu-** [comment]
你好，感谢你的三种情况测试。

>2.2 在服务端和路由端只都开了Udp2raw，PS4不支持ip碎片封包

这个是符合预期的，单独udp2raw不支持分片。

>分在服务端和路由端单独运行Udpspeeder或者Udp2raw也不行，情况如下：
2.1 在服务端和路由端只都开了Udpspeeder，PS4测试NAT失败

这个是有可能符合预期的，可能你的网络到国外UDP不通。

>1.Udpspeeder与Udp2raw串联之后，PS4测速之后，不支持ip碎片封包，MHW也无法联机

这个不符合预期。这个问题我复现不了(我本人没有梅林路由器和PS4，不过我找别人测试过这个游戏，复现不了，在他的环境上正常)。 目前为止只有俩人反馈过类似问题。

目前我也没什么好的追查办法，一些建议：

1. 检查一下服务端的 $$r是否开启了`--port-reuse`，如果有，关掉。

2. 用wiki上的方法清空VPS的iptables重试

3. 连别人的（经测试没问题的）VPS测试，观察问题是否存在

4. 用别人的(经测试没问题的)路由器去连你的VPS，观察问题是否存在

**Comment by cyrilliao** [comment]
非常感谢w大的回复，我尝试以上建议之后，再进一步在这里反映

**Comment by cyrilliao** [comment]
经过两天（不太严谨的）测试，我来反映一下情况：
我手上刚好有两个VPS主机：
一台是Vultr的JP线路，一台是GigsGigs的HK线路。
两台主机我都问了“是否可以转发UDP”的问题，回复分别如下：

Vultr JP
[<img src='http://i1.bvimg.com/647356/06d663a27b6c746a.png'>](url)

GigsGigs HK
[<img src='http://i1.bvimg.com/647356/0f85b49818cfeea0.png'>](url)

然后我分别在两台VPS上进行了测试。为了测试条件的一致性（事实上也不可能完全一致），系统都是Centos 6.9，内核是4.11.8-1.el6.elrepo.x86_64，SSR的脚本是【逗比根据地】的[《『原创』ShadowsocksR MudbJSON模式多用户一键脚本 支持流量限制等》](https://doub.io/ss-jc60/)，在配置$$R的过程中，【每个端口设备连接数”我使用的是“无限（默认）”】（其实是$$R中的-protocol_param-参数为空），不知道这一步会否对-port reuse-进行了开启，但是结果却有不一样的影响（后面会详述）。

结果：
Vultr JP：串联成功后，PS4测试网络的时候，完全正常，可以分片（但是由于这个线路不稳定，日常使用中我不会优先使用）
GigsGigs HK：串联成功后，情况依旧如Issue所说（issue发问的就是基于这个VPS来测试的）

问题：如果两个服务器，已经用了一样的配置来测试了，但是出现了两个不一样的结果，是否我的VPS作出了什么限制？如果是的话，我在选用VPS上，应该注意什么问题？希望W大大可以给些建议

针对-port reuse-，字面上理解为端口复用，但是实际上是什么我在Google找了很久，包括其关闭方法，搜到的资料也是凤毛麟角T_T。于是我根据自己的理解，尝试做了另两个测试，所以这个测试不一定严谨或者有根据。

另外一个测试：
我安装了【逗比根据地】的[CentOS/Debian/Ubuntu ShadowsocksR 单/多端口 一键管理脚本](https://doub.io/ss-jc42/)，这个脚本我也只开一个端口，【每个端口设备连接数”我使用的是“无限（默认）”】（其实是$$R中的-protocol_param-参数为空）。
但是结果依旧。
【每个端口设备连接数”我使用的是“1”】（其实是$$R中的-protocol_param-参数为1）
出现$$R国外链接PD的情况，Udpspeeder在启用的时候出现错误。

另一个测试II：
安装了【秋水逸冰】的[Shadowsocks 一键安装脚本（四合一）](https://teddysun.com/486.html)，其中$$R中的-protocol_param-参数为空，$$R正常，但是串联之后依然出现不能分片的情况。

至此，或许可以判定是GIgsGigs的VPS的问题了。但是由于该线路比较优秀，所以想作为长期使用对象，所以还是想办法来解决问题。W大大您之前提到的关闭-port reuse-，可以给我一个相对详细的教程吗？包括如何查看是否开启以及如何关闭。（因为关于-port reuse-我在Google找到的实在太少，问了一些脚本的编写人员，也无法得到答案）我可以再作进一步测试。

最后还是非常感谢W大，开发了这么好的东东，让我无聊的生活多了一个可以折腾的东西，O(∩_∩)O

**Comment by wangyu-** [comment]
你好，感谢你的测试。

>问题：如果两个服务器，已经用了一样的配置来测试了，但是出现了两个不一样的结果，是否我的VPS作出了什么限制？如果是的话，我在选用VPS上，应该注意什么问题？希望W大大可以给些建议

有可能是VPS的问题，应该不是VPS故意做了什么限制。有可能是VPS的线路上有tcp代理之类的东西，faketcp/udp2raw无法有效穿透tcp代理。 选VPS最好选有独立IP的，不过有独立IP不一定能保证faketcp一定没问题，所以还是得以自己的测试为准。 也不用过分担心，从ISSUE的反馈来看，绝大多数有独立IP的VPS都是没问题的。

>W大大您之前提到的关闭-port reuse-，可以给我一个相对详细的教程吗？包括如何查看是否开启以及如何关闭。（因为关于-port reuse-我在Google找到的实在太少，问了一些脚本的编写人员，也无法得到答案）我可以再作进一步测试。

我好像记错了，应该是`--reuse-port`。`--reuse-port`是$$的一个选项。 你用ps命令看一下$$的启动参数，如果有`--reuse-port`，就去掉。这个选项也可能在$$的配置文件里(一般叫xxxx.json)，如果有就注释掉。  貌似这个参数不是每个$$版本都有，如果没有就不用管他。你在$$-libev的github主页上搜`reuse-port`即可搜到。

你是在两台VPS用同样的安装脚本安装的，一台正常一台不正常，问题应该不是出在`reuse-port`这里。

**Comment by wangyu-** [comment]
之前其他人也反馈过GigsGigsCloud有问题：

>我也遇到这个问题了，我原先使用搬瓦工vps没有这个问题，换成GigsGigsCloud就出现这个问题，怀疑系统或者vps服务商的问题。。

相关issue： https://github.com/wangyu-/udp2raw-tunnel/issues/160

建议再试一下清空VPS的iptables，然后重新启动udp2raw和UDPspeeder：

https://github.com/wangyu-/tinyfecVPN/wiki/清空iptables的方法

如果问题依旧，可以尝试一下udp2raw的ICMP模式。

 如果还是不行，可能就没什么办法了。

**Comment by cyrilliao** [comment]
今晚尝试了根据教程清空VPS的iptables，再重启串联，然后尝试了分别尝试了UDP和ICMP两种模式，另外再尝试了xor的加密模式，所以最后应该是服务器的问题。我想尝试换一下GigsGigsCloud的Hong Kong Origin IP的服务器试一下，不知道这个是否您在上次回复所说的“独立IP”呢？

**Comment by wangyu-** [comment]
>我想尝试换一下GigsGigsCloud的Hong Kong Origin IP的服务器试一下，不知道这个是否您在上次回复所说的“独立IP”呢？

GigsGigsCloud的Hong Kong Origin IP我不了解，不过 `独立ip`就是字面意思。
