### ISSUE TITLE
udpspeeder+openvpn的问题

### ISSUE THREAD

**Issue by QiXianPu** [wangyu-/UDPspeeder#14]
用openvpn.会不会被屏蔽啊？虽然我用来游戏，但有文章说openvpn已经被识别了，被封就麻烦了，我换服务器的ip要花钱   (・｀ヘ´・;)ゞ

还有就是我现在准备用openvpn，免得装kcptun，但是装了openvpn就没有必要开启ss了吧？

**Comment by wangyu-** [comment]
>openvpn.会不会被屏蔽啊？虽然我用来游戏，但有文章说openvpn已经被识别了，被封就麻烦了，我换服务器的ip要花钱 (・｀ヘ´・;)ゞ

你在openvpn前面加了个tunnel以后，外界就看不到openvpn流量了，所以没有问题。

>还有就是我现在准备用openvpn，免得装kcptun，但是装了openvpn就没有必要开启ss了吧？

纯翻墙相关的问题，我还是不回答了吧，以免惹上麻烦。你自己Google一下吧。

**Comment by QiXianPu** [comment]
好，我自己找吧，但是那个tunnel指什么？是指Shadowsocks不？给发个相关资料链接吧😃

**Comment by wangyu-** [comment]
前面的tunnel指的就是udpspeeder，另外udp2raw/kcptun/sshtunnel这些都是tunnel。

**Comment by QiXianPu** [comment]
谢了
