### ISSUE TITLE
Q：Padavan固件 udp2raw+speederv2的NAT问题

### ISSUE THREAD

**Issue by 540369718** [wangyu-/UDPspeeder#142]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)

求大佬帮忙。

### 环境
Padavan固件、libev版本的魔法

### 代码
在server端运行代码：
```shell
/root/udp2raw/udp2raw_amd64 -s -l0.0.0.0:28901 -r127.0.0.1:28900 -a -k "密码" --raw-mode faketcp
/root/udpspeeder/speederv2_amd64 -s -l0.0.0.0:28900 -r127.0.0.1:魔法端口  -f2:4 -k "密码" --mode 0 -q1
```
在client端运行代码：
```shell
killall ss-redir
ss-redir -c /tmp/ss-redir_1.json &
ss-redir -s 127.0.0.1 -c /tmp/ss-redir_1.json -U &
killall speeder
/opt/bin/udp2raw -c -l0.0.0.0:28900  -r魔法地址:28901 -a -k "密码" --raw-mode faketcp
/opt/bin/speederv2 -c -l0.0.0.0:魔法端口 -r127.0.0.1:28900 -f2:4 -k "密码" —timeout 0
```

### LOG
路由器speederv2
![image](https://user-images.githubusercontent.com/8408547/41648122-a6f9790a-74aa-11e8-9669-a5d380722597.png)
路由器udp2raw
![image](https://user-images.githubusercontent.com/8408547/41648242-f1a8c4f6-74aa-11e8-82b3-a989af7779b3.png)
服务器udp2raw
![image](https://user-images.githubusercontent.com/8408547/41648191-cff913ce-74aa-11e8-85d9-fbd741b0f2d7.png)
服务器speederv2
![image](https://user-images.githubusercontent.com/8408547/41648226-e72df636-74aa-11e8-8afa-77aa46aae0ae.png)

### 问题
此时nattypetester显示UdpBlocked。
不使用udp2raw+speederv2时，nattypetester显示PortRestrictedCone，NAT3.

### 参考
[ISSUE31](https://github.com/wangyu-/UDPspeeder/issues/31)和[Padavan固件路由器简明教程](https://github.com/wangyu-/UDPspeeder/wiki/Padavan%E5%9B%BA%E4%BB%B6%E8%B7%AF%E7%94%B1%E5%99%A8%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B)

**Comment by ACG-MM** [comment]
![Capture](https://user-images.githubusercontent.com/63167197/86931901-3ef31180-c16b-11ea-91a2-f5dcb915a8b2.PNG)
我的运行怎么是这样。。完全连接不了。折腾半年了

**Comment by SicknUnDope** [comment]
我的运行怎么是这样。一直使用不了 折腾半年了
![capture (2)](https://user-images.githubusercontent.com/63167197/86932717-4ff05280-c16c-11ea-89a7-ac313b512c03.png)

**Comment by SicknUnDope** [comment]
开发人员全失踪了吗
