### ISSUE TITLE
centos 7 装完后命令行不能退出

### ISSUE THREAD

**Issue by hasayakey** [wangyu-/UDPspeeder#144]
SSH到VPS后按guide执行命令启动后不会自动结束命令。。。。只能强行关闭SSH，然后就失效了没启动

**Comment by hasayakey** [comment]
CPU model            : QEMU Virtual CPU version (cpu64-rhel6)
Number of cores      : 2
CPU frequency        : 2599.998 MHz
Total size of Disk   :  GB ( GB Used)
Total amount of Mem  : 1002 MB (117 MB Used)
Total amount of Swap : 259 MB (0 MB Used)
System uptime        : 0 days, 5 hour 52 min
Load average         : 0.04, 0.04, 0.01
OS                   : CentOS 7.5.1804
Arch                 : x86_64 (64 Bit)
Kernel               : 4.17.2-1.el7.elrepo.x86_64

**Comment by wangyu-** [comment]
https://github.com/wangyu-/UDPspeeder/wiki/FAQ
