### ISSUE TITLE
遗憾被墙 来求解决方案

### ISSUE THREAD

**Issue by lcpp1123** [wangyu-/UDPspeeder#145]
只单纯用来玩游戏的VPS。使用的方案是OPENVPN+UDPspeeder+UDP2raw 今天不幸被墙 中午还好好地，下午就G了。想问下，这种接连方式会暴露openvpn的信息吗？我暂时想尝试使用anyconnect+UDP双兄弟，请问有更好的推荐吗？只想用来玩游戏。

**Comment by lcpp1123** [comment]
抱歉 看到伟大的作者做了很多的更新。居然有了windows版本，非常兴奋。想问下我现在的命令是否依然有效且最新？
服务端
./udpspeeder/speederv2_amd64 -s -l0.0.0.0:4096 -r127.0.0.1:1194   -k "passwd" --mode 0 -f2:4 --timeout 0 

./udp2raw/udp2raw_amd64 -s -l0.0.0.0:4097 -r127.0.0.1:4096 -a -k "passwd" --raw-mode faketcp &

客户端
./udpspeeder/speederv2_amd64 -c -l0.0.0.0:4099 -r127.0.0.1:4098   -k "passwd" --mode 0 -f2:4 --timeout 0 

./udp2raw/udp2raw_amd64 -c -l0.0.0.0:4098 -rxx：xx：xx：xx:4097 -a -k "passwd" --raw-mode faketcp

**Comment by wangyu-** [comment]
这里不允许讨论翻墙问题，先关了。

**Comment by wangyu-** [comment]
>这种接连方式会暴露openvpn的信息吗？

UDPspeeder+UDP2raw不会暴露关于上层应用的信息。

>想问下我现在的命令是否依然有效且最新？

UDPspeeder windows版命令和linux版一样， udp2raw有一点区别，见：

https://github.com/wangyu-/udp2raw-multiplatform/wiki/快速入门

如果有其他问题，开新issue。
