### ISSUE TITLE
请问一下udpspeeder +openvpn + SS是都配置在一台VPS上面吗？

### ISSUE THREAD

**Issue by liyuhanaljlj** [wangyu-/UDPspeeder#15]
请问一下udpspeeder +openvpn + SS 是都配置在一台VPS上面吗？用来玩绝地

**Comment by wangyu-** [comment]
可以配置在同一台VPS上面。

玩游戏的话，只用udp speeder+vpn就可以，额外的那个$$主要是为了浏览器上网方便。当然，这个看你的习惯了，udpspeeder +openvpn + $$也没问题。

**Comment by liyuhanaljlj** [comment]
好的，谢谢

**Comment by liyuhanaljlj** [comment]
@wangyu- 好的，谢谢

**Comment by liyuhanaljlj** [comment]
[](url)
