### ISSUE TITLE
请教openvpn+udp2raw+speederv2加密问题

### ISSUE THREAD

**Issue by atrandys** [wangyu-/UDPspeeder#151]
大神好，我用openvpn+udp2raw+speederv2这种方案，做游戏代理。
看wiki说明udp2raw本身就有加密功能，我的openvpn是否可以设置为无加密传输。
谢谢。

**Comment by wangyu-** [comment]
>看wiki说明udp2raw本身就有加密功能，我的openvpn是否可以设置为无加密传输。

一般来说可以。

对于安全要求极高的环境，建议还是不要关掉openvpn的加密。openvpn在安全上投入的精力比udp2raw多得多，比如openvpn有前向安全性：

https://zh.wikipedia.org/wiki/前向安全性

**Comment by atrandys** [comment]
谢谢大神。
