### ISSUE TITLE
关于udp2raw连接的问题

### ISSUE THREAD

**Issue by GINmvp** [wangyu-/UDPspeeder#152]
首先感谢作者。
udpspeeder+udp2raw这一整套流程在家里的电脑和在公司的电脑都可以完美运行。但是在我在给我同学的电脑上搭udp2raw的时候出现的这个状况
![image](https://user-images.githubusercontent.com/40859392/42323512-0303ae5c-8093-11e8-8e85-1eac8b966f7c.png)
![image](https://user-images.githubusercontent.com/40859392/42323591-47fffbfa-8093-11e8-8c53-02cc88827ee1.png)
vps：阿里云，Ubuntu V16，1C1G  udpspeeder+udp2raw都是最新版本
同学电脑：win10 udpspeeder+udp2raw都是支持win版的最新版本

**Comment by wangyu-** [comment]
为什么没有`-a`？

**Comment by GINmvp** [comment]
emmmmmm因为加了-a之后报了个错：-a not supported in this version, check -g or --raw-mode easyfaketcp      0.0

**Comment by wangyu-** [comment]
VPS端为什么不加？

客户端用没用过`-g`?

**Comment by GINmvp** [comment]
没有过

**Comment by wangyu-** [comment]
https://github.com/wangyu-/udp2raw-multiplatform/wiki/快速入门
