### ISSUE TITLE
关于udpspeeder的原理和ps4竞技运动类游戏联机的疑惑

### ISSUE THREAD

**Issue by daodaodaren** [wangyu-/UDPspeeder#154]
wangyu大神您好，我现在使用一台cn2线路的同城电信云主机作为vps，我和主机之间延迟很低，没有丢包。现在遇到一个问题，我使用udp高倍发包到服务器，比如2:4,2:2，会和很多玩家连接失败，无法建立游戏，而使用100:2这样的超低发包参数，就能几乎连接所有玩家。我通过查看udpspeeder的设计机制原理，觉得有些疑惑。按说这个发包倍数只和我本地网络与vps服务器通信有关，和其他玩家的数据交互都是由vps代理完成的，为什么会出现多倍发包无法连接的情况呢？烦请讲解一下，谢谢。

**Comment by daodaodaren** [comment]
自己懂了，udpspeeder的nat有问题，不是全锥型的，所以只能和全锥型nat玩家或者nat1玩家联机。

**Comment by wangyu-** [comment]
>udpspeeder的nat有问题，不是全锥型的，所以只能和全锥型nat玩家或者nat1玩家联机。

UDPspeeder不影响NAT类型，是否full cone由代理软件决定。如果本来是full cone加上UDPspeeder后变成了非full cone，很可能是代理软件/路由器插件的问题。

**Comment by xueyichen** [comment]
> > udpspeeder的nat有问题，不是全锥型的，所以只能和全锥型nat玩家或者nat1玩家联机。
> 
> UDPspeeder不影响NAT类型，是否full cone由代理软件决定。如果本来是full cone加上UDPspeeder后变成了非full cone，很可能是代理软件/路由器插件的问题。

我也遇到类似问题，如果是代理软件问题／路由器插件问题，是哪些问题呢？

我的使用场景是
路由器上$$，玩游戏udp丢包，想解决于是udp2raw-tunnel + speeder串联，搞完之后视频，网页都没问题，能够正常。就是玩游戏的时候这个nat有问题。

于是按 #31 这里面方法设置，知识加了speeder，还是类似问题。
如果我把speeder去掉，正常ss的化，nat是full cone。 

大神能帮忙解释下原理吗？

如果需要详细信息，我再按照issue创建要求加上相信环境信息，和相关日志截图，麻烦了。

**Comment by wangyu-** [comment]
>我也遇到类似问题，如果是代理软件问题／路由器插件问题，是哪些问题呢？

$$版本/分支众多，我也不可能去搞清楚每个版本各有什么问题。

不过确实有很多类似的NAT问题，换了个SS版本就好了，或者关了某个$$的参数就好了。

比如：我记得有人反馈过，如果$$加了`--port-reuse`选项， 会出现跟你一样的问题。 关了就好了。

$$的UDP貌似一直不完美，即使你NAT测试是full cone，某些情况还是会出问题。比如$$-libev里面的《Xbox one 100% packet loss》这个issue，是个稳定复现的问题， 我也回复了issue给作者提供了追查思路（跟pmtu有关），然而作者貌似并没有时间/兴趣解决。

所以，我建议你：如果只是想凑合用一下让nat类型的显示变正常，换个$$版本试试（换个版本号不同的，或者换个其他语言实现的版本）或者关掉$$的某些参数试试。 如果想一劳永逸得解决，那就改用VPN方案。

**Comment by wangyu-** [comment]
你可能觉得单独用$$时没问题，UDPspeeder+$$就有问题，所以问题是UDPspeeder造成的。实际上不一定是这样的，实际上$$自己对UDP的支持就不完美/不稳定，单独用$$也会有时正常/有时有问题。
 
| \ | $$ | openvpn |
| ------ | ------ | ------ |
| 单独用 | 没问题(有时有问题) | 没问题 |
| 配合UDPspeeder | 有问题| 没问题 |

看了这个表，你觉得锅是谁的呢？ 我不敢保证锅是$$的，但是如果你想问题少一点，还是用openvpn吧。

**Comment by xueyichen** [comment]
> 你可能觉得单独用$$时没问题，UDPspeeder+$$就有问题，所以问题是UDPspeeder造成的。实际上不一定是这样的，实际上$$自己对UDP的支持就不完美/不稳定，单独用$$也会有时正常/有时有问题。
> 
> \	$$	openvpn
> 单独用	没问题(有时有问题)	没问题
> 配合UDPspeeder	有问题	没问题
> 看了这个表，你觉得锅是谁的呢？ 我不敢保证锅是$$的，但是如果你想问题少一点，还是用openvpn吧。

感谢及时解释。
今天一直在搭建openvpn套speeder，到目前还没成功，能帮忙看下吗

现象：路由器上面能够正常ping/dig/curl，但是连接路由器的某个机器没法ping以及访问网站
怀疑ip route配错了，能帮忙看下吗


0.0.0.0/1 via 172.31.100.1 dev tun0
default via 221.221.144.1 dev pppoe-wan
127.0.0.1 via 221.221.144.1 dev pppoe-wan
128.0.0.0/1 via 172.31.100.1 dev tun0
x.x.x.x via z.z.z.z dev pppoe-wan
172.31.100.0/24 dev tun0 scope link  src 172.31.100.2
192.168.1.0/24 dev br-lan scope link  src 192.168.1.1
z.z.z.z dev pppoe-wan scope link  src y.y.y.y

x.x.x.x 是我vps的ip， z.z.z.z为宽带的网关。 y.y.y.y是宽带分配的ip

172.31.100.1  是openvpn虚拟出来的网段。

链接机器分配的ip为192.168.1.x


我是学习https://github.com/wangyu-/UDPspeeder/wiki/UDPspeeder-openvpn-config-guide 这个链接搭建的。
整了一天了，脑袋都大了，求指导了

还需啥信息，我再提供，麻烦了。

**Comment by xueyichen** [comment]
实验了下openvpn的模式。
加了后tun模式后，nat识别成双nat，请问有无解决办法呢？
用tap方式，暂时还没成功～～！路由器上的流量发现不走openvpn，不知道你知道啥原因吗？
我是参照 [如何配置openvpn](https://oldwiki.archive.openwrt.org/doc/howto/vpn.openvpn#tab__server-bridge_tap_server) 
 这里面的两种模式配置的

然后用openvpn后，用iperf3测试了下udp，发现和没用传输是一样的
[  5] local 156.236.113.151 port 5201 connected to 221.221.152.81 port 57229
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec   120 KBytes   983 Kbits/sec  9.941 ms  0/15 (0%)
[  5]   1.00-2.00   sec   128 KBytes  1.05 Mbits/sec  11.509 ms  0/16 (0%)
[  5]   2.00-3.00   sec   128 KBytes  1.05 Mbits/sec  12.063 ms  0/16 (0%)
[  5]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  12.384 ms  0/16 (0%)
[  5]   4.00-5.00   sec   128 KBytes  1.05 Mbits/sec  12.507 ms  0/16 (0%)
[  5]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  12.459 ms  0/16 (0%)
[  5]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  16.711 ms  0/16 (0%)
[  5]   7.00-8.00   sec   128 KBytes  1.05 Mbits/sec  13.946 ms  0/16 (0%)
[  5]   8.00-9.00   sec   128 KBytes  1.05 Mbits/sec  12.945 ms  0/16 (0%)
[  5]   9.00-10.00  sec   128 KBytes  1.05 Mbits/sec  12.542 ms  0/16 (0%)
[  5]  10.00-10.04  sec  0.00 Bytes  0.00 bits/sec  12.542 ms  0/0 (0%)

用的游戏模式里面的配置，不知道是何原因呢？

**Comment by daodaodaren** [comment]
各位大神都来了，我是楼主，借本帖问一个我目前不能理解的问题……
我现在用pptp方式连接一个大陆的主机，路由器是华硕梅林固件，桥接型光猫，路由器pppoe拨号，运营商公网ip。目前的问题是，如果使用华硕路由器拨号后直接pptp vpn，ps4网络nat失败。必须要用另一台路由器拨号后，华硕路由器接在拨号路由器之下获得静态或者动态ip后连接pptp，ps4连接华硕路由器才会有nat2。我查了很久百度谷歌，百思不得骑姐，请各位大神顺手解救小弟……
