### ISSUE TITLE
"comp-lzo" is deprecated

### ISSUE THREAD

**Issue by ghost** [wangyu-/UDPspeeder#158]
在[教程](https://github.com/wangyu-/UDPspeeder/wiki/UDPspeeder-openvpn-config-guide)中，使用了`comp-lzo no`这个选项。
我在通过luci部署openwrt的时候，发现不起作用，观察conf文件才发现没有加上这一条。
然后做了一点调查，因为官方在2.4版本已经[丢弃了这个配置](https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#a--comp-lzo)，所以openwrt也就[不再加入了](https://bugs.openwrt.org/index.php?do=details&task_id=1478&status%5B0%5D=&pagenum=10&order=category&sort=asc)。
按照官方的解释，`--compress`后面不加参数就表示原参数，但是openwrt里也没有提供compress参数。
我本人可以手动修改脚本解决这个问题，提这个issue是希望作者能改进一下教程，让小白少走弯路。

**Comment by wangyu-** [comment]
感谢反馈。我在几个openvpn相关的文章里加上了注释：

```
comp-lzo no   #this option is deprecated since openvpn2.4. For 2.4 and above, use "compress" instead
#compress
```
