### ISSUE TITLE
延迟比裸连变高

### ISSUE THREAD

**Issue by atrandys** [wangyu-/UDPspeeder#159]
wangyu大神好，请教一下延迟变高问题：

**串联方式**

使用openvpn+udpspeeder+udp2raw的串联方式

**服务端参数设置**
> ./speederv2 -s -l0.0.0.0:9999 -r127.0.0.1:1194 -f2:4 --mode 0 --timeout 1
> ./udp2raw -s -l0.0.0.0:9898 -r 127.0.0.1:9999 --raw-mode faketcp -a -k passwd

**客户端参数设置**
> speederv2.exe -c -l0.0.0.0:2099 -r127.0.0.1:9999 -f2:4 --mode 0 --timeout 1 --report 10 
> udp2raw.exe -c -r23.106.143.182:9898 -l 127.0.0.1:9999 --raw-mode faketcp -k passwd

**延迟变高现象描述**

使用裸连时延迟147ms，如下图
[裸连](https://i.loli.net/2018/09/01/5b8a2af99fdfd.png)

使用openvpn连接后，延迟在156ms-173ms间波动
[vpn](https://i.loli.net/2018/09/01/5b8a2b56141ee.png)

按照参数说明，这个配置应该是没有增加额外延迟的，请您帮助分析下原因。

**Comment by wangyu-** [comment]
发一下udp2raw 和UDPspeeder的版本(看-h输出)

单独分别用udp2raw和UDPspeeder试一下，看延迟是谁产生的。

用udp2raw的UDP模式和ICMP模式分别连一下延迟有多少。

**Comment by yobabyshark** [comment]
刚只用udpspeeder连接测试，仍然存在比裸连延迟高的情况。
服务端和客户端都是使用的最新的release版本

**Comment by yobabyshark** [comment]
@wangyu- 我把openvpn中加上了mtu参数（之前没设置，刚看到一篇您文章提到过），现在延迟基本和裸连差不多，不知道是不是mtu的问题。

**Comment by atrandys** [comment]
#### 版本信息 ####
服务端
> UDPspeeder V2 git version: 1f946ab705    build date: Aug  5 2018 23:59:57
> udp2raw-tunnel git version: 2c67c319b7    build date:Feb 24 2018 18:07:42

客户端
> UDPspeeder V2 git version: 1f946ab705    build date: Aug  6 2018 13:00:17
>udp2raw-tunnel  git version: f7166bfde3    build date:Jul  1 2018 11:10:47

#### 单独使用udpspeeder ####
同样出现延迟变高，而且很奇怪的是：偶尔能有那么一次重新连接openvpn后延迟没变高，但断开重新连接后就变高了，多次尝试断开重连都是比裸连要高一些（裸连147ms   vpn连156-170ms来回跳，有几率变成147ms左右）

#### udp2raw 各种模式 ####
· 使用udp模式，和本题问题一样

**Comment by wangyu-** [comment]
>单独使用udpspeeder
同样出现延迟变高，而且很奇怪的是：偶尔能有那么一次重新连接openvpn后延迟没变高，但断开重新连接后就变高了，多次尝试断开重连都是比裸连要高一些（裸连147ms vpn连156-170ms来回跳，有几率变成147ms左右）

断开后重新连接延迟变高/变低是正常现象，运营商的路由会做负载均衡(应该是以连接为单位，具体技术不了解)，重新连接后会走不同的路由路径。 

比如我这边到vultr美国建立VPN连接，透过VPN去ping，ping值是260ms，断开后重连就可能变成220ms，有时候甚至可能290。 只要不重连，延迟就基本不变，重连后可能变很多。是网络本身的原因（负载均衡），跟程序没关系。

你单独使用Openvpn（不用udp2raw+UDPspeeder）应该也会观察到类似现象。

另外我再多说一句。延迟跟流量类型(tcp/udp/icmp)也有关系，比如我这边到vultr日本，用`udp2raw(icmp)+vpn`和`udp2raw(tcp)+vpn`对比，透过vpn去ping延迟就很不一样，icmp延迟经常低很多。也是网络本身的原因(不通流量的不同路由策略)，跟程序没关系。

你`不用VPN直接ping`是走icmp流量，`单独用VPN`或`用UDPspeeder+openvpn`后ping是走udp流量，`用udp2raw伪装faketcp`后是走tcp流量。

回答到此为止，以下是吐槽：

>udp2raw 各种模式
· 使用udp模式，和本题问题一样

没看懂。使用udp模式后延迟到底是变大了还是变小了？是指单独用udp2raw还是UDPspeeder+udp2raw“？能不能认真写？

>用udp2raw的UDP模式和ICMP模式分别连一下延迟有多少。

>使用udp模式

Icmp模式呢？

**Comment by atrandys** [comment]
谢谢，那个icmp没测试成功。
