### ISSUE TITLE
请问作者UDPspeeder + kcptun + ss的方案具体如何实现呢？

### ISSUE THREAD

**Issue by McLeeX** [wangyu-/UDPspeeder#16]
因为希望能够同时加速tcp和udp的流量，所以希望能够使用这个方案，希望作者能够指点一下如何实现，谢谢！

**Comment by wangyu-** [comment]
$$ server同时监听在一个tcp和一个udp端口，比如443。用udpspeeder把远程的udp 443映射到本地的的1234，用kcptun把远程的tcp 443映射到本地的1234。 然后在$$ client把端口填成1234，ip填成127.0.0.1，就可以了。

**Comment by McLeeX** [comment]
好的，解决了，谢谢您

**Comment by wjszh668** [comment]
我想问一下这个TCP和UDP分别映射是如何实现的?
/etc/kcptun/server_linux_amd64 -t "127.0.0.1:16003" -l ":16999" -mode fast2 -mtu 1300
/etc/speederv2/speederv2_amd64 -s -l0.0.0.0:16999 -r127.0.0.1:16003  -f20:10 -k "passwd"
S**的端口开在了16003.
我在服务端同时运行这2行代码,会出线端口冲突.
是用iptables?
能否给条具体代码说明一下

**Comment by wangyu-** [comment]
@wjszh668 

>/etc/kcptun/server_linux_amd64 -t "127.0.0.1:16003" -l ":16999" -mode fast2 -mtu 1300
/etc/speederv2/speederv2_amd64 -s -l0.0.0.0:16999 -r127.0.0.1:16003 -f20:10 -k "passwd"

你这里面的16999只是个中间端口，并不需要kcptun和udpspeeder的相同。这个两个16999都是udp，当然会冲突。

>$$ server同时监听在一个tcp和一个udp端口，比如443。用udpspeeder把远程的udp 443映射到本地的的1234，用kcptun把远程的tcp 443映射到本地的1234。 然后在$$ client把端口填成1234，ip填成127.0.0.1，就可以了。

这里面并没提到中间端口，中间端口随意选的。
