### ISSUE TITLE
闲谈

### ISSUE THREAD

**Issue by QiXianPu** [wangyu-/UDPspeeder#18]
大神玩Brawl Stars时用的哪个服务器加速的啊，是ban wangong吗？还有用的是openvpn还是其他的工具啊？: D

**Comment by wangyu-** [comment]
>玩Brawl Stars时用的哪个服务器加速的啊，是ban wangong吗？

Brawl Stars主要用的是搬瓦工洛杉矶机房。 vultr东京机房的备用。

>还有用的是openvpn还是其他的工具啊？: D

用的是udp2raw+udpspeeder+openvpn

**Comment by QiXianPu** [comment]
;-D
