### ISSUE TITLE
ssr+kcptun+udpspeeder+udp2raw如何调优

### ISSUE THREAD

**Issue by keeno1982** [wangyu-/UDPspeeder#20]
个人用的是比较渣的线路，平时看看油管，之前试了另一个项目用ssr+kcptun+udp2raw效果还行，比原来不套udp2raw要好些，看来抗QOS是有效果的。后面想说udpspeeder还能加速就试了一下，在kcptun和udp2raw中间串了udpspeeder，但是效果却不好，貌似有拖后腿嫌疑。又试了一个办法，把kcptun拿掉了，用udpspeeder直接加速ssr，不过效果也不行，跟有没有串kcptun差别不大。是我打开的方式不对？如果是ssr+kcptun+udpspeeder+udp2raw串联顺序应该是怎样才合理？udpspeeder的参数怎么设才是合理的？

**Comment by wangyu-** [comment]
UDPspeeder不是为了看youtube这种大流量场景而设计的。引用下主页里的**适用场景**：
>适用场景：绝大部分流量不高的情况。程序本身加速udp，但是配合openvpn可以加速任何流量。网络状况不好时，游戏卡得没法玩，或者网页卡得没法打开，使用起来效果最好。对于解决语音通话的断断续续效果也不错。不适合大流量的场景，比如BT下载和在线看视频。 无论从自己使用效果的角度，还是从国际出口带宽占用的角度，都建议不要在大流量环境使用。

UDPspeeder用来加速tcp，主要是通过多倍发包来避免重传，从而改善游戏的延迟。用来加速youtube，只有在网络本身特别差的情况下才会有明显效果，否则只能浪费流量。如果你坚持要用来加速Youtube，可以尝试一下`-d1`。

**Comment by keeno1982** [comment]
@wangyu- 
./speeder_amd64 -l 0.0.0.0:7777 -r 127.0.0.1:111 -s -d1 -k "password"
参数这样可以吗？是要写成-d1还是-d 1呢，111是kcp端口，7777给udp2raw用。还有其它黑科技的参数吗？

**Comment by wangyu-** [comment]
>参数这样可以吗？是要写成-d1还是-d 1呢

都是可以的，效果一样。
