### ISSUE TITLE
能够支持点到多点吗

### ISSUE THREAD

**Issue by hothotstreet** [wangyu-/UDPspeeder#202]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)
我将udpspeeder和openvpn结合起来使用，在openvpn的server端开启udpspeeder的server，然后在openvpn的client端开启udpspeeder的client，发现运行其来后，我两个openvpn客户端和服务端通信的话只能通一个，要不是这个client通，要么是另外一个client通
openvpn client 配置
  client
  dev tap_test
  proto udp
  fast-io
  remote 127.0.0.1 3333
  nobind
  persist-key
  persist-tun
  verb 3
  log /root/openvpn.log
  ca /etc/openvpn/test/ca.crt
  cert /etc/openvpn/test/client.crt
  key /etc/openvpn/test/client.key

openvpn server配置
local 0.0.0.0
port 7777
proto udp
dev tap_test
ca /etc/openvpn/easy-rsa/keys/ca.crt
cert /etc/openvpn/easy-rsa/keys/server.crt
key /etc/openvpn/easy-rsa/keys/server.key        # This file should be kept secret
dh /etc/openvpn/easy-rsa/keys/dh2048.pem
ifconfig-pool-persist ipp.txt
server-bridge 10.1.0.4 255.255.255.0 10.1.0.50 10.1.0.100
#push "route 172.19.1.0 255.255.255.0"
client-config-dir ccd
keepalive 10 120
client-to-client
;max-clients 100
persist-tun
persist-key
status /etc/openvpn/easy-rsa/keys/openvpn-status.log
;log-append  openvpn.log
verb 3

udpspeeder配置：
./speederv2_x86 -s -l0.0.0.0:4096 -r127.0.0.1:7777  -f20:10 -k "passwd" --mode 0
./speederv2_x86 -c -l0.0.0.0:3333 -r192.168.1.52:4096 -f20:10 -k "passwd" --mode 0

**Comment by k79e** [comment]
客户端是win版的么? 最新客户端有bug的.
老版本我也不知道.

vpn没必要用client-to-client 你有什么特殊需求么.
连接之后vpn里面的ip都可以互相连接的.

多个客户端用同一个证书必须服务端开启duplicate-cn
否则ip冲突肯定只能连1个

更新
前一个老版本我也测了 根本连不上....

**Comment by hothotstreet** [comment]
后面测试发现可以支持一个server被多个client连接，但是是和openvpn结合使用。
