### ISSUE TITLE
能否同时监听ipv4和ipv6

### ISSUE THREAD

**Issue by rullineter** [wangyu-/UDPspeeder#204]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)

参考wiki ipv6 and domain的说明，配置了ipv6的监听，只监听了ipv6端口。
是需要另起一个实例监听ipv4？还是只需要配置监听ipv6就可以同时监听ipv4？

**Comment by wangyu-** [comment]
UDPspeeder本身没有同时监听在ipv4和ipv6的功能。但是在(不太旧的)linux上，如果UDPspeeder监听在[::]上，来自0.0.0.0的ipv4连接也能自动被支持(操作系统层面的自动支持)。

**Comment by rullineter** [comment]
> 
> 
> UDPspeeder本身没有同时监听在ipv4和ipv6的功能。但是在(不太旧的)linux上，如果UDPspeeder监听在[::]上，来自0.0.0.0的ipv4连接也能自动被支持(操作系统层面的自动支持)。

谢谢解答，我自己尝试开启两个实例同时监听ipv4和ipv6，目前是后开启的实例无法正常监听——错误信息是，端口已被监听。
所以，我想确实是如你所说。
