### ISSUE TITLE
确实不知道怎么让openvpn通过虚拟机中的speeder连接上

### ISSUE THREAD

**Issue by liyuhanaljlj** [wangyu-/UDPspeeder#21]
#服务端已经架设speeder+openvpn+ssr，所有服务以及自启都设置好了。
客服端已经设置好虚拟机speeder自启了,ssr和openvpn也准备就绪。现在唯一就是不知道怎么设置openvpn连接虚拟机中的speeder。
是否是打openvpn-Settings-Proxy-Manual Configguration中选择HTTP Proxy或者SOCKS Proxy 然后设置虚拟机ip桥接地址？还有就是地址是那一个（下面是配图）？如果不是这样设置请问怎么设置，已经搞了几个通宵了。请帮助一下，谢谢。在线等
![qq 20171014064615](https://user-images.githubusercontent.com/32599001/31569232-e8d38ec4-b0ab-11e7-961d-853102b93549.png)
![qq 20171014064949](https://user-images.githubusercontent.com/32599001/31569230-e7ef685c-b0ab-11e7-9a9c-cf5fae0b8d59.png)
![qq 20171014065807](https://user-images.githubusercontent.com/32599001/31569368-1059d97a-b0ad-11e7-9bef-a8fa92367127.png)
![qq 20171014064743](https://user-images.githubusercontent.com/32599001/31569233-e90edccc-b0ab-11e7-8d9d-72937d4e748a.png)

**Comment by wangyu-** [comment]
>是否是打openvpn-Settings-Proxy-Manual Configguration中选择HTTP Proxy或者SOCKS Proxy 然后设置虚拟机ip桥接地址？还有就是地址是那一个（下面是配图）？如果不是这样设置请问怎么设置，已经搞了几个通宵了。请帮助一下，谢谢。在线等

不是这样设置。在openvpn client里，把server ip填成192.168.123.51:3333就可以了。

用了udpspeeder以后,相当于把远程的openvpn的udp端口映射到本地了，你直接连这个本地的端口就相当于连接到了远程的openvpn。
