### ISSUE TITLE
OpenVPN和$$-libev的选择

### ISSUE THREAD

**Issue by QiXianPu** [wangyu-/UDPspeeder#22]
你好， @wangyu- 

我最近一直是使用$$-libev来代理游戏的（绝地PUBG），但是我不知道OpenVPN用来代理游戏是不是更加适合，更加好！

我知道你用的OpenVPN来加速的游戏，但要配置OpenVPN可比安装使用$$繁琐，就来问你一下。

多谢。

**Comment by wangyu-** [comment]
>但是我不知道OpenVPN用来代理游戏是不是更加适合，更加好！

$$+udpspeeder只能加速udp,如果要加速tcp还得配kcptun，不能加速icmp（不过游戏貌似不会用到icmp）。openvpn+udpspeer配置简单些，能同时加速tcp/udp/icmp。

**Comment by QiXianPu** [comment]
谢谢, @wangyu- 

如果游戏只用的是udp，那么是不是使用openvpn和使用$$-libev都一样，随便用一个？

**Comment by wangyu-** [comment]
>如果游戏只用的是udp，那么是不是使用openvpn和使用$$-libev都一样，随便用一个？

如果确实只用udp，那么效果应该没有差别。

**Comment by QiXianPu** [comment]
（○゜ε＾○）

**Comment by QiXianPu** [comment]
最后一个问题：

我测试到VPS服务器的udp数据没有丢包的话（或者丢包2~3%），那么有没有必要使用udpspeeder？（就是想知道在直接连接时不丢包的情况下，使用udpspeeder会不会增加网络延迟，就是游戏里显示的ping:XX ms）

**Comment by wangyu-** [comment]
>就是想知道在直接连接时不丢包的情况下，使用udpspeeder会不会增加网络延迟，就是游戏里显示的ping:XX 

对于游戏这种流量很小的场景，除非环境特殊，用udpspeeder只会变好，不会变坏。

>我测试到VPS服务器的udp数据没有丢包的话（或者丢包2~3%），那么有没有必要使用udpspeeder

如果确实是全天都0丢包，那就没有使用必要了。另外，丢包2~3%不算低，如果是tcp，丢包1%已经很卡了。
