### ISSUE TITLE
使用微林做中转加速时，提示这个错误，是微林把这种数据包，过滤了吗？

### ISSUE THREAD

**Issue by colakang** [wangyu-/UDPspeeder#23]
./speeder_arm -l 192.168.1.1:3333 -r hk3.vxtrans.link:33735 -c  -d2 -k "passwd"

udp fd connect fail -1 Permission denied

如果直连vps，是正常，没有问题的。

**Comment by nxtreaming** [comment]
微林数据不加密，即使它不过滤数据，GFW也会过滤。

**Comment by colakang** [comment]
上层我是走ssr，TCP走kcpturn，udp走udpspeed

udpspeed的这些udp包，应该也是有加密和混淆

kcpturn的udp包，可以被微林加速转发的，就是udpspeed的udp包被block

或者用另外一个场景，上层走openvpn的udp，udpspeed中转，通过微林再加速，应该是可以达到一个更好的游戏加速效果；
可惜微林不知为何现block了，不知道作者，是否有打算调试一下

**Comment by wangyu-** [comment]
地址不能用域名，换成ip

**Comment by colakang** [comment]
好，我试试

**Comment by colakang** [comment]
改用IP后，可以了
