### ISSUE TITLE
bash运行时一直提示permission denied

### ISSUE THREAD

**Issue by reimurin** [wangyu-/UDPspeeder#239]
不知道为什么
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)

**Comment by YihaoPeng** [comment]
```sh
# 添加执行权限：
chmod +x ./speederv2_amd64

# 现在应该可以运行了
./speederv2_amd64
```

**Comment by reimurin** [comment]
可以运行了，谢谢。
