### ISSUE TITLE
shell脚本和倍数问题

### ISSUE THREAD

**Issue by QiXianPu** [wangyu-/UDPspeeder#24]
你好， @wangyu- 

我利用vnstat监测openwrt网卡eth1的流量总量，然后编写了一个脚本来判断流量大于1GiB时就执行一个命令（比如删除一个文件），我有两个问题啊：

   1. 我运行此shell后出现错误提示如下：
```
         line 5: bc: command not found
         line 5: [: -eq: unary operator expected
         line 5: echo: write error: Broken
```

   2. 设置-d2后，流量是没有使用udpspeeder时的三倍，这个倍数肯定会反应在服务器流量消耗上，但是会反应在openwrt的网卡上吗（openwrt上网卡显示的流量会不会也是三倍）？

这是shell：
```
#!/bin/bash
ax=`vnstat --oneline | awk -F ";" '{print $11}'`
if [[ "$ax" == *GiB* ]];
then
        if [ $(echo "$(echo "$ax" | sed 's/ GiB//g') > 10"|bc) -eq 1 ]
        then
                rm -rf /etc/qita.conf
        fi
fi
```
这是vnstat --oneline的输出结果：
```
1;eth1;10/15/17;5.26 MiB;487 KiB;5.74 MiB;11.52 kbit/s;Oct '17;1.04 GiB;51.64 MiB;1.09 GiB;7.55 kbit/s;1.04 GiB;51.64 MiB;1.09 GiB
```

**Comment by wangyu-** [comment]
> 设置-d2后，流量是没有使用udpspeeder时的三倍，这个倍数肯定会反应在服务器流量消耗上，但是会反应在openwrt的网卡上吗（openwrt上网卡显示的流量会不会也是三倍）

会。其他问题你自己debug一下。`line 5: bc: command not found`这这个错误不是报得很清楚吗，没有bc这个命令。

最近你已经开了6个ISSUE了，你控制一下发新issue的数量，相关问题发到一个ISSUE里，不要为了个小问题就开新ISSUE。

**Comment by QiXianPu** [comment]
知道啦，谢谢提醒啊。 @wangyu-
