### ISSUE TITLE
UDPspeeder + VPN 单线下载速度还是比不过 SOCKS 代理

### ISSUE THREAD

**Issue by sdysj** [wangyu-/UDPspeeder#25]
添加 FEC 反而比 v1 影响最大速度，为了稳定性值得吗？v1双发包对除非是极烂线路来说延迟稳定性已经没问题。

UDPSPEEDER + VPN 单线下载速度是不是硬伤？我的测试顶多 200K，而用 kcp 就可以 3M/s，而 kcp 无法代理 UDP 啊。

V1 看 youtube 可以 5M/s，而 FEC 版就降到 kcp 一样速度，都有得失啊。

**Comment by wangyu-** [comment]
你自己编译了一个fec版吗？fec版的binary我还没发布呢。

可能是参数没调好。我这边在一个有10%的双向丢包的网络上，用fec版的默认参数可以3.5MB/s。如果丢包更大，需要把fec的参数调高。

v1版`-d1`是双倍发包，fec版默认是1.5倍发包。1.5倍的fec比直接2倍发包差，是有可能的。

你先等我把文档完善一下再尝试FEC版的吧。

**Comment by wangyu-** [comment]
>添加 FEC 反而比 v1 影响最大速度

在使用相同的流量的情况下，fec版不论是最大速度，还是单线程的速度，都是应该比v1版好的。延迟会比v1版大几毫秒。

**Comment by sdysj** [comment]
是的，我编译后测试了一下，添加 FEC 后看 youtube 速度和 kcp 一样了，而 v1 是可以达到最大带宽一半的。你加速VPN单线下载能有3.5M？那应该是你线路好。

**Comment by wangyu-** [comment]
>那应该是你线路好。

我这边可是在本来线路丢包基础上，额外加了10%丢包的。

**Comment by sdysj** [comment]
没什么，就是想说客户端到服务端单线速度100K以下的情景下，kcp 单线下载比 udpspeeder+VPN 效果好，不知道能不能解决这个问题，如果可以就完美了。

我测试的到就是 UDPspeeder 添加 FEC 以后对加速 VPN 来说单线下载和 V1 并没什么改善，而 kcp 单线下载就可以达到加速效果。

**Comment by wangyu-** [comment]
>没什么，就是想说客户端到服务端单线速度100K以下的情景下，kcp 单线下载比 udpspeeder+VPN 效果好，不知道能不能解决这个问题，如果可以就完美了

>我测试的到就是 UDPspeeder 添加 FEC 以后对加速 VPN 来说单线下载和 V1 并没什么改善，而 kcp 单线下载就可以达到加速效果。

V2版可以试一下 -f 20:20 ，如果不行再试下-f 20:30

**Comment by wangyu-** [comment]
最进改动比较频繁，用最新的code编译一下试试。

**Comment by sdysj** [comment]
我运行在四核ARM开发板上，刷 youtube 时确实 CPU100% 了，明天试试PC。
有测试了一下 20:20 20:30 还是一般，单线还是300K左右，刷 youtube 最大 2M/s 和 kcp 差不多。

**Comment by wangyu-** [comment]
>我运行在四核ARM开发板上，刷 youtube 时确实 CPU100% 了，明天试试PC。

CPU 100%就无法更快了。问题应该就在这里。

我用的树莓派3b,也是arm 4核，速度1.2mb/s的时候，cpu占用只有30~40%。你300k/s就100%了，不正常。

我估计你编译的时候没加-O3选项，为了debug方便，我把make file里默认的O3选项去掉了。刚才我提交了个commit，把默认的-O3选项加回来了，你pull一下最新的源码，重新编译一下估计就好了。

**Comment by sdysj** [comment]
不是，我说是加速VPN的话纯粹单线HTTP下载只有300K，而刷 youtube 可以 2M/s CPU100%。 而 kcp 单线HTTP下载可以2M/s。

**Comment by wangyu-** [comment]
默认的是-f20:10，换成20:20和20:30之后还是300k左右，没变大也没变小吗？我觉得有点奇怪，感觉像是没生效一样。慢可以理解，不过调了-f参数之后效果没变化，不太正常。

**Comment by wangyu-** [comment]
用openvpn直接连上去（不用udpspeeder）,ping起来丢包有多少呢？

**Comment by wangyu-** [comment]
另外再问一个问题，如果用v1版测单线程下载，-d1 -d2 -d3 -d4 -d5 都是只有300k吗？

**Comment by sdysj** [comment]
vultr jp 现在非常时期丢包 50%。
v1 也是这样的。

**Comment by wangyu-** [comment]
如果丢包真有50%这么高，那-f20:30也是不够的，可以试一下-f5:30。client和server都加上这个参数。

我觉得实际应该不会有这么高，如果真有50%那v2默认的参数应该卡得一点速度也没有了。

**Comment by wangyu-** [comment]
我查了一下，貌似youtube本身也是单线程缓冲的。所以你看youtube 2mb/s时候，应该也是单线程的速度。

**Comment by sdysj** [comment]
youtube 是通过 QUIC 的，没拥塞控制所以容易满速，而单线 HTTP 下载通过 kcp 可以实现提速但 UDPspeed + VPN 不能，我觉得是 SOCKS 代理和 VPN 原理硬伤啊不了解技术细节，如果你能 udpspeed + vpn 单线 3.5M 我觉得你直接 ss 无需加速都可以了。

**Comment by wangyu-** [comment]
>而单线 HTTP 下载通过 kcp 可以实现提速但 UDPspeed + VPN 不能，我觉得是 SOCKS 代理和 VPN 原理硬伤啊不了解技术细节

原理上是没问题的，不清楚实际上在你那边出了什么问题。

>如果你能 udpspeed + vpn 单线 3.5M 我觉得你直接 ss 无需加速都可以了

不加速的话，单线程只有几十k的速度。对比图：

![scp_compare](https://user-images.githubusercontent.com/4922024/31803071-97dd050e-b506-11e7-82bb-d51e96604d43.PNG)

（这个网络延迟100多ms，ping的丢包率19%）

**Comment by wangyu-** [comment]
>youtube 是通过 QUIC 的，没拥塞控制所以容易满速

如果用不支持quic的浏览器看，速度有多少？我想确认下是不是QUIC造成的差距。

也许是BBR造成的差距，youtube服务器上部署了BBR。用 udpspeed + vpn时也会受惠于BBR。

**Comment by wangyu-** [comment]
如果你能提供环境的话，我可以测试一下是什么原因。wangyucn@gmail.com

**Comment by sdysj** [comment]
难道是VPN程序问题？我是 udpspeeder + shadowvpn，我测试下 OpenVPN。

**Comment by sdysj** [comment]
哈哈，果真是 VPN 程序问题，换了 OPENVPN 速度就正常了。

**Comment by sdysj** [comment]
不是，又测试一回，还是不正常。应该不是程序问题了。

**Comment by sdysj** [comment]
@wangyu-  你是 udpspeeder + openvpn + ss 吗？如果是的话那当然能满速，我现在暂时用 tun2socks + kcpraw 解决了。

**Comment by wangyu-** [comment]
@wangyu- 你是 udpspeeder + openvpn + ss吗？如果是的话那当然能满速

不是，我用的就是udp2raw+udpspeeder+openvpn，然后直接scp测试的。 s***我平时上网会用，但是做测试的时候没有s***。

**Comment by ldaochen** [comment]
请问下tun2socks怎么配置路由？？

**Comment by sdysj** [comment]
最终还是 udpspeeder_v1 + udp2raw + shadowvpn + shadowsocks ss-redir (通过shadowvpn) 解决问题，纯粹 udpspeeder + vpn 单线下载速度真不能跑满。估计应该有人有同样问题。

**Comment by wangyu-** [comment]
>最终还是 udpspeeder_v1 + udp2raw + shadowvpn + shadowsocks ss-redir (通过shadowvpn) 解决问题，纯粹 udpspeeder + vpn 单线下载速度真不能跑满。估计应该有人有同样问题。

我看你之前问过udp2raw+udpspeeder的问题，我以为你发这贴的时候已经套上udp2raw了。不套udp2raw可能会被限制udp速度，跑不满是有可能的。

**Comment by sdysj** [comment]
说错，不是不能跑满，是根本就是没加速效果，单线HTTP 200K 左右，不套上 udp2raw 用 ss-redir 单线也可以跑满。。。
