### ISSUE TITLE
Not Running In Background

### ISSUE THREAD

**Issue by asterdeve** [wangyu-/UDPspeeder#255]
Dear, Sir, I have tried a lot to make it run in background but I couldn't I have read the all article help page everything but didn't understand how to make it run in background, 

when I run this 
./udp2raw_amd64 -s -l0.0.0.0:4096  -r127.0.0.1:7777   -k "passwd" --raw-mode faketcp  

its started the UDP2RAW & function as well but when I need to exit from the system if I press CTRL+C or CTRL+Z or I closed the SSH connection its lost the connection.

So I want to know how can I run udp2tun with start/stop/restart command or like openvpn

./udp2raw_amd64 --conf-file /etc/udp2raw/server.conf --daemon

please if anyone know about it, let me know as well, thanks...

**Comment by wangyu-** [comment]
duplicated with:
https://github.com/wangyu-/udp2raw-tunnel/issues/338
