### ISSUE TITLE
能不能简单 udp 192.168.1.1:1080 转发到 192.168.1.2:1080啊？

### ISSUE THREAD

**Issue by t66y100** [wangyu-/UDPspeeder#256]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)

**Comment by t66y100** [comment]
不需要其他功能，可不可以简单实现啊。
gost socat都会爆内存 udpfwd有点慢啊

**Comment by wangyu-** [comment]
https://github.com/wangyu-/tinyPortMapper

**Comment by t66y100** [comment]
谢谢
