### ISSUE TITLE
加速方案的选择

### ISSUE THREAD

**Issue by leepoi** [wangyu-/UDPspeeder#26]
首先感谢作者给我们提供了一个新的加速选择。然后，想请教一下开发者。

我的理解是，kcptun用于处理tcp数据，并转为udp，因此对原生的udp数据无效。

udpspeeder则是用于加速、处理udp数据的，因此对原生的tcp数据无效。

这里我有个疑问，主要是关于udpspeeder和kcptun的用途的。

我想加速香港的vps，用来玩游戏，低延迟是最重要的，通过额外的加速方案，进一步降低延迟，防止丢包，加强网络波动的抗性。

比如我用openvpn作为第一层，用来提供游戏加速的隧道

那么问题是，在低延迟应用中，udpspeeder能完全或者部分替代kcptun吗？

比如，有如下3种加速方案：

1、openvpn(tcp模式)+kcptun+udp2raw

2、openvpn(udp模式)+udpspeeder+udp2raw

3、openvpn(tcp模式)+kcptun+udpspeeder+udp2raw

第一种方案因为最底层还是tcp，即使转为udp，我感觉还是无法避免底层发起的3次握手等多余的请求（不确定）。

第二种感觉是最符合逻辑的，没有udp2tcp、或者tcp2udp的转换，但udpspeeder目前没有fec和快速重传这些kcptun上已经实现的功能，感觉还是有所欠缺，但不知道这些功能对游戏意义有多大。

第三种，感觉有多此一举的感觉（不确定）。

所以想请教一下开发者，我该作何选择呢？kcptun和udpspeeder对游戏的加速效果区别大吗？如果能加入fec、快速重传，udpspeeder是否就可以完全替代kcptun了呢？

**Comment by wangyu-** [comment]
>我的理解是，kcptun用于处理tcp数据，并转为udp，因此对原生的udp数据无效。

>udpspeeder则是用于加速、处理udp数据的，因此对原生的tcp数据无效。

这个理解是对的。

> 1、openvpn(tcp模式)+kcptun+udp2raw

这种方案不行。效果可能会更差。对tcp会有tcp over tcp问题，会有双倍重传。对udp，也会有udp over tcp的问题，会破坏udp的实时性。

openvpn的tcp模式，不推荐使用，openvpn的开发者们也不推荐用。这个模式只是为了在udp被屏蔽的情况下"凑合用一下"而开发的，有严重的性能问题。

>第一种方案因为最底层还是tcp，即使转为udp，我感觉还是无法避免底层发起的3次握手等多余的请求（不确定）。

不只是多余的请求的问题。从原理上有性能问题。

>3、openvpn(tcp模式)+kcptun+udpspeeder+udp2raw

>第三种，感觉有多此一举的感觉（不确定）。

这个确实有点多此一举了。而且有和1一样的问题。

> 2、openvpn(udp模式)+udpspeeder+udp2raw

对玩游戏来说这是最合理的方案。

如果要看视频，可以考虑用ss+kcptun+udpspeeder(+udp2raw),tcp走kcptun， udp走udpspeeder。这样更省流量。对玩游戏来说openvpn(udp模式)+udpspeeder+udp2raw就足够了。

>所以想请教一下开发者，我该作何选择呢？kcptun和udpspeeder对游戏的加速效果区别大吗？

kcptun主要是通过优化重传、拥塞控制来提速；udpspeeder通过发冗余数据避免丢包。udpspeeder的降延迟效果更好，缺点是更费流量。对于游戏来说，流量本身不大，延迟很重要，udpspeeder预计效果会更好。对于看视频kcptun预计效果更好。

>但udpspeeder目前没有fec和快速重传这些kcptun上已经实现的功能，感觉还是有所欠缺
>如果能加入fec、快速重传，udpspeeder是否就可以完全替代kcptun了呢？

fec在最新的版本里已经有了。应该不能完全替代kcptun，不过在大流量的场景下，效果会更接近kcptun。

udpspeeder不工作在tcp层面，所以不会涉及快速重传的问题，重传是上层协议的工作（比如tcp,kcp）。udpspeeder加速游戏在绝大多数情况下可以直接避免上层重传，所以上层重传策略的好坏就不是那么重要了。

**Comment by leepoi** [comment]
非常感谢！！！这样我就懂了，这个问题困扰了我好久！因为看到别的加速器，比如网易UU，人家加速效果很好，我自己用ss+kcptun就没那种效果，但服务器已经是香港阿里云了，所以很纠结，这次我要试试看openvpn+udpspeeder+udp2raw方案。    再次表示感谢！！！！

**Comment by wangyu-** [comment]
>比如网易UU，人家加速效果很好，我自己用ss+kcptun就没那种效果

这种东西，人家一般是买了到国外的专线的。你自己加速效果比不上它是正常的。

用openvpn(udp模式)+udpspeeder+udp2raw，如果链路质量不是特别差，预计也能达到类似的效果。

**Comment by leepoi** [comment]
最后一个小担心，openvpn因心跳包等原因，早已被GFW识别。我在openvpn的基础上，套上udp2raw，能消除openvpn的特征吗？我看到别的类型的vpn，比如ipsec，好像工作在ip层，貌似没法用udpspeeder

**Comment by wangyu-** [comment]
>最后一个小担心，openvpn因心跳包等原因，早已被GFW识别。我在openvpn的基础上，套上udp2raw，能消除openvpn的特征吗？

你自己尝试下吧。抱歉纯翻墙相关的问题我不能回答。

**Comment by leepoi** [comment]
OK，谢谢

**Comment by leepoi** [comment]
作者好。

我在部署的时候，有个小问题：FEC可以配合多倍发包吗？因为FEC的效率比单纯多倍发包高很多，比如  FEC+2倍发包的效果是否能媲美单纯的3倍、4倍发包呢？

你的文档里以及kcptun那里都提到过，FEC会增加延迟，想问一下，延迟会高很多吗？

比如90个包后面跟着10个纠正数据包，是不是意味着，要完整接收/处理完这全部的100个包，才会交给高层的程序使用呢？所以延迟就是完整接收100个包的所需时间？

**Comment by wangyu-** [comment]
>我在部署的时候，有个小问题：FEC可以配合多倍发包吗？因为FEC的效率比单纯多倍发包高很多

可以，2个UDPspeeder串联起来就能实现。

>比如 FEC+2倍发包的效果是否能媲美单纯的3倍、4倍发包呢？

我这里也没有测试数据，以实际效果为准。

>比如90个包后面跟着10个纠正数据包，是不是意味着，要完整接收/处理完这全部的100个包，才会交给高层的程序使用呢？所以延迟就是完整接收100个包的所需时间？

对于UDPspeeder的 mode 1模式，90个包里面没有丢失的包不产生额外延迟，对于需要重建的包才需要`要完整接收/处理完这全部的100个包，才会交给高层的程序使用`，准确来说是收到100个包的任意90个并且处理完，才能把重建的包提交给上层。Kcptun的行为也类似。

对于UDPspeeder的 mode 0模式，所有的包都需要重建，需要收到100个包的任意90个，并且处理完，才能提交给上层。

**Comment by leepoi** [comment]
谢谢！！！

**Comment by leepoi** [comment]
到目前为止，openvpn已经连接，但是默认数据并没有走vpn，可能路由还有问题，我还得配置一下。

说一下我在Windows下面遇到的几个小问题，

首先win客户端的openvpn配置文件里，txqueuelen 4000选项不能用，提示不支持Windows系统，屏蔽即可。

然后，客户端配置文件里remote 127.0.0.1 3333无法连接，提示connection reset by peer openvpn，
通过将地址改为 remote 192.168.50.105 3333解决，192.168.50.105是我的virtualbox跑lede的虚机ip。

**Comment by wangluyichen** [comment]
@leepoi 目前你的加速效果怎么样？openvpn+udpspeeder2+udpraw2

**Comment by Bepartofyou** [comment]
请教您一个问题，如果不用openvpn(udp模式)+udpspeeder+udp2raw， 只是openvpn(udp模式) + udp裸包是否也有tcp加速效果？tcp over udp是否有加速功能，对于其中协议影响不太理解。比如网络不好的时候，是否tcp over udp比tcp直连效果要好呢？有点小白，还望见谅

**Comment by wangyu-** [comment]
> 只是openvpn(udp模式) + udp裸包是否也有tcp加速效果？

没有加速效果。如果运营商有udp qos策略，反而可能有减速效果。

**Comment by Bepartofyou** [comment]
@wangyu- 哦，多谢

**Comment by leepoi** [comment]
@wangluyichen 我现在被转发规则弄得头大，好用的时候玩战地1很爽，不好用的时候，都上不了网。。。梅林插件也用了，那个感觉还不如vpn呢。

**Comment by wangluyichen** [comment]
@leepoi vpn玩游戏效果比 其他方式好，最好用tinyvpn的不多发包模式，如果网速可以的话，就是默认不掉包的情况

**Comment by leepoi** [comment]
我编译了一个给树莓派用，发现不能转发我的pc流量，真心的，看着转发规则就郁闷。你说比其它方式好？比openvpn+udpspeeder要好吗？按道理说，这个是个集成的，效果应该差不多吧

**Comment by Mattosx** [comment]
问下 kcptun 是否可以设置发包策略, 模拟udpspeeder这样的多倍发包, 我感觉kcp和udpspeeder 有一定功能的重叠.

**Comment by wangyu-** [comment]
>问下 kcptun 是否可以设置发包策略, 模拟udpspeeder这样的多倍发包, 我感觉kcp和udpspeeder 有一定功能的重叠.

一个是加速tcp的，一个是加速UDP/全流量的，不知道哪里重叠了。唯一的相似之处就是都用到了FEC。
