### ISSUE TITLE
Iptables connmark does not work with udpspeeder

### ISSUE THREAD

**Issue by congzhangzh** [wangyu-/UDPspeeder#263]
Background:

   I have 2 default route, one is my isp, another Is others, I use iptables connmark+ip rule trick to mark the income connect attempt, and go out by the same interface and route.

   But this does not work with speeder, So maybe some special api speeder used.

Expected behavior:

    This trick should work by default for any socket application.

Reference:

https://home.regit.org/netfilter-en/netfilter-connmark/

**Comment by wangyu-** [comment]
>But this does not work with speeder, So maybe some special api speeder used.

I can confirm there shouldn't be special APIs that's not compatible with conntrack+ ip rules.

There is likely some mistakes in your conntrack or ip rules

**Comment by congzhangzh** [comment]
ok, tks
