### ISSUE TITLE
Mac and Windows native compilation

### ISSUE THREAD

**Issue by fairbairn** [wangyu-/UDPspeeder#265]
Is it possible to support native compilation of UDPSpeeder for Mac and Windows?

I know udp2raw supposedly supports them natively.  I wonder what it would take to be able to compile and run UDPSpeeder as binary executables on each of these platforms without the VM image.

More specifically, what needs to change in the makefile to be able to build the same binaries that are available in the pre-built releases?

We're attempting compilation on Catalina.

```
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wangyu-** [comment]
The instructions can be found from the [wiki](https://github.com/wangyu-/UDPspeeder/wiki).

Specially in this article: https://github.com/wangyu-/tinyPortMapper/wiki/How-to-build

For windows install "msys2+mingw-w32 or mingw-w64" first,  then run `make mingw` inside the directory of the repo in the terminal of msys2.

For mac install "gcc"(possibly from brew), then run `make mac` inside the directory.

**Comment by fairbairn** [comment]
Thank you.  I didn't think to look under tinyPortMapper.

That works great.

**Comment by wangyu-** [comment]
It's inside the UDPspeeder wiki, there is an article redirects you to the the tinyportMapper wiki:

https://github.com/wangyu-/UDPspeeder/wiki/How-to-build
