### ISSUE TITLE
Need confirmation on the supported client number

### ISSUE THREAD

**Issue by MakiseKurisu** [wangyu-/UDPspeeder#276]
I'm trying to tunnel multiple WireGuard connections. However, it seems like only the first connected client can communicate with the server. I'd like to check if this is the intended behavior.

**Comment by wangyu-** [comment]
Not the intented behavior, UDPspeeder support multiple connections.

**Comment by wangyu-** [comment]
For further clarification:
1. One UDPspeeder server supports multiple UDPspeeder clients.
2. One UDPspeeder client-server pair supports multiple upper-level connections
