### ISSUE TITLE
UDPspeeder fails after a long sleep in Windows 10 and UDPspeeder must be restarted

### ISSUE THREAD

**Issue by CCCAUCHY** [wangyu-/UDPspeeder#289]
English Only (except for bug reporting).

**Comment by wangyu-** [comment]
I suggest to write a tiny keep alive script:

https://github-com.translate.goog/wangyu-/udp2raw/wiki/%E8%BF%9B%E7%A8%8B%E4%BF%9D%E6%B4%BB?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp

it's more reliable than let UDPspeeder handles all the corner cases corretly.
