### ISSUE TITLE
实际应用

### ISSUE THREAD

**Issue by QiXianPu** [wangyu-/UDPspeeder#29]
今天早上没有更新v2时，我搭建环境玩游戏（守望先锋），方式如下：
```
$$ client 1--'TCP'---> $$ Server
$$ client 2--'UDP'---> udpspeeder cient ---'UDP'---> udpspeeder Server ---'UDP'---> $$ Server
```
延迟有点高（180ms），游戏卡顿。

晚上我重新搭建搭建了环境，并加入了udp2raw-tunnel，也使用的udpspeederv2

但现在效果没有早上的那个效果好，更卡顿了。

我觉得实际应用并没有缓解网络状况啊。
或者我有什么设置错误？

**Comment by wangyu-** [comment]
玩游戏建议用多倍发包，效果更好，不要用FEC，FEC主要是照顾到看视频和下载。用v1版的就可以，配置起来简单。

看起来没什么问题。你用speederv1 +udp2raw试试，把发包倍数调高一些，比如用`-d3`。

不过，延迟变高也是有可能的。可能连到守望先锋服务器的路由策略比较好，是直连。而连到linode日本的连接绕路了。路由策略决定的，你没办法改。

游戏变得卡顿不正常，游戏卡顿一般说明是丢包了，发了冗余数据后丢包不应该变高，至少不会比原来差。

你的udpspeeder client和udp2raw client运行在什么机器上？虚拟机？

**Comment by wangyu-** [comment]
>$$ client 1--'TCP'---> $$ Server
$$ client 2--'UDP'---> udpspeeder cient ---'UDP'---> udpspeeder Server ---'UDP'---> $$ Server

我查了以下，守望先锋不止要用UDP,还要用TCP。

你这个连法相当于TCP没有加速，反而先连到日本再连到韩国守望先锋服务器，绕了路。卡顿有可能是TCP连接造成的。

加速游戏建议用udp2raw+udpspeederv1+openvpn。如果不是特别能折腾，建议不要用udpspeeder+$$。

**Comment by QiXianPu** [comment]
是的，有可能是这个原因，我昨天晚上设置的用的v2，没有用多倍发包，也有可能是这个原因导致效果变差了。
之所以没用openvpn 是因为我在openvpn网站看到的搭建教程非常冗长，而在客户端的配置也非常长，所以先试试$$，看来现在要去看看openvpn了。
有个问题：
       那个udpspeederv2是不是没有-d的选项？

**Comment by wangyu-** [comment]
> 1.那个udpspeederv2是不是没有-d的选项？

v2版和v1版‘-d’相对应的选项是 `-f`，如果不会用，建议就用v1版的吧。

> 2.对于openvpn，iptables可不可以控制通过openvpn的流量？

用iptables和tc命令配合可以，具体的你得自己研究下了。

**Comment by QiXianPu** [comment]
配置OpenVPN时，这一步要不要设置：
Push DNS Changes to Redirect All Traffic Through the VPN
```
sudo vi /etc/openvpn/server.conf
                push "redirect-gateway def1 bypass-dhcp"
                push "dhcp-option DNS 208.67.222.222"
                push "dhcp-option DNS 208.67.220.220"
```

**Comment by wangyu-** [comment]
看使用场景。

你提供一下具体的部署方式。openvpn udpseeder client server 都运行在什么机器上，游戏运行在什么机器上。

**Comment by QiXianPu** [comment]
```
Windows PC<----->虚拟OpenWRT x86<----->Ubuntu 16.04LTS Server-------
```
其中OpenVPN ，udp2raw-tunnel和udpspeeder client都装在虚拟的OpenWRT上面。
游戏运行在Windows上面。

**Comment by wangyu-** [comment]
OpenVPN client 运行在虚拟机里的话，不需要`Push DNS Changes to Redirect All Traffic Through the VPN`，不过你要在Openwrt里配置路由规则。还有，在windows上让openvpn的网卡成为默认网卡。

如果OpenVPN client 运行在windows上比较简单（speeder仍然运行在虚拟机里），用`Push DNS Changes to Redirect All Traffic Through the VPN`应该就可以了。

具体细节你得自己goolge一下了。

**Comment by wangyu-** [comment]
我自己的使用方式是，udpspeeder和openvpn client都运行在路由器上。

我有两个路由器，一个是刷了openwrt的tplink，另一个是树莓派3b当路由器用，都可以。

**Comment by QiXianPu** [comment]
对了，我再使用udp2raw client时没用-a参数，而是直接自己输入的iptables规则：
```iptables -I INPUT -p tcp -s X.X.X.X --sport 80 -j DROP```
这样也行吧，就这一个规则吧？还有其他的吗？

**Comment by wangyu-** [comment]
>对了，我再使用udp2raw client时没用-a参数，而是直接自己输入的iptables规则：
iptables -I INPUT -p tcp -s X.X.X.X --sport 80 -j DROP
这样也行吧，就这一个规则吧？还有其他的吗？

你用udp2raw -g命令生成一下规则，然后自己手动加入这个规则，对udp2raw来说，只需要加这个一个规则，不需要其他。

**Comment by QiXianPu** [comment]
我设置openvpn服务端已经会了，但是在虚拟机上设置openvpn还不知道，看了一天了，现在有几个问题：

1. 目前openwrt提供的openvpn (openvpn-openssl_2.3.6-5_x86.ipk)版本低于官网的最新版本(2.4.4)，不同版本的客户端和服务端可以连接吗？
2. 在openwrt里配置路由规则，openwrt的wiki提供的资料是这么设置的，
```
   uci set openvpn.myvpn.route_nopull='1'
   uci add_list openvpn.myvpn.route='123.456.789.0 255.255.255.0'
   uci add_list openvpn.myvpn.route='234.567.891.0 255.255.255.0'
```
这里的`123.456.789.0 255.255.255.0`和`234.567.891.0 255.255.255.0`该设置成什么才能连上？

3. 我要让电脑里游戏的流量经过安装在电脑上的虚拟机发出去，我以前使用$$时是把网卡的默认网关改成虚拟openwrt的ip（也就是像我们登陆无线路由器时输入的`192.168.1.1`），现在改成使用openvpn后也还是这样设置吧？

**Comment by wangyu-** [comment]
>目前openwrt提供的openvpn (openvpn-openssl_2.3.6-5_x86.ipk)版本低于官网的最新版本(2.4.4)，不同版本的客户端和服务端可以连接吗？

应该是没问题的。

具体的OpenVPN配置你自己google一下吧，以前我配过但是已经忘了。我现在UDPspeeder和VPN是运行在路由器上的，虚拟机的你自己研究下。

另外，你可以参考下这个文章：http://blog.csdn.net/wolfid/article/details/77937488

**Comment by leepoi** [comment]
linode jp2 、vultr、conoha延迟和丢包率都很高，线路类似，中日线路晚高峰流量都被我国下片的绅士们占满了，个人感觉优化的余地不是很大。日本现在能用的就是linode jp1、Sakura、再就是软银机房里面的vps，即使如此，高峰期100ms也是家常便饭。韩国也有vps卖，你可以搜一下，中国北方从青岛出口通过海底光缆直连韩国，延迟和丢包率都很好

**Comment by QiXianPu** [comment]
>韩国也有vps卖，你可以搜一下，中国北方从青岛出口通过海底光缆直连韩国，延迟和丢包率都很好

@leepoi  谢谢提醒，韩国vps是哪家，麻烦发我一下，我没找到 : gmail: arisaly436 或者直接回复我

谢谢

**Comment by QiXianPu** [comment]
@wangyu- 
我已经成功设置好了openvpn，但是出现了问题：
刚开始我ping`OpenVPN`的服务端tun0 ip（`10.222.2.1`）可以ping通（在Windows主机上也可以ping通），但是测试访问网站时还是使用的默认路由（`default via 192.168.1.1 dev eth1  proto static  src 192.168.1.100`），没有经过OpenVPN，于是我在OpenWRT上手动设置了route 参数：
```
   ip route add Server IP via 192.168.1.1 dev eth1
   ip route change default via 10.222.2.5 dev tun100
```
此时仍可以ping通`10.222.2.1`，但是测试访问网站时直接显示无法解析DNS这类的信息。
下面是其他相关的东西：
```
Windows pc--->VirtualBOX OpenWRT(OpenVPN+udpspeeder)--->udpspeeder server--->OpenVPN server-----
```
```
OpenWRT iptables规则
# Generated by iptables-save v1.4.21 on Thu Sep 14 09:47:38 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -j ACCEPT
-A POSTROUTING -o eth1 -j MASQUERADE
-A POSTROUTING -s 192.168.144.0/24 -o tun+ -j MASQUERADE
-A POSTROUTING -j ACCEPT
COMMIT
# Completed on Thu Sep 14 09:47:38 2017
# Generated by iptables-save v1.4.21 on Thu Sep 14 09:47:38 2017
*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -j ACCEPT
COMMIT
# Completed on Thu Sep 14 09:47:38 2017
# Generated by iptables-save v1.4.21 on Thu Sep 14 09:47:38 2017
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -j ACCEPT
-A FORWARD -j ACCEPT
COMMIT
# Completed on Thu Sep 14 09:47:38 2017
# Generated by iptables-save v1.4.21 on Thu Sep 14 09:47:38 2017
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -j ACCEPT
-A FORWARD -j ACCEPT
-A OUTPUT -j ACCEPT
COMMIT
# Completed on Thu Sep 14 09:47:38 2017
```
```
br-lan    Link encap:Ethernet  HWaddr 08:00:27:76:6B:EB
          inet addr:192.168.144.1  Bcast:192.168.144.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe76:6beb/64 Scope:Link
          inet6 addr: fd71:5965:fbdb:4::1/62 Scope:Global
          inet6 addr: fd71:5965:fbdb::1/60 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1935 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1739 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:167655 (163.7 KiB)  TX bytes:265451 (259.2 KiB)

eth0      Link encap:Ethernet  HWaddr 08:00:27:76:6B:EB
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1997 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1733 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:203075 (198.3 KiB)  TX bytes:265171 (258.9 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:03:A5:13
          inet addr:192.168.1.100  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe03:a513/64 Scope:Link
          inet6 addr: fd71:5965:fbdb:0:a00:27ff:fe03:a513/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1635 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1664 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:250754 (244.8 KiB)  TX bytes:168655 (164.7 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:122 errors:0 dropped:0 overruns:0 frame:0
          TX packets:122 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:9099 (8.8 KiB)  TX bytes:9099 (8.8 KiB)
```
```
服务器iptables规则
# Generated by iptables-save v1.6.0 on Thu Oct 26 12:16:43 2017
*nat
:PREROUTING ACCEPT [5642:346098]
:INPUT ACCEPT [1319:81050]
:OUTPUT ACCEPT [16:1270]
:POSTROUTING ACCEPT [16:1270]
-A POSTROUTING -s 10.222.0.0/16 -o eth0 -j MASQUERADE
COMMIT
# Completed on Thu Oct 26 12:16:43 2017
```

**Comment by wangyu-** [comment]
>但是测试访问网站时直接显示无法解析DNS这类的信息。

可能是你的服务器没开启ipforward. 执行这条命令开启ip forward:

```echo 1 > /proc/sys/net/ipv4/ip_forward```

既然你都ping通了，那剩下的问题就是纯OpenVPN相关的了，去网上自己找一些OpenVPN教程看一下吧。

**Comment by QiXianPu** [comment]
ip转发我已经开启了，
```
vi /etc/sysctl.conf
net.ipv4.ip_forward=1
sysctl -p
```
```
root@localhost:~# cat /proc/sys/net/ipv4/ip_forward
1
```
openvpn搭建我都是照着官方教程来设置的，而上面的`ip route`规则也是在Stack Exchange上提问后别人提供的方法。现在真不知道哪里错了。: ）

**Comment by wangyu-** [comment]
>-A POSTROUTING -s 10.222.0.0/16 -o eth0 -j MASQUERADE

你服务器的网卡是不是不叫 eth0?

>-A POSTROUTING -s 192.168.144.0/24 -o tun+ -j MASQUERADE

这个tun+是什么意思，我看不懂

还有，虚拟机是不是桥接的

**Comment by wangyu-** [comment]
我建议你如果不是特别能折腾的话，还是把OpenVPN运行在windows上吧，让windows上的OpenVPN连虚拟机里的UDPspeeder。

就像这个issue里的一样：

https://github.com/wangyu-/UDPspeeder/issues/38

**Comment by QiXianPu** [comment]
服务器网卡是eth0，tun+可以代表tun100吧, +可以代表后面所有的数字。
openvpn自带的配置防火墙的例子就是这么设置的。
```
iptables -A INPUT -i tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -j ACCEPT
iptables -A INPUT -i tap+ -j ACCEPT
iptables -A FORWARD -i tap+ -j ACCEPT
```

还有虚拟机是桥接的，我以前用SS时也是这样弄得，没有问题。

**Comment by QiXianPu** [comment]
好的

**Comment by QiXianPu** [comment]
@wangyu- 
之所以没在windows上使用openvpn，是因为直接装在openwrt里更方便。
现在我发现了一个情况：

输入`ip route change default via 10.222.2.5`后，在Windows宿主机的cmd里输入`nslookup www.youtube.com 8.8.4.4`，可以解析到真正的ip。但打开浏览器后没法访问所有网站，显示无法访问目标网站的DNS之类的消息。

改成默认路由是`192.168.1.1`后，在Windows的cmd里输入`nslookup www.youtube.com 8.8.4.4`时，显示的是错误的ip, 但此时访问一般网站可以打开。

您觉得怎么处理才能解决这个问题啊？

谢谢你

**Comment by QiXianPu** [comment]
最后一个问题，问完我就关了，不麻烦你了，你也不是用的虚拟机，估计你也不知道该怎么解决。

我有个疑惑，为什么我使用`ss-redir`时没有任何问题，只是使用`iptables`把tcp和udp流量转发到`ss-redir`监听的端口后就可以正常访问所有网站了。而使用`OpenVPN`会出现无法解析DNS的情况？

**Comment by wangyu-** [comment]
>你也不是用的虚拟机，估计你也不知道该怎么解决。

确实我也不知道。不过有人报告把VPN运行在虚拟机里也成功了，可以看一下：

http://blog.csdn.net/wolfid/article/details/77937488

他用的是l2tp，不过和OpenVPN没有本质区别。

>我有个疑惑，为什么我使用ss-redir时没有任何问题，只是使用iptables把tcp和udp流量转发到ss-redir监听的端口后就可以正常访问所有网站了。而使用OpenVPN会出现无法解析DNS的情况？

可能的原因太多了：

也许你在server端没配好OpenVPN的流量重定向规则。

也许你在本机没配置好让流量走OpenVPN。具体的原因可能是你没让虚拟机的IP成为你的默认网关，或者你没把DNS改成8.8.8.8而你先前配置的DNS又拒绝对国外IP服务。

也许你本来配对了，但是被你配的其他iptables规则搞坏了。尤其是你以前配过s**-redir的规则。我建议把iptables全都清空了再配置。

>之所以没在windows上使用openvpn，是因为直接装在openwrt里使用时更方便。

如果你基础知识不好的话，暂时先把openvpn运行在windows上调试通。先把简单情况搞明白，再玩难度高的。

**Comment by raphael008** [comment]
@QiXianPu 我和你遇到了一样的症状😂，加个QQ交流一下？base64: ODA3MzE0MDcx

**Comment by QiXianPu** [comment]
我不知道你的情况，你是都装在路由里吗 还是装在win上。

**Comment by QiXianPu** [comment]
@wangyu- 

成功使用OpenVPN+udp2raw_tunnel+udpspeeder后，我现在测试了一下，发现：
ping 服务器的openvpn的网卡ip:  `min=109ms   max=156ms   avg=133ms`,
而直接ping服务器ip时：`min=105ms  max=129ms  avg=110ms`

会是什么原因？

**Comment by wangyu-** [comment]
有些运营商为了让ping值好看，会让ping走更快的路由路径。

比如我本地的移动就是，ping的延迟经常比tcp/udp要低几十毫秒。

这种情况用udp2raw_tunnel的icmp模式可以降低延迟。不过要小心，大流量ICMP可能会让VPS运营商以为你在DDOS攻击。根据我个人经验，vultr日本没问题，我经常用ICMP，从来没被封或被警告过。

**Comment by QiXianPu** [comment]
谢谢你，

但是会不会有多重加密的因素（虽然我感觉没多大关系）：
```
udp2raw:      --raw-mode faketcp -k "password2" --cipher-mode xor --auth-mode simple
udpspeeder:   -d3 -k "password1"
openvpn:      cipher AES-128-CBC
```
另外想达到游戏最好的效果就得知道isp对哪个协议的路由最好咯？

**Comment by wangyu-** [comment]
@raphael008 

可以看一下这个issue，我贴出了OpenVPN的完整配置，和虚拟机的网卡设置截图。

https://github.com/wangyu-/UDPspeeder/issues/55
