### ISSUE TITLE
[Feature] reverse connectivity support.

### ISSUE THREAD

**Issue by basncy** [wangyu-/UDPspeeder#295]
This program now works like ssh -L 0.0.0.0:4096:127.0.0.1:7777 but for UDP.

Can we add -R support like ssh -R 0.0.0.0:12345:127.0.0.1:5000?
OR can we configure(bind) a static source port when sending the package to 127.0.0.1:7777, e.g. https://stackoverflow.com/questions/9873061/how-to-set-the-source-port-in-the-udp-socket-in-c ?

The purpose is to enable the program which listen on 127.0.0.1:7777 to be able to send udp package back(to a preconfigured ip:port).

**Comment by wangyu-** [comment]
you can tunnel a VPN with UDPspeeder, then it automatically support reverse traffic.
