### ISSUE TITLE
Add the ability to not bind() and not connect(), at least on client mode. It's UDP anyway.

### ISSUE THREAD

**Issue by Originalimoc** [wangyu-/UDPspeeder#307]
It's straight unusable on roaming devices with multiple interfaces on and off frequently.
I think the main protocol(not UDP) itself is stateless(?) anyway like UDP.

**Comment by wangyu-** [comment]
udp being stateless doesn't mean if you remove bind() and connect() then it will support roaming automatically

**Comment by Originalimoc** [comment]
hmmm........ a reply after 18 month?
anyway I removed it and it works so...
???
it is?

**Comment by wangyu-** [comment]
Your issue didn't catch my attention, since it was written in confusing language. Like `Add...It's UDP anyway`

>???
it is?

After such a long time, you still doesn't seem to learn how to communicate clearly.

Anyway, nobody has any responsibility to reply to you.

**Comment by Originalimoc** [comment]
I think 1st post is already clear enough: If you don't bind() and connect(), then OS will decide which interface next packet is going to send through, but if bind() and connect() is called then a client restart is neccessary when network changes(eg. switch between Cell/WiFi/LAN), afterall what's the good point to use bind() and connect() in UDP anyway???
```
???
it is?
```
:
`it DOES support roaming automatically`

**Comment by wangyu-** [comment]
> afterall what's the good point to use bind() and connect() in UDP anyway???

In my case, mostly for simplicity.  In this way the OS remembers the remote endpoint for me. 

> I think 1st post is already clear enough: If you don't bind() and connect(), then OS will decide which interface next packet is going to send through, but if bind() and connect() is called then a client restart is necessary when network changes(eg. switch between Cell/WiFi/LAN)

Hi, thanks for your effort in explaining it.  Appreciate it.  

You do have some valid point.  I admit what you suggested can be useful in some case.
But it doesn't give you fully functional roaming:

```
Consider,  before your interface is down:
CLIENT----->session1-->UDPspeeder(eth0,202.96.x.x)-------------->UDPspeeder----session1------->SERVER

Now, your eth0 is down,  OS picked another interface with different IP:
client----->session1-->UDPspeeder(wlan0,210.82.x.x)--------------->UDPspeeder (see a new IP)

The UDPspeederServer doesn't know the new IP, so it will start a new session:
CLIENT----->session1-->UDPspeeder(wlan0,210.82.x.x)-------------->UDPspeeder---session2------->SEVER
```
You CLIENT thinks session1 is still valid, but actually SERVER has switched to session2.  Depends on what you CLIENT is, there are 3 possible cases:
1. it might work perfectly
2. it might have compatiblity issue, and doesn't work at all
3. you client think session1 times out, and have to start a new session. (in this case the service is interrupted before timeout is detected).

Here is how romaing is done in a faithfully enough way (it's already implemented in udp2raw):
```
before your interface is down.
CLIENT----->session1-->udp2raw(eth0,202.96.x.x)------------>udp2raw----session1------->SERVER

After eth0 is down:
CLIENT----->session1-->udp2raw(wlan0,210.82.x.x)-------------->udp2raw---session1(recovered)------->SERVER
```
when network adapter changes, the existing sessions are staying valid.  No issues mentioned above.

**Comment by Originalimoc** [comment]
Oh I think UDPspeeder has tagged the FEC packet thus the session recovery feature... My case it works because both CLIENTs is working authenticated and will dynamically switch endpoint IP to src of a known authenticated packet then.
