### ISSUE TITLE
max_conv_num max number

### ISSUE THREAD

**Issue by IMIEEET** [wangyu-/UDPspeeder#316]
hello there. im hitting maximum number of max_conv_num that is set to 10000 by default. is that a builtin tning or can i up it in sysctl? or i should compile with higher number?

**Comment by wangyu-** [comment]
increase the value of `max_conv_num` in `common.h` and re-compile

The default value 10000 is kind of for "self-protection", it protects misbehaved upper-level programs from creating a crazy amount of session/conversation to eat up your resource.

if you believe you need more than 10000, you can change it to 100000 or 1000000 without problem
