### ISSUE TITLE
:error: -r not found" pls help me thx 

### ISSUE THREAD

**Issue by bnrtlli** [wangyu-/UDPspeeder#318]
[2023-07-23 21:01:23][INFO]argc=8 ./speederv2_amd64 -s -l127.0.0.1:7776  -r127.0.0.1:7777 --mode 0 -f2:4 --timeout 1 
[2023-07-23 21:01:23][INFO]parsing address: 127.0.0.1:7776
[2023-07-23 21:01:23][INFO]its an ipv4 adress
[2023-07-23 21:01:23][INFO]ip_address is {127.0.0.1}, port is {7776}
[2023-07-23 21:01:23][FATAL]error: -r not found

**Comment by wangyu-** [comment]
I tried your options, couldn't reproduce
![image](https://github.com/wangyu-/UDPspeeder/assets/4922024/4ba56dc2-86d7-4f57-8eaf-a7faf09666c4)

maybe your system requires a space after "-r",  try `./speederv2 -s -l 127.0.0.1:7776  -r 127.0.0.1:7777 --mode 0 -f 2:4 --timeout 1`

**Comment by bnrtlli** [comment]
> I tried your options, couldn't reproduce ![image](https://user-images.githubusercontent.com/4922024/255432512-4ba56dc2-86d7-4f57-8eaf-a7faf09666c4.png)
> 
> maybe your system requires a space after "-r", try `./speederv2 -s -l 127.0.0.1:7776 -r 127.0.0.1:7777 --mode 0 -f 2:4 --timeout 1`

It's worked! thx bro

**Comment by bnrtlli** [comment]
> I tried your options, couldn't reproduce ![image](https://user-images.githubusercontent.com/4922024/255432512-4ba56dc2-86d7-4f57-8eaf-a7faf09666c4.png)
> 
> maybe your system requires a space after "-r", try `./speederv2 -s -l 127.0.0.1:7776 -r 127.0.0.1:7777 --mode 0 -f 2:4 --timeout 1`

it worked! thx bro !

**Comment by bnrtlli** [comment]
> I tried your options, couldn't reproduce ![image](https://user-images.githubusercontent.com/4922024/255432512-4ba56dc2-86d7-4f57-8eaf-a7faf09666c4.png)
> 
> maybe your system requires a space after "-r", try `./speederv2 -s -l 127.0.0.1:7776 -r 127.0.0.1:7777 --mode 0 -f 2:4 --timeout 1`

it worked! thx bro !
