### ISSUE TITLE
Udpspeeder with Shadowsocks or Socks5 possible? 

### ISSUE THREAD

**Issue by ryandotnet** [wangyu-/UDPspeeder#320]
Hi! I have a wireless connection that has 10-20% packet loss to every game server. 15ms game server and 80ms game server all the same. I think the loss is from my router to wireless tower. The game is CSGO. 

Will udpspeeder help with my connection? The game runs on windows but I use Linux VPS for server.

Do you have a setup guide for windows Udpspeeder + shadowsocks client with Linux Server?

What is the best way to forward CSGO udp packet through Udpspeeder? I don't think proxifier work because it's not a socks proxy. 

Thank you very much!

**Comment by testcaoy7** [comment]
Use tinyfecvpn instead.
udpspeeder, like it's name, only speeds up udp connections.

**Comment by ryandotnet** [comment]
Thank you!

**Comment by wangyu-** [comment]
it's indeed possible with udpspeeder, if you use kcptun/finalspeed together.

here is an article in chinese:
https://github.com/wangyu-/UDPspeeder/wiki/UDPspeeder---kcptun-finalspeed---%24%24-%E5%90%8C%E6%97%B6%E5%8A%A0%E9%80%9Ftcp%E5%92%8Cudp%E6%B5%81%E9%87%8F

in this way, the udpspeeder will improve your udp connection,  kcptun/finalspeed will deal with tcp.
