### ISSUE TITLE
Add multi core support

### ISSUE THREAD

**Issue by sdanfa** [wangyu-/UDPspeeder#326]
Hello,
Is there any plan to add multi core support on udp speeder? It is a very useful app for me but it's lacking multi core support. I hope you can add it.

Thank you!

**Comment by wangyu-** [comment]
No plan at the moment. 

Multiple-core is not super hard, but I have concerns about implementing it.

Also multiple-core is not the biggest possible improvement. I actually have investigated a avx2 enabled FEC library which can improve the performance by 10x，even if with single-core.   (Combining avx2 and multiple core, it's not hard to achieve a performance improvement of 40x)

But I am worrying about this program being abused.   I have seen a lot that people are sending crazy amounts of redundant packets (e.g. 10 times than original).

So I would like to keep the performance as-is.

**Comment by wangyu-** [comment]
In addition:

1. The current performance is enough for my personal use. So I don't have much impetus for my own sake.
2. Currently I am occupied with work, doesn't have much time on this. (I am a visa holder in the US, lost job means lost visa)

If you have large scale commercial use case, you can possibly mail me for collaboration in furture.

**Comment by sdanfa** [comment]
Hi, the performance in embedded router is pretty bad right now. Especially the small arm cpu struggle. Will you be able to fix the performance please? It would be helpful for me.

Thanks!

**Comment by wangyu-** [comment]
Sorry, no. 

If you urgently need, get a more powerful device.

**Comment by wangyu-** [comment]
Or trying to distrubute load to multiple UDPspeeder instance.

**Comment by sdanfa** [comment]
Hi my friend, is the banana pi new router good for this? Can you fix the code for it to run good on banana pi openwrt new router?

Thank you so much!

**Comment by Lu5ck** [comment]
I don't think AVX2 benefit router much, specifically routers running on openwrt and ddwrt so on. These arms chip don't support AVX2. Multicore on other hand can work on those routers.

**Comment by iopq** [comment]
Very bad performance on my VPS, need avx2 to not peg the CPU at 100% even going f2:1 because once it needs to do correction it's very slow and better to just let the packets drop by themselves by turning off FEC completely

When I added -mavx2 to the flags in the makefile, it resolved my issue. Should I open a pull request?
