### ISSUE TITLE
关于tcpspeed的问题

### ISSUE THREAD

**Issue by siriume** [wangyu-/UDPspeeder#33]
tcpspeed（fs）自带端口sock5端口1083。目前用sstap sock5 连接fs socks5端口，直接加速游戏。但是实际使用情况是经常断线，人物瞬移（丢包），我想用这个多倍发包或者冗余来解决这个问题

**Comment by wangyu-** [comment]
>tcpspeed（fs）自带端口sock5端口1083。

这个不是很清楚怎么配置，我只用过finalspeed，finalspeed只能加速指定的几个端口，不带socks5。

如果你折腾不明白的话，建议直接用UDPspeeder+OpenVPN吧，最简单直观的方法。

**Comment by wangyu-** [comment]
```
原始情况 ： 
sstap 
全局代理 
sock5 127.0.0.1:1083 

tcpspeed 
使用 udp 协议 
本地端口 1083 
指向服务器 
45.66.77.88:130 

game->sstapSocks5->tcpspeedClient->tcpspeedServer->gameServer 
加倍发包情况： 
sstap 
sock5 127.0.0.1:1083 

tcpspeed 
192.168.3.18(虚拟机 ip) 

在 client 端运行: 
./speederv2 -c -l0.0.0.0:130 -r44.55.66.77:4096 -f20:10 -k "passwd" 
让虚拟机 130 端口对应服务器 130 端口 

在 server 端运行: 
speederv2 -s -l0.0.0.0:4096 -r127.0.0.1:130 -f20:10 -k "passwd" 

game->sstapSocks5->tcpspeedClient->udpSpeederClient->udpSpeederServer->tcpspeedServer->gameServer 

链接一次就断开 不知道为啥
```

这个我看了，觉得如果按照finalspeed的方式理解，貌似没有问题。也许tcpspeed和finalspeed不一样，我没用过tcpspeed，抱歉。

如果是在不行，还是用UDPspeeder+OpenVPN吧。

**Comment by wangyu-** [comment]
另外，建议你排查下，sstapSocks5是不是劫持了虚拟机里的udpSpeederClient的流量。

**Comment by siriume** [comment]
如果把udpSpeederClient 和 tcpspeed调换下，是否可行。我没找到办法
game->udpSpeederClient->sstapSocks5->tcpspeedClient->tcpspeedServer->udpSpeederServer->gameServer

如果让sstap的流量分开发送，我也没有想到办法，不知道你教程里面的那个s*分开发送如何弄出来的。
game->sstapSocks5->tcpspeedClient->tcpspeedServer->
                                    udpSpeederClient->udpSpeederServer->gameServer

**Comment by wangyu-** [comment]
>如果让sstap的流量分开发送，我也没有想到办法，不知道你教程里面的那个s*分开发送如何弄出来的。

s**监听在一个tcp端口和一个udp端口，用udpspeeder映射那个udp端口，用kcptun映射那个tcp端口，很自然就分开了。

>如果把udpSpeederClient 和 tcpspeed调换下，是否可行。我没找到办法

貌似是不可行。

**Comment by siriume** [comment]
> 另外，建议你排查下，sstapSocks5是不是劫持了虚拟机里的udpSpeederClient的流量。
我添加了额外的路由表，虚拟机和服务器的ip都是直连的

**Comment by siriume** [comment]
> s**监听在一个tcp端口和一个udp端口，用udpspeeder映射那个udp端口，用kcptun映射那个tcp端口，很自然就分开了。

kcptun 感觉不太安全。s**没有开，用的chain_a协议。

**Comment by wangyu-** [comment]
>我添加了额外的路由表，虚拟机和服务器的ip都是直连的

那就不知道了，用UDPspeeder+OpenVPN吧。

**Comment by siriume** [comment]
> 那就不知道了，用UDPspeeder+OpenVPN吧。

anyconnect会设置么。。。openvpn我明天试试，还没架呢

**Comment by wangyu-** [comment]
>anyconnect会设置么

不会

**Comment by siriume** [comment]
今天遇到错误：
客户端：message too long len=1370 mtu=1250,ignored

**Comment by wangyu-** [comment]
用的是Openvpn？设置openvpn的mtu

**Comment by wangyu-** [comment]
Readme里面有openvpn的配置教程。

**Comment by siriume** [comment]
木有。用的还是老路子。

openvpn正在配置，用的是[onekey](https://github.com/Nyr/openvpn-install)安装，我大概看了下，应该可以把你的配置直接覆盖

port 1194
proto udp
dev tun

sndbuf 0
rcvbuf 0

topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt

keepalive 10 120
cipher AES-256-CBC
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem

#不用动？
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0

#删除
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 108.61.10.10"

**Comment by wangyu-** [comment]
我没用过onekey，你自己解决一下吧。

**Comment by siriume** [comment]
好的  我在试

**Comment by wangyu-** [comment]
你需要做的只是在openvpn client和 server之间加一个udpspeeder client和server，连接就能被加速了。然后注意一下MTU。

其他的只要合理，你随便配置，没有标准答案。具体的细节可以在网上找一下openpvn的教程。

**Comment by siriume** [comment]
感觉openvpn不安全，还是用了anyconnect，anyconnect可以把udp和tcp端口分开，然后把把127.0.0.1和虚拟网卡ip加入到no-route中 。正好udpspeed+udp-tunnel都能用上。操作可行。但是问题我不会后台执行命令。。。

anyconnect
 I  P             : x.x.x.x:
 TCP端口          : 9000
 UDP端口          : 9001
 单用户设备数限制 : 2
 总用户设备数限制 : 8

udpspeeder client:  ./speeder_x86 -c -l0.0.0.0:9001 -r127.0.0.1:8002 -f20:10 --mode 1
udp2raw client:  ./udp2raw_x86 -c -l0.0.0.0:8002 -r45.77.28.30:4096 -a --raw-mode faketcp -k "SpeedUP" --cipher-mode xor --auth-mode simple

udp2raw serevr: ./udp2raw_amd64 -s -l0.0.0.0:4096 -r 127.0.0.1:8000 -a --raw-mode faketcp -k "SpeedUP" --cipher-mode xor --auth-mode simple
udpspeeder server:  ./speeder_amd64 -s -l0.0.0.0:8000 -r 127.0.0.1:9001 -f20:10 --mode 1

**Comment by wangyu-** [comment]
>但是问题我不会后台执行命令。。。 

这个简单，装个tmux或者screen。装一个然后找教程学一下。

或者用nohup。

**Comment by siriume** [comment]
>这个简单，装个tmux或者screen。装一个然后找教程学一下。
或者用nohup。

我已经百度了，虚拟机怎么办

**Comment by wangyu-** [comment]
如果是我提供的那个虚拟机镜像的话：
`opkg update`
`opkg install tmux`

>虚拟机怎么办？输命令很头疼。。。

不看readme的后果。。。

虚拟机自带ssh，可以ssh进去，能复制粘贴。root密码:123456

**Comment by wangyu-** [comment]
>顺便帮我看下哪4行命令有没有错误 谢谢大佬

你不是说已经可以用了吗？我扫了一眼，没发现什么问题。

**Comment by siriume** [comment]
弄了  udpspeeder完全没有反应。。。。
把Cisco anyconnect 连接改成本地虚拟机的ip  连不上。虚拟机连连接都没创建

**Comment by wangyu-** [comment]
>弄了 udpspeeder完全没有反应。。。。
把Cisco anyconnect 连接改成本地虚拟机的ip 连不上。虚拟机连连接都没创建

我没用过anyconnect，如果你坚持要用anyconnect，那只有自己慢慢研究了。

**Comment by siriume** [comment]
anyconnect还是不行，暂时使用tcpspeed+sstap+udp2raw+udpspeedv2,可行，还没有断线过。
ps：作者没提到，两个同时用要把speederV2的mtu调到一样  1200，否则会提示消息过长

**Comment by wangyu-** [comment]
>ps：两个同时用要把speederV2的要使用mode0然后把mtu调到一样 1200，否则会提示消息过长。

这个最早的readme里确实没有说明，不过后来已经加上了。

>message too long....应该加个is把^_^

加不加都一样的。
