### ISSUE TITLE
请问udpspeeder能跟锐速共存吗?

### ISSUE THREAD

**Issue by MicrosoftYK** [wangyu-/UDPspeeder#35]
bbr对于我网络的高丢包效果不佳
不知道udpspeeder能否跟锐速共存，还是可以代替锐速？

**Comment by wangyu-** [comment]
根据配置方式的不同。

UDPspeeder和锐速可以独立工作，互不干扰。也可以和锐速叠加使用。

因为两者都可以加速tcp，所以UDPspeeder可以在一定程度上”代替” 锐速的功能。
