### ISSUE TITLE
直连OpenVPN正常,通过UDPSpeeder连接提示握手失败

### ISSUE THREAD

**Issue by sky92682** [wangyu-/UDPspeeder#38]
**环境:** 
OpenVPN客户端-Windows 10 1709 x64
UDPSpeeder客户端-Windows 10 1709 x64 Ubuntu子系统
UDPSpeeder,OpenVPN服务端-树莓派 Raspbian

**未能排查的问题:**
在不使用 UDPSpeeder 的情况下,OpenVPN 可以正常连接上 
通过 UDPSpeeder 连接的话,UDPSpeeder 客户端显示收到了 OpenVPN 客户端发送过来的数据包: 
![inked _20171023131916_li](https://user-images.githubusercontent.com/16216997/31872226-fcaf40fa-b7f4-11e7-864a-eb177860fb9a.jpg)

UDPSpeeder 服务端那边也显示收到了 UDPSpeeder 客户端发送过来的数据包: 
![inked _20171023132110_li](https://user-images.githubusercontent.com/16216997/31872245-3527a918-b7f5-11e7-927c-a8fada7a821c.jpg)

但是OpenVPN连接显示握手失败:
![_20171023132308](https://user-images.githubusercontent.com/16216997/31872254-550ba54a-b7f5-11e7-9514-28e0a85ad917.png)

**OpenVPN客户端配置文件如下(不包含证书部分):**
client
dev tun
proto udp
sndbuf 0
rcvbuf 0
remote 127.0.0.1 3333
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-CBC
comp-lzo
setenv opt block-outside-dns
key-direction 1
verb 3
mssfix 1200 
fragment 1200

**OpenVPN服务端配置文件如下:**
port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 168.126.63.1"
push "dhcp-option DNS 8.8.8.8"
keepalive 10 120
cipher AES-256-CBC
comp-lzo
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem
mssfix 1200 
fragment 1200

尝试过在启动UDPSpeeder命令中添加"--mode 0 --mtu 1200"参数,但错误依旧
从目前来看,UDP的隧道似乎是打通了,但是OpenVPN未能成功连接,问题应该是出在了认证这个阶段.
具体问题还需要进一步排查.

**Comment by wangyu-** [comment]
>push "redirect-gateway def1 bypass-dhcp"

把这一行从配置里去掉试试，貌似是openvpn为你的电脑添加了全局代理的功能，但是你没有在路由表里为UDPspeeder添加例外，UDPspeeder的流量被OpenVPN劫持了，造成了环路。

先去掉这行，测试能否连接成功。如果确认可以连接成功，再想办法添加例外。

**Comment by sky92682** [comment]
测试了依旧不行 
我想问题出现在OpenVPN建立的握手阶段,VPN连接尚未建立,应该不是劫持了UDPSpeeder的流量所致
不过我想到了一个可能的原因是我的服务端的500端口跑了SS服务,好像有些VPN的建立要用到这个端口
现在我手头有点别的事情,稍后排查一下这个问题,如果确认了问题所在,我会再次到这说明

**Comment by wangyu-** [comment]
好。

另外，建议你在调试阶段把`--mode 0 --mtu 1200`一直加上不要去掉，client和server端都加上。先完全排除MTU问题，然后再定位真正的问题出在哪

**Comment by wangyu-** [comment]
咦？我发现个问题，为什么你的server端用的是`UDPspeeder -c`，不是应该用-s么？

**Comment by sky92682** [comment]
感谢楼主的提醒 确实是因为服务端错误地使用了参数导致握手失败 修改之后可以正常连上了 但是不能访问互联网 现在正在研究添加例外

**Comment by wangyu-** [comment]
我在最新的OpenVPN+UDPspeeder里面加上了添加例外规则的例子，你可以参考，不过不一定能套用。

**Comment by wangyu-** [comment]
之前V2EX上面有人问WSL能不能用，你回他一下吧，告诉他是能用的。

**Comment by sky92682** [comment]
好的 我先告诉他一声 如果测试成功我会整理一下心得发上来

**Comment by wangyu-** [comment]
好的，多谢。

**Comment by sky92682** [comment]
不过WSL上不能用UDP2raw 提示不支持iptables

**Comment by wangyu-** [comment]
>不过WSL上不能用UDP2raw 提示不支持iptables

嗯，这个是已知的。

**Comment by sky92682** [comment]
我测试的结果是 OpenVPN服务端的配置文件里如果加入redirect-gateway这一行会导致连接的时候一直处于wait状态并最终超时握手失败 去掉这一行则能成功连上  我手动在OpenVPN客户端的配置文件里添加路由 最终实现了在WSL环境下使用OpenVPN通过UDPSpeeder通信 感谢作者的开发

**Comment by QiXianPu** [comment]
>  我手动在OpenVPN客户端的配置文件里添加路由

@sky92682  怎么添加的，能否把配置文件贴一下

谢谢

**Comment by sky92682** [comment]
请参照这篇文章
https://www.52os.net/articles/openvpn-add-local-routing-table.html

**Comment by raphael008** [comment]
@sky92682 我的树莓派在我一番摧残后重装了arm版centos，通过netcat测试一直提示no route to host，你有遇到过吗😂，网关也配置了
