### ISSUE TITLE
[2017-09-02 15:38:26][WARN]send returned -1 ,errno:Network is unreachable

### ISSUE THREAD

**Issue by Joney0210** [wangyu-/UDPspeeder#4]
[2017-09-02 15:38:26][WARN]send returned -1 ,errno:Network is unreachable

在Client端不斷接收此訊息. 

Server端上沒有,

在client端运行:
./speeder_arm -l0.0.0.0:1701 -r 47.x.x.x:139 -c -d3 -k "12345"

在server端运行:
./speeder_amd64 -l0.0.0.0:139 -r 127.0.0.1:1701 -s -d3 -k "12345"

可以看出來, 我是希望用在Xl2tp上的. 單純使用xl2tp vpn 時, 可以連通. 
但加上speeder後, VPN撥號有撥上, 但無法連通.

**Comment by wangyu-** [comment]
这个协议我没用过。但是我查了一下google:

>L2TP/IPSEC uses UDP 500 for the the initial key exchange, protocol 50 for the IPSEC encrypted data (ESP), UDP 1701 for the initial L2TP configuration and UDP 4500 for NAT traversal.

貌似它用了很多Udp端口，应该得把这些端口全都映射到本地吧。

openvpn只需要一个端口，比较简单，建议尝试一下openvpn

**Comment by wangyu-** [comment]
已经确认了。L2TP可以被udpspeeder加速，只需要映射1701端口到本地。但是不支持L2TP+IPSEC这种方式，单独使用L2TP没问题。
