### ISSUE TITLE
直连openVPN成功，通过UDPspeeder失败

### ISSUE THREAD

**Issue by kwxiaozhu** [wangyu-/UDPspeeder#43]
### openVPN server.conf

>client-cert-not-required
client-to-client
persist-key
persist-tun
username-as-common-name
auth-user-pass-verify /etc/openvpn/checkpsw.sh via-env
ca /etc/openvpn/ca.crt
cert /etc/openvpn/openvpn-server.crt
key /etc/openvpn/openvpn-server.key
tls-auth /etc/openvpn/ta.key 0
dh /etc/openvpn/dh2048.pem
dev tun1
port 1195
proto udp
ifconfig-pool-persist /var/log/openvpn/ipp.txt
keepalive 10 120
script-security 3
server 172.16.3.0 255.255.255.0
status /var/log/openvpn/openvpn-status-private.log
topology subnet
comp-lzo yes
verb 3
mute 20
push dhcp-option DNS 172.16.3.1
client-config-dir /etc/openvpn/ccd
fragment 1200
mssfix 1200 
sndbuf 2000000 
rcvbuf 2000000 
txqueuelen 4000 

### openvpn client.conf
>auth-user-pass pw.txt
client
dev tun
proto udp
#remote 45.77.88.99 1195
remote 127.0.0.1 3333
resolv-retry infinite
nobind
persist-key
persist-tun
#cipher none 
key-direction 1
\<ca\>
\</ca\>
\<tls-auth\>
\</tls-auth\>
ns-cert-type server
comp-lzo
verb 1
mute 20
fragment 1200 
mssfix 1200 
sndbuf 2000000
rcvbuf 2000000 
txqueuelen 4000 

### run on openvpn server side 
`./speederv2_amd64 -s -l0.0.0.0:7777 -r 127.0.0.1:1195 -f20:10 --mode 0 --mtu 1200 -k "password"`
### run on openvpn client side 
`./speederv2_amd64 -c -l0.0.0.0:3333 -r  45.77.88.99:7777 -f20:10 --mode 0 --mtu 1200 -k "password"`

### 如果直连openVPN服务器一切正常，如果通过speederv2 的127.0.0.1:3333 连接，则提示

> 10月 24 16:57:24 debian9 ovpn-client[20151]: library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.08
10月 24 16:57:24 debian9 ovpn-client[20152]: TCP/UDP: Preserving recently used remote address: [AF_INET]127.0.0.1:3333
10月 24 16:57:24 debian9 ovpn-client[20152]: UDP link local: (not bound)
10月 24 16:57:24 debian9 ovpn-client[20152]: UDP link remote: [AF_INET]127.0.0.1:3333
10月 24 16:58:24 debian9 ovpn-client[20152]: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
10月 24 16:58:24 debian9 ovpn-client[20152]: TLS Error: TLS handshake failed`

### 我的openVPN配置了用户名密码认证，不过应该跟这没关系吧

**Comment by wangyu-** [comment]
配置没什么问题。我目前能想到的是有可能服务器上的防火墙没开7777这个端口。

你再贴一下两边UDPspeeder的log，加上`--log-level 5 --log-position`

**Comment by kwxiaozhu** [comment]
### 服务端日志
>[2017-10-24 17:44:06][INFO]argc=15 ./speederv2_amd64 -s -l0.0.0.0:7777 -r 127.0.0.1:1195 -f20:10 --mode 0 --mtu 1200 -k password --log-level 5 --log-position 
[2017-10-24 17:44:06][DEBUG]key=password
[2017-10-24 17:44:06][INFO][main.cpp,func:process_arg,line:1584]jitter_min=0 jitter_max=0 output_interval_min=0 output_interval_max=0 fec_pending_time=8 fec_data_num=20 fec_redundant_num=10 fec_mtu=1200 fec_pending_num=200 fec_type=0
[2017-10-24 17:44:06][DEBUG][main.cpp,func:init_listen_socket,line:93]local_listen_fd=5
,[2017-10-24 17:44:06][DEBUG][main.cpp,func:server_event_loop,line:644] delay_manager.get_timer_fd() =3
[2017-10-24 17:44:06][INFO][main.cpp,func:server_event_loop,line:646]now listening at 0.0.0.0:7777
[2017-10-24 17:44:06][DEBUG][main.cpp,func:server_event_loop,line:654] timer.get_timer_fd() =7
[2017-10-24 17:44:24][DEBUG][main.cpp,func:server_event_loop,line:742]fec_fd64=4294967396
[2017-10-24 17:44:24][DEBUG][main.cpp,func:server_event_loop,line:752]conn_info.timer.get_timer_fd64()=4294967397
[2017-10-24 17:44:24][INFO][main.cpp,func:server_event_loop,line:757]new connection from 39.151.206.190:55199
[2017-10-24 17:44:24][DEBUG][main.cpp,func:new_connected_socket,line:118][127.0.0.1:1195]created new udp_fd 10
[2017-10-24 17:44:24][INFO][main.cpp,func:server_event_loop,line:808][39.151.206.190:55199]new conv f482fe01,fd 10 created,fd64=4294967398
[2017-10-24 17:44:25][DEBUG][main.cpp,func:new_connected_socket,line:118][127.0.0.1:1195]created new udp_fd 11
[2017-10-24 17:44:25][INFO][main.cpp,func:server_event_loop,line:808][39.151.206.190:55199]new conv edb11c38,fd 11 created,fd64=4294967399

### 客户端日志
>[2017-10-24 17:44:19][INFO]argc=15 ./speederv2_amd64 -c -l0.0.0.0:3333 -r 45.76.192.22:7777 -f20:10 --mode 0 --mtu 1200 -k password --log-level 5 --log-position 
[2017-10-24 17:44:19][DEBUG]key=password
[2017-10-24 17:44:19][INFO][main.cpp,func:process_arg,line:1584]jitter_min=0 jitter_max=0 output_interval_min=0 output_interval_max=0 fec_pending_time=8 fec_data_num=20 fec_redundant_num=10 fec_mtu=1200 fec_pending_num=200 fec_type=0
[2017-10-24 17:44:19][DEBUG][main.cpp,func:init_listen_socket,line:93]local_listen_fd=7
,[2017-10-24 17:44:19][DEBUG][main.cpp,func:new_connected_socket,line:118][45.76.192.22:7777]created new udp_fd 9
[2017-10-24 17:44:19][DEBUG][main.cpp,func:client_event_loop,line:346]remote_fd64=4294967397
[2017-10-24 17:44:19][DEBUG][main.cpp,func:client_event_loop,line:360]delay_manager.get_timer_fd()=3
[2017-10-24 17:44:19][DEBUG][main.cpp,func:client_event_loop,line:371]conn_info.fec_encode_manager.get_timer_fd64()=4294967395
[2017-10-24 17:44:19][DEBUG][main.cpp,func:client_event_loop,line:382]conn_info.timer.get_timer_fd()=6
[2017-10-24 17:44:24][INFO][main.cpp,func:client_event_loop,line:497]new packet from 127.0.0.1:49821,conv_id=f482fe01
[2017-10-24 17:44:25][INFO][main.cpp,func:client_event_loop,line:497]new packet from 127.0.0.1:50435,conv_id=edb11c38
[2017-10-24 17:45:04][INFO][connection.cpp,func:clear_inactive0,line:166]conv f482fe01 cleared
[2017-10-24 17:45:31][INFO][main.cpp,func:client_event_loop,line:497]new packet from 127.0.0.1:49196,conv_id=ae177ea8
[2017-10-24 17:45:37][INFO][connection.cpp,func:clear_inactive0,line:166]conv edb11c38 cleared

**Comment by kwxiaozhu** [comment]
### 服务端防火墙就没开启

**Comment by wangyu-** [comment]
先用netstat -nlp看一下OPENVPN server有没有bind到127.0.0.1:1195

然后用netcat测试一下通过UDPspeeder能不能正常收发数据。

**Comment by kwxiaozhu** [comment]
netstat -nlp 已经bind到0.0.0.0:1195
服务端用nc -ul -p 1196 监听udp 1196端口，用./speederv2_amd64 -s -l0.0.0.0:7777 -r 127.0.0.1:1196 -f20:10 --mode 0 --mtu 1200 -k "password" --log-level 5 --log-position加速，客户端运行./speederv2_amd64 -c -l0.0.0.0:3333 -r 45.77.88.99:7777 -f20:10 --mode 0 --mtu 1200 -k "password" --log-level 5 --log-position用nc -u 127.0.0.1 3333连接输入test在服务端可以收到test，证明可以正常通信。

**Comment by wangyu-** [comment]
在nc服务端也输入一下数据，测试下反向的通信有没有问题

**Comment by kwxiaozhu** [comment]
刚测试反向通信收不到数据

**Comment by kwxiaozhu** [comment]
又重试了一下，现在正向通信也不行，nc连上以后输入测试数据就直接退出了，而直接连接服务端IP就没有问题

**Comment by wangyu-** [comment]
能提供一下环境吗？wangyucn@gmail.com

**Comment by wangyu-** [comment]
现在这个情况，需要用tcpdump看一下了，看一下反向不通是因为server没有把数据发出来，还是server发了client没有收到。

如果你有能力可以自己看一下。

**Comment by wangyu-** [comment]
我想到个问题，你刚才说：
>又重试了一下，现在正向通信也不行，nc连上以后输入测试数据就直接退出了，而直接连接服务端IP就没有问题

nc的服务端只能接受一个client连接一次,可能是这个问题导致的。你把nc client和server都杀掉重启，重新试一下双向的传输有没有问题。

**Comment by kwxiaozhu** [comment]
客户端和服务器端同时运行tcpdump -i eth0 -vv 'udp and port 7777'抓包，nc测得
客户端——>服务端 第一次数据正常传输，第2次以后server端nc收不到数据，但是tcpdump抓server端7777端口有数据，speeder日志提示
[DEBUG][main.cpp,func:server_event_loop,line:900]udp fd,recv_len<0 continue,Connection refused
服务端——>客户端 服务端收到数据回复时，客户端收不到回复，tcpdump抓server端7777端口没有数据。

**Comment by kwxiaozhu** [comment]
直接用nc连接server端正向和反向通信都没有问题，可以重复多次传输数据。

**Comment by wangyu-** [comment]
>Connection refused

这个是我刚才说的那个问题导致的。nc 的server只能被一个client连一次。

>服务端——>客户端 服务端收到数据回复时，客户端收不到回复，tcpdump抓server端7777端口没有数据。

这个是把nc的 client和server都kill后测的吗？

**Comment by wangyu-** [comment]
>可以重复多次传输数据。

是可以重复多次传输，只是一个sever只能接受client的一次连接。

**Comment by wangyu-** [comment]
>客户端——>服务端 第一次数据正常传输，第2次以后server端nc收不到数据，但是tcpdump抓server端7777端口有数据，speeder日志提示

这个第一次和第二次是说，同一连接，多次发送数据吗？

**Comment by kwxiaozhu** [comment]
>我想到个问题，你刚才说：
又重试了一下，现在正向通信也不行，nc连上以后输入测试数据就直接退出了，而直接连接服务端IP就没有问题
nc的服务端只能接受一个client连接一次,可能是这个问题导致的。你把nc client和server都杀掉重启，重新试一下双向的传输有没有问题。

这个是我之前测试时输入了错误的端口导致的，更正后正向通信也是只限于第一次。

>这个是把nc的 client和server都kill后测的吗？

是的，每次测试都是先kill掉nc的server和client

>这个第一次和第二次是说，同一连接，多次发送数据吗？

是同一连接，测试过程是nc的client连上后先发送数据，server端可以收到，client端再发数据，server端nc收不到数据，但是tcpdump有数据，server端向client端发送数据，client端收不到，并且server端和client端的tcpdump都没有数据，我想应该是server端收到一次数据就关闭连接了，但是直接连接server端IP的话是可以一个连接多次发送数据的。

**Comment by wangyu-** [comment]
>服务端用nc -ul -p 1196 监听udp 1196端口
./speederv2_amd64 -s -l0.0.0.0:7777 -r 127.0.0.1:1196 -f20:10 --mode 0 --mtu 1200 -k "password" --log-level 5 --log-position
客户端运行
./speederv2_amd64 -c -l0.0.0.0:3333 -r 45.77.88.99:7777 -f20:10 --mode 0 --mtu 1200 -k "password" --log-level 5 --log-position

我用了一样的命令测试，测试了几次，双向通信多次都是正常的，没办法复现。

你再尝试一下在两边加上--report 5，再测试一次，测试完贴下两边UDPspeeder的log。

**Comment by wangyu-** [comment]
会不会是7777这个端口号的问题，把这个端口换成一个已知可以正常通信的端口（比如1196）试下？

**Comment by kwxiaozhu** [comment]
刚才我又在我局域网内的nas和香蕉派两台机器上实验，还是同样的问题，无法双向通信。

**Comment by wangyu-** [comment]
>在两边执行一下./speederv2_amd64 --help，贴出结果，我看下是哪个版本。

**Comment by kwxiaozhu** [comment]
>130 root@bananapi ~/speederv2 # ./speederv2_arm --help                                                                                                                                    :(
UDPspeeder V2
git version:39f2ead0af    build date:Oct 21 2017 11:10:36
repository: https://github.com/wangyu-/UDPspeeder

>130 root@debian9 ~/speederv2 # ./speederv2_amd64 --help                                                                                                                                   :(
UDPspeeder V2
git version:39f2ead0af    build date:Oct 21 2017 11:10:20
repository: https://github.com/wangyu-/UDPspeeder

刚下的最新release版

**Comment by wangyu-** [comment]
我之前用的不是这个版本，但是我刚才下载了这个版本反复测试了好几次，都没能复现这个问题。

然后我尝试client和server都跑在单机上，也没问题。

麻烦你在单机上测试一下，看是否正常。

**Comment by wangyu-** [comment]
>麻烦你在单机上测试一下，看是否正常。

你找台不重要的机器测试一下，如果单机还是能复现这个问题，把这个环境提供给我，我上去测试一下。

**Comment by kwxiaozhu** [comment]
测试环境已经发到你的邮箱，感谢！

**Comment by wangyu-** [comment]
>你好，我看你client端连的是45.77.88.99，本地测试应该连127吧

看到了哈哈，忘改了

**Comment by kwxiaozhu** [comment]
echo "你可以这样和我聊天" >/dev/pts/1

**Comment by wangyu-** [comment]
我目前发现你这机器，不使用udpspeeder也有一样的问题：

nc -l -p 3334 -u

nc -u 127.0.0.1 3334

貌似只要通过127.0.0.1通信就有问题。具体原因我也很好奇，我在排查。

2017-10-24 5:40 GMT-07:00 wang yu <wangyu.cn@gmail.com>:

> >你好，我看你client端连的是45.77.88.99，本地测试应该连127吧
>
> 看到了哈哈，忘改了
>

**Comment by wangyu-** [comment]
>echo "你可以这样和我聊天" >/dev/pts/1

这样有点乱 = =

**Comment by kwxiaozhu** [comment]
貌似跟我机器上的一条iptables规则有关
iptables -t nat -A POSTROUTING -j MASQUERADE
删掉nc 127可以通信
我的NAS上没有这条命令，用nc 127测试正常，但是套上udpspeeder还是不行

**Comment by wangyu-** [comment]
>iptables -t nat -A POSTROUTING -j MASQUERADE

这条我可以删吗？如果127不能连的话，我就没法测试了。

**Comment by kwxiaozhu** [comment]
可以，已经帮你删掉，测试本地nc是正常的

**Comment by wangyu-** [comment]
>可以，已经帮你删掉，测试本地nc是正常的

删了以后UDPspeeder也正常了。

**Comment by kwxiaozhu** [comment]
确实是这样，但是相同的原理我用kcptun都正常，而udpspeeder就不行，我加这条命令主要是为了VPN连上以后做NAT访问内网用的，也不能不用呀

**Comment by wangyu-** [comment]
一般NAT不都这么写吗：

`iptables -t nat -A POSTROUTING -s 10.222.0.0/16 -o eth0 -j MASQUERADE`
或者
`iptables -t nat -A POSTROUTING -s 10.222.0.0/16 -j SNAT --to-source 44.55.66.77`

>iptables -t nat -A POSTROUTING -j MASQUERADE

你这个写法是有问题的。

>但是相同的原理我用kcptun都正常
kcptun一端是tcp连接，一段是udp连接， UDPspeeder两端都是udp连接。也许你这条命令只会干扰到127.0.0.1的udp不会干扰tcp。

**Comment by kwxiaozhu** [comment]
好吧，这是我偷懒的写法，我的内网环境有点复杂，为了不每个vpn网段都写一条命令，我就写一个命令了，没想到还会有这问题，非常感谢你的帮助，谢谢！

**Comment by wangyu-** [comment]
>非常感谢你的帮助，谢谢！

没事。
