### ISSUE TITLE
在pfsense路由器怎么用

### ISSUE THREAD

**Issue by liuxyon** [wangyu-/UDPspeeder#45]
我目前在国外用vps建openvpn,然后国内用pfsense接入vpn,pfsense里搭建的局域网，目前通过vpn nat到我本地局域网内各类web服务器，目前问题是有时丢包比较高20左右，随之延迟也高300多，另外openvpn我从本地局域网下载测速很慢，只有几兆。所以要找个解决方案,有聊天联系方式吗，这里写太多了。

**Comment by wangyu-** [comment]
没用过pfsense，抱歉。

**Comment by liuxyon** [comment]
就是freebsd 系统

**Comment by wangyu-** [comment]
freebsd不能用，需要移植。
