### ISSUE TITLE
可否将代码缩进自动排版？

### ISSUE THREAD

**Issue by bg6cq** [wangyu-/UDPspeeder#49]
您好！

目前的代码的缩进比较散，可否执行以下命令自动排版？

indent *.cpp -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4  -cli0 -d0 -di1 -nfc1 -i8 -ip0 -l160 -lp -npcs -nprs -npsl -sai -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8

谢谢

**Comment by wangyu-** [comment]
我试了一下，代码排版风格全变了。

暂时不想改变风格。

**Comment by bg6cq** [comment]
indent *.cpp -nbad -bap -nbc -bbo -hnl -bli0 -brs -c33 -cd33 -ncdb -ce -ci4 -cli0 -d0 -di1 -nfc1 -i8 -ip0 -l160 -lp -npcs -nprs -npsl -sai -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8

这样行不行呢？跟您之前的风格几乎一样

**Comment by wangyu-** [comment]
暂时先不要动缩进了。 全局缩进重排造成的diff太多，不便于版本管理。

目前的缩进还可以把，可能局部有些问题，局部改一下就可以。

有些空行是我故意加上的，把功能紧密的代码用空行隔成一块一块，隔的空行越多越不相关。重排了多行就变成单行了。
