### ISSUE TITLE
如何加速ssr游戏模式下的UDP数据

### ISSUE THREAD

**Issue by ZhxChen** [wangyu-/UDPspeeder#5]
如何加速ssr游戏模式下的UDP数据

本地ss-redir默认端口3333

VPS ssr服务监听接口2333

是本地SSR-（2333）-UDPspeederC（本地2333）服务器（23333）--------VPS（23333）本地2333---SSR服务端  
是这样么

还有我在本地LEDE上跑 提示

Segmentation fault

错误

**Comment by ZhxChen** [comment]
看了前面的回答 发现太复杂了  还是关了这个

**Comment by wangyu-** [comment]
如果这个SSR的加速环境是你自己搭的，那么非常简单。只要用UDPspeeder把ssr的udp端口映射到本地，再用kcptun/ncat/ssh/iptables（任意一个方法都可以）规则把ssr的tcp端口映射到本地，就可以办到。就像图中的一样。

![image0](https://raw.githubusercontent.com/wangyu-/UDPspeeder/master/images/Capture3.PNG)

#2 之所以没搞定是因为@genics 的SSR环境不是自己搭的，而是用梅林固件自带的，梅林固件对扩展不友好。而@genics又对iptables规则之类的东西不是很熟悉。

@baggiogogo在那个帖子里也有回复，他的环境是自己用树莓派搭的，没费多大力气就成功了。

**Comment by wangyu-** [comment]
>Segmentation fault
可能是没选对版本，也可能是release里没有可以用的版本，用路由器的toolchain编译一下可以解决。

**Comment by genics** [comment]
我用的lede固件已经加入udpspeeder了，有ui，直接配置。不过还是很难配置，正在研究。说明上这样写的。

UDPspeeder加速SS游戏模式udp的简要操作手册：
根据 官方说明文档配置好服务器端程序；
比如你正在使用SS游戏模式，此时用命令ps | grep ss-redir 可以查看到相关进程。
例如查看进程找到【ss-redir -b 0.0.0.0 -c /koolshare/ss/ss.json -u -f /var/run/shadowsocks.pid】此条；
该进程同时承载了ss的tcp和udp流量，需要将tcp和udp分开成两个进程，方便运行UDPspeeder单独加速udp，用命令killall ss-redir 将进程杀死，然后运行下面两个命令重新启动ss-redir；
命令1（运行ss-redir转发tcp流量，去掉原命令 -u选项）：ss-redir -b 0.0.0.0 -c /koolshare/ss/ss.json -f /var/run/shadowsocks.pid
命令2（运行ss-redir转发udp流量，去掉原命令 -u选项，加上 -U选项，并加上 -s 127.0.0.1）：ss-redir -b 0.0.0.0 -s 127.0.0.1 -c /koolshare/ss/ss.json -U -f /var/run/shadowsocks.pid
假如你的ss服务器端口是2345，接下来可以在本插件里填写[本地监听地址：端口]为 0.0.0.0:2345；[填写服务器地址：端口]为 vps_ip:2345；
选择客户端模式，并填写其它参数（除了密码外，其它参数服务器和客户端可以不一致）后点击保存，即可加速游戏模式的udp流量了。
你可以自己配置触发脚本来实现以上功能；

**Comment by ZhxChen** [comment]
按照描述的搭可以成功的

**Comment by wangyu-** [comment]
>还有我在本地LEDE上跑 提示

>Segmentation fault

>可能是没选对版本，也可能是release里没有可以用的版本，用路由器的toolchain编译一下可以解决。

现在最新版release里的speeder_amd64，可以直接运行在x64的lede上了。不需要自己编译了。
