### ISSUE TITLE
“windows自带vpn client -> UDPspeeder client -> UDPspeeder server -> OpenVPN server” 这样行吗？

### ISSUE THREAD

**Issue by shithappens2016** [wangyu-/UDPspeeder#50]
“windows自带vpn client -> UDPspeeder client -> UDPspeeder server -> OpenVPN server” 

你好，请问这样的串联可以配置吗？

我想用网线连接树莓派和路由器，软件都安装在树莓派上，pc上不要安装任何软件（只做设置）。

不知道像作者那样，把树莓派作为路由，pc上作些什么？

**Comment by wangyu-** [comment]
>windows自带vpn client 

windows好像不带openvpn的客户端。

>我想用网线连接树莓派和路由器，软件都安装在树莓派上，pc上不要安装任何软件（只做设置）。
不知道像作者那样，把树莓派作为路由，pc上作些什么？

pc上什么也不用做，完全透明。现在我的环境就是所有东西都安装在树莓派上。

**Comment by shithappens2016** [comment]
你好 @wangyu- 
请问 树莓派 配置成路由器 后，能与原来的路由器并存吗？
能否 只在windows下更改个网关ip来切换不同的路由器呢？

**Comment by jlccskw** [comment]
我的openvpn运行在win上的,有客户端的.不太明白vpn运行在树莓派上的话,电脑要怎么跟树莓派连接呢?

**Comment by shithappens2016** [comment]
希望作者能出个配置树莓派作为路由器的文档。
@wangyu-

**Comment by wangyu-** [comment]
@shithappens2016 

我写了一个，但是仅供参考，不要问我细节。

https://github.com/wangyu-/UDPspeeder/wiki/用树莓派做路由器，搭建透明代理，加速游戏主机的网络

**Comment by shithappens2016** [comment]
@wangyu- 
nice
