### ISSUE TITLE
如果使用后不丢包，但是延迟抖动较大，应该怎么调优

### ISSUE THREAD

**Issue by myliyifei** [wangyu-/UDPspeeder#51]
平时延迟良好，偶尔出现大延迟的抖动，应该如何调优呢，下面选项是否有用?应该选择什么值呢？

-i 选项

指定一个时间窗口，长度为n毫秒。同一个fec分组的数据在发送时候会被均匀分散到这n毫秒中。可以对抗突发性的丢包。默认值是0，因为这个功能需要用到时钟，在某些虚拟机里时钟不稳定，可能会导致个别包出现非常大的延迟，所以默认关掉了。这个功能很有用，默认参数效果不理想时可以尝试打开。这个选项的跟通信原理上常说的交错fec 交织fec的原理是差不多的。

**Comment by wangyu-** [comment]
>指定一个时间窗口，长度为n毫秒。同一个fec分组的数据在发送时候会被均匀分散到这n毫秒中。可以对抗突发性的丢包。默认值是0，因为这个功能需要用到时钟，在某些虚拟机里时钟不稳定，可能会导致个别包出现非常大的延迟，所以默认关掉了。这个功能很有用，默认参数效果不理想时可以尝试打开。这个选项的跟通信原理上常说的交错fec 交织fec的原理是差不多的。

这个是防止突发丢包用的。不能降低延迟抖动。

>平时延迟良好，偶尔出现大延迟的抖动，应该如何调优呢，下面选项是否有用?应该选择什么值呢？

截个图看看。是不是用在虚拟机里？vmware的话，根据我个人经验如果宿主机忙，虚拟机性能会严重下降。
