### ISSUE TITLE
可以提供LEDE/OPENWRT的makefile吗

### ISSUE THREAD

**Issue by imwsy** [wangyu-/UDPspeeder#52]

**Comment by wangyu-** [comment]
目前的makefile支持用LEDE/OPENWRT的toolchain编译。具体看一下：

https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/build_guide.zh-cn.md

另外，我在release里已经包含了opewrt/lede 常用cpu的预编译版本了，一般不需要自己编译。

**Comment by imwsy** [comment]
有一种情况 比如我需要同时编译集成了这个组建几种不同构架的ROM 用这种方法就不太方便了 所以还是需要标准的makefile？另外有了标准的makefile 更新版本也会相对简单点
@wangyu-

**Comment by wangyu-** [comment]
你可以自己写一个，PR过来。
