### ISSUE TITLE
这是什么错误？

### ISSUE THREAD

**Issue by bao3** [wangyu-/UDPspeeder#53]
先是在 client 端看到这个 
`[2017-10-29 19:49:52][WARN]recv failed -1 ,udp_fd9,errno:Connection refused`

client 配置
> ./speederv2_arm -c -l0.0.0.0:9998 -r 1.1.1.1:8080  -k "right-rae-guano-team-sill" -f30:10 --mtu 1600

Server端发生：

`[2017-10-29 11:51:21][ERROR]recv_from error,this shouldnt happen at client`

server 
> speederv2 -s -l0.0.0.0:8080 -r 127.0.0.1:6553 -k right-rae-guano-team-sill -f20:10 --mtu 1550

**Comment by wangyu-** [comment]
疑似是VPS本身的问题，之前也有人遇到，换了个VPS解决了：

https://github.com/wangyu-/UDPspeeder/issues/42
