### ISSUE TITLE
多倍发包和fec的实际区别是什么？

### ISSUE THREAD

**Issue by BH4WHN** [wangyu-/UDPspeeder#54]
以10秒发送10个原始数据包为例，假设线路丢包率20%。
个人理解：2倍发包就是10原始包+10备份包=20个包，远端实际收到16个包。
如果不幸这16个包收到的是前8个原始包+前8个备份包，那么数据实际收到是损坏的，丢失的2个包会触发软件快速重传之类的机制吗？目测好像没这功能
fec和多倍发包的真正区别是什么？目前主要依赖udpspeeder双倍发包玩游戏和kcptun并联工作，掉线次数确实减少了，也试过4倍发包效果没啥区别，并不令人满意。

**Comment by wangyu-** [comment]
>个人理解：2倍发包就是10原始包+10备份包=20个包，远端实际收到16个包。
如果不幸这16个包收到的是前8个原始包+前8个备份包，那么数据实际收到是损坏的

差不多。不知道你说的数据损坏是什么意思。实际上是10个包中收到了8个，丢了2个，收到的8个还是有效的，不是整个10个都坏了。

>fec和多倍发包的真正区别是什么？

FEC算法比多倍发包的恢复能力更强一些，比如对于20个包发10个冗余包，只要收到了30个中的20个，就一定能恢复出全部数据。

FEC会引入额外的延迟，多倍发包不会。

>丢失的2个包会触发软件快速重传之类的机制吗？目测好像没这功能

UDP协议是允许丢包的，丢了就丢了，不会重传。就算你实现了重传，重传会引入额外的延迟，你传给了游戏，游戏也不一定要这个包了（游戏里检测出了这个包是很久以前发送的，丢弃了）。

>也试过4倍发包效果没啥区别

会比2倍好。

**Comment by BH4WHN** [comment]
谢谢答复，请问有可能会考虑直接提供tcp转udp部分（kcptun这样）的功能吗？现在用户的实际感受其实挺悲催的，为了某些科学性目的要使用三、四个软件一个套一个。另外，看说明上有写如果kcptun和udpspeeder串联可以关闭kcptun的fec（过人之处是？），那不如udpspeeder直接实现tcp部分不是更好。
**包括令人振奋的动态调整fec，希望可以提供完整的实现教程。**

**Comment by wangyu-** [comment]
>请问有可能会考虑直接提供tcp转udp部分（kcptun这样）的功能吗？现在用户的实际感受其实挺悲催的，为了某些科学性目的要使用三、四个软件一个套一个。

>udpspeeder直接实现tcp部分不是更好

对有一定动手能力的人来说，3个4个和1个区别不大，只要配置一个脚本启动这些就可以了。目前方法
的优点是可以自由组合。 一个集成了所有功能的软件只是方便了小白，我的精力主要在改善软件的功能，方便小白不是高优先级的事情。

另外你可以看下tinyFecVPN，这个集成度高一点：

https://github.com/wangyu-/tinyFecVPN
