### ISSUE TITLE
求教 openvpn+udp speeder route的具体例子

### ISSUE THREAD

**Issue by Hadsital** [wangyu-/UDPspeeder#55]
先感谢作者的项目
我是win7+vmware 使用的虚拟机是udp2raw中提供的lede路由固件 我ssh虚拟机 通过sftp将speedv2传到了虚拟机 目前我已经搭好了open VPN（直连可用）并开启了redirect Gateway 
以下是问题：
1.麻烦帮我看一眼我上面那个将speederv2在lede固件中运行得方法行么？跟其他人用的路由插件有区别么？
2.如果我的openVPN服务器ip为45.66.77.88 端口是2000 通过udpspeeder 将端口映射至4200 本地虚拟机ip为192.168.1.4 内置udpspeeder将45.66.77.88:4200映射至192.168.1.4:1500 pc的ip为192.168.1.3请教一下如果用ip route add xx.xx.xx.xx via xx.xx.xx.xx 具体应该如何替换 使udpspeeder的流量不通过openvpn 或者说如果网页登录的话应该怎么填route （麻烦了 我是真的不会...）
3.看udp2raw的issue中有提到ocserv也能使用 那么如要使用anyconnect是否要用open VPN将其转换成udp才能通过udp2raw呢？
4.请教一下openvpn+udpspeeder+udp2raw的route填写和问题2的答案类似呢？

**Comment by Hadsital** [comment]
补充一下问题2中vpn分配内网段为192.168.200.0
问题4问的是 是否跟问题2的答案类似

**Comment by wangyu-** [comment]
>请教一下如果用ip route add xx.xx.xx.xx via xx.xx.xx.xx 具体应该如何替换 

你先用ip route看一下输出。比如：
```
root@debian9:~/Desktop/udp2raw-tunnel# ip route
default via 192.168.100.1 dev ens33 proto static metric 100
169.254.0.0/16 dev ens33 scope link metric 1000
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
172.18.0.0/16 dev br-832721119df5 proto kernel scope link src 172.18.0.1 linkdown
192.168.100.0/24 dev ens33 proto kernel scope link src 192.168.100.107 metric 100
```

对于这个输出就 ip route add 45.66.77.88 via 192.168.100.1。

>4.请教一下openvpn+udpspeeder+udp2raw的route填写和问题2的答案类似呢？

一样的

>3.看udp2raw的issue中有提到ocserv也能使用 那么如要使用anyconnect是否要用open VPN将其转换成udp才能通过udp2raw呢？

没用过这两个，不清楚。

>1.麻烦帮我看一眼我上面那个将speederv2在lede固件中运行得方法行么？

方法没错，就是这样。

**Comment by Hadsital** [comment]
您好 我的ip route是这样的：
![tim 20171030224248](https://user-images.githubusercontent.com/33181526/32176901-d2408188-bdc3-11e7-96a6-73976faf63b3.png)
我 输出 ip route add 45.66.77.88 via 192.168.1.1
回复： ip : invalid argument '45.66.77.88' to ip
请教一下 这个是怎么回事 需要将光猫改为桥接模式么？

**Comment by wangyu-** [comment]
也许是这样的，`ip route add 44.55.66.77 via 192.168.1.1 dev eth0 src 192.168.1.4`。

不保证可以用，你尝试一下，如果加成功了，并且加了以后ping 44.55.66.77仍然可以ping通，那应该就是加对了。

>请教一下 这个是怎么回事 需要将光猫改为桥接模式么？

应该没有关系。

**Comment by Hadsital** [comment]
好的 谢谢回复

**Comment by Hadsital** [comment]
看了 #38 里的回复 找到根源了 貌似是redirect gateway选项没配置好？ 我在看看 感谢作者答复

**Comment by Hadsital** [comment]
貌似netcat正反向正常 OPEN VPN已绑定 udp 2000 正在研究tcpdump（小白没用过 等研究完了 测试后 在回复）

**Comment by Hadsital** [comment]
请教一下 是我没贴配置文件还是我的问题太基础了 为什么不回复我了🌚

**Comment by wangyu-** [comment]
当时有点没看明白，后来就忘了

>现在的情况是OpenVPN能connected 但是无法上网 ping不通45.66.77.88
正在尝试使用netcat排查问题 但如果按照上面所言 ping不通代表加错了？所以还是route的问题么？

这里是用VPN分配的ip ping还是用真实ip ping的？

**Comment by wangyu-** [comment]
如果是ping OpenVPN的ip ping不通，那90%可能是route的例外没添加对，OpenVPN刚connect上以后添加了重定向的规则，然后把UDPspeeder流量劫持了，造成了能connect但是ping不通。

如果是ping真实ip ping不通，可能是iptables没配好之类的原因。

**Comment by Hadsital** [comment]
用的vpn分配的ip ping的 啊 那我这个route该咋整 😂

**Comment by Hadsital** [comment]
是用的openvpn分配的ip ping的服务器的IP ping不通 而且openvpn连虚拟机以后 网络跟断了一样 网也上不去 请问这个也是route不对的原因么？

**Comment by Hadsital** [comment]
麻烦了 老是打扰作者 但我实在是没查出来应该怎么办 看了其他几个issue 貌似除了一位用WSL的 没几个人选择win+内置虚拟机的人 🌚 都是刷的路由 真的是每天就琢磨这点东西了 这东西配不好 打游戏感觉就像吃了X一样难受.......

**Comment by Hadsital** [comment]
顺便问一下需要我提供VPS么 如果需要请说 虽然open VPN直连能用 但就怕哪里配置不当 结果我想差了 没想到 然后就尴尬了

**Comment by Hadsital** [comment]
不管怎么说 我再查查我这种route应该怎么填吧 感谢作者回复 起码给了个排查方向🙏

**Comment by wangyu-** [comment]
>ip route add 44.55.66.77 via 192.168.1.1 dev eth0 src 192.168.1.4。

我刚才自己开了个虚拟机试了，就是这么加没错的， 而且貌似桥接的虚拟机不添加这条例外也没问题。

你手动在vmware里指定一下桥接的网卡，确保它桥接到了你的无线网卡，不要选自动，自动经常出问题。

**Comment by wangyu-** [comment]
另外，你是不是没按照openvpn配置教程里面说的设置 mssfix和fragment为1200？

UDPspeeder里面报什么错？贴一下log。

**Comment by Hadsital** [comment]
我用的有线网卡 其他的网卡我都禁用掉了 vmware指定的是vmnet0 貌似连上以后啥报错都没有 很迷茫

**Comment by wangyu-** [comment]
> 你是不是没按照openvpn配置教程里面说的设置 mssfix和fragment为1200？

**Comment by Hadsital** [comment]
设置了 之前怀疑过这个 服务端和客户端都设置了
Client:
![tim 20171104003508](https://user-images.githubusercontent.com/33181526/32385154-2b86d1ca-c0f8-11e7-9416-9a17628f1a99.png)
Server:
![tim 20171104003701](https://user-images.githubusercontent.com/33181526/32385195-4c45c4de-c0f8-11e7-88ad-1f1cd0e7daab.png)

**Comment by Hadsital** [comment]
mtu也限制为1200了 但是连上以后还是没网。。。。

**Comment by Hadsital** [comment]
这是服务端的iptables：
![tim 20171104004436](https://user-images.githubusercontent.com/33181526/32385546-83715f94-c0f9-11e7-836f-b4887669d6c2.png)
客户端的iptables我没动过
服务端的ip route：
![tim 20171104004650](https://user-images.githubusercontent.com/33181526/32385707-f8e9e138-c0f9-11e7-84bc-278641697660.png)

**Comment by Hadsital** [comment]
客户端ip route
![tim 20171104004844](https://user-images.githubusercontent.com/33181526/32385830-4f7770a6-c0fa-11e7-8a7b-bd03bc11495f.png)

**Comment by wangyu-** [comment]
我刚才试了一下

client端：
```
client
dev tun100       #也可只写dev tun       也可用tap
proto udp            #需要和server一致

remote 192.168.100.59 1234
resolv-retry infinite  #无限次尝试连接服务器
nobind  #???
persist-key  #断线重连不重新读取key
persist-tun  #断线重连不up/down close/reopen tun接口

ca ./ca.crt
cert ./client.crt
key ./client.key

redirect-gateway def1  #让openvpn来修改路由表
dhcp-option DNS 8.8.8.8

keepalive 3 20

verb 3
mute 20


comp-lzo no
cipher none #不和server设成一样会报warrning
auth none

fragment 1200
mssfix 1200

sndbuf 4000000
rcvbuf 4000000
#txqueuelen 4000
mute-replay-warnings
```
server端：

```
local 0.0.0.0

port 7777 #端口，需要与客户端配置保持一致
proto udp #使用协议，需要与客户端配置保持一致
dev tun100 #也可以选择tap模式


ca /etc/openvpn/easy-rsa/2.0/keys/ca.crt
cert /etc/openvpn/easy-rsa/2.0/keys/server.crt
key /etc/openvpn/easy-rsa/2.0/keys/server.key
dh /etc/openvpn/easy-rsa/2.0/keys/dh1024.pem

server 10.222.2.0 255.255.255.0 #给客户的分配的IP段，注意不要与客户端网段冲突！
ifconfig 10.222.2.1 10.222.2.6

client-to-client #client 间可见
duplicate-cn #允许同一个证书建立多个连接
keepalive 10 60 #每10秒一ping 连续60秒没消息就认为连接失败

#comp-lzo #启用压缩 ，客户端也需要开启
comp-lzo no
cipher none #传输数据不加密，但不关闭验证
auth none
max-clients 50

persist-key
persist-tun

status /etc/openvpn/openvpn-status.log
#log-append /etc/openvpn/openvpn.log# 添加这行以后所有输出都写到openvpn.log

verb 3
mute 20  #mute重复消息

mssfix 1200
fragment 1200

sndbuf 4000000
rcvbuf 4000000
txqueuelen 4000
```

客户端运行在win10，udpspeeder client运行在虚拟机；server是Vultr日本的VPS，debian系统。直接就好使了，打开ip138显示的是VPS的IP。唯一遇到的问题是，貌似win 10上的dns设置有点BUG，打不开google系的网站，我把无线网卡的DNS也改成了8.8.8.8，然后就完全正常了。

**Comment by Hadsital** [comment]
哇 难道是centos有毒？我回来试试改成debian试试 🌝

**Comment by Hadsital** [comment]
有点累了 准备先歇了 明天再反馈 请作者找到休息......

**Comment by wangyu-** [comment]
![image](https://user-images.githubusercontent.com/4922024/32388637-8a650950-c085-11e7-895d-00a60cecff77.png)

![open2](https://user-images.githubusercontent.com/4922024/32388697-be7b337c-c085-11e7-810a-bd1cbcfee591.PNG)

确保你的桥接设置跟我图里的一样。

**Comment by leepoi** [comment]
这么晚了还在战斗，简直是夜魔侠

**Comment by Hadsital** [comment]
谢谢回复 已经按图对照了 但是貌似还是不行 准备待会改debian试试 诶 想用centos。。。

**Comment by Hadsital** [comment]
哦 对了 这是我的openvpn的log 您看看吧 也许能分析出什么。。。。

**Comment by Hadsital** [comment]
![tim 20171104091712](https://user-images.githubusercontent.com/33181526/32400914-859374fe-c141-11e7-9308-a0f8ef87b869.png)

**Comment by wangyu-** [comment]
换台VPS或者换台电脑试试吧。

**Comment by Hadsital** [comment]
刚刚稍微再想了想 应该还是本地到虚拟机之间的问题 因为我通过udpspeeder连上openvpn后不能ping通192.168.1.4（本地虚拟机地址） 裸连就没事

**Comment by Hadsital** [comment]
请教一下 这个是怎么回事？ 服务器配置没变 客户端使用vbox 安装的是centos官网的最新minimal版本 已确认服务器和客户端使用的release是同一版本
![tim 20171109192344](https://user-images.githubusercontent.com/33181526/32603289-200f1d30-c584-11e7-8f8f-f336d8b29b32.png)

**Comment by wangyu-** [comment]
你试一下在vbox里ssh那台机器看能否连上

**Comment by Hadsital** [comment]
可以的

**Comment by wangyu-** [comment]
你那个log的IP显示的是255.255.255.255，有可能你的参数里有中文字符，把参数搞乱了

你尝试重新输入一下参数试试

**Comment by Hadsital** [comment]
问题已解决 感谢回复！

**Comment by Hadsital** [comment]
这次换了vbox 与之前不一样的是 虚拟机里的系统换为了centos 7 可惜貌似还是不能通 具体表现为over speeder后 主机不能上网 但是虚拟机可以ping通 baidu.com等外网 但是不能ping通主机IP（192.168.1.3）

**Comment by Hadsital** [comment]
问题成功解决了！！！！！！！！！！！
在windows中指定网关为虚拟机地址后成功上网了 
美滋滋！！！！！！！！！

**Comment by wangyu-** [comment]
>在windows中指定网关为虚拟机地址后成功上网了

你是把OpenVPN client跑在虚拟机里了吗？

**Comment by Hadsital** [comment]
没有啊 但是确实通过udpspeeder能上网了.....

**Comment by wangyu-** [comment]
这个问题貌似是`push "redirect-gateway def1" `的bug。

去掉`push "redirect-gateway def1"`，手动在win10上添加路由表可以解决。

https://github.com/wangyu-/UDPspeeder/issues/108
