### ISSUE TITLE
关于ipv6的支持

### ISSUE THREAD

**Issue by sptuan** [wangyu-/UDPspeeder#56]
首先感谢作者的辛勤付出。
请问能否支持ipv6？对于校园网用户需求还蛮大的

**Comment by wangyu-** [comment]
暂时没计划。我这边也没有方便的测试环境。

你可以自己尝试改一个，pr一下

**Comment by 0x6d3f9c** [comment]
在客户端和服务器端ipv6环境下，20170806.0版本测试可以使用。

**Comment by wangyu-** [comment]
>20170806.0版本测试可以使用。

我发现名字写错了，是20180806.0，已经改过来了

20180806.0及以后版本已经支持ipv6

**Comment by 0x6d3f9c** [comment]
我在x64的linux上客户端，ss-redir转发tcp通过kcptun到服务器的ss-server，同时转发udp通过udpspeeder到服务器的同一ss-server。

我在discord上使用了语音服务，它使用的是webrtc，该服务使用udp，经测试udp转发成功。

**Comment by wangyu-** [comment]
@0x6d3f9c  多谢反馈
