### ISSUE TITLE
与kcptun并联后使用udp2raw的问题

### ISSUE THREAD

**Issue by liuxxyzz** [wangyu-/UDPspeeder#57]
如果按着UDPspeeder和kcptun并联的方式还能用udp2raw吗？

![image](https://user-images.githubusercontent.com/25899693/32158523-0ebf5a34-bd84-11e7-8baf-eedf6436717b.png)

**Comment by wangyu-** [comment]
可以，给udpspeeder和kcptun分别套上udp2raw。

**Comment by liuxxyzz** [comment]
那udp2raw的local_port改怎么设置呀，比如这里kcp用4000，speeder用4001，udp2raw怎么作用在这两个端口
```
run at server side:
./kcp_server  -l ":4000" -t "127.0.0.1:443" -mode fast2
./speederv2 -s -l0.0.0.0:4001 -r127.0.0.1:443  -f20:10 -k "passwd"

run at client side:
./kcp_client  -l ":1234" -r "44.55.66.77:4000" -mode fast2
./speederv2 -c -l0.0.0.0:1234 -r44.55.66.77:4001 -f20:10 -k "passwd"
```

**Comment by wangyu-** [comment]
@liuxxyzz 
那udp2raw的local_port该怎么设置呀，比如这里kcp用4000，speeder用4001，udp2raw怎么作用在这两个端口

需要开两个udp2raw分别给kcptun和UDPspeeder用

**Comment by ykfq** [comment]
> @liuxxyzz
> 那udp2raw的local_port该怎么设置呀，比如这里kcp用4000，speeder用4001，udp2raw怎么作用在这两个端口
> 
> 需要开两个udp2raw分别给kcptun和UDPspeeder用

udp2raw 是否可以实现这样的功能呢？ udp2raw 可以多次使用 -r参数，从不同的端口读取数据，并通过统一的端口监听？
