### ISSUE TITLE
直连OK  通过UDPspeeder 连接提示 TLS握手失败

### ISSUE THREAD

**Issue by Hadsital** [wangyu-/UDPspeeder#58]
OpenVPN Server.conf :
![tim 20171030153743](https://user-images.githubusercontent.com/33181526/32159457-99d2b554-bd88-11e7-8dd5-90015a5231b7.png)
OpenVPN Client.ovpn:
![tim 20171030154056](https://user-images.githubusercontent.com/33181526/32159493-c0a12d96-bd88-11e7-9425-68ff54afa748.png)
直连OK 通过UDPspeeder则提示TLS 握手错误：
![tim 20171030154412](https://user-images.githubusercontent.com/33181526/32159625-33db217c-bd89-11e7-8141-273252ffc385.png)
Server：./speederv2_amd64 -s -l0.0.0.0:3000 -r127.0.0.1:2000  -f30:15 -k "passwd" --mode 0 --mtu 1200
Client ：./speederv2_x86 -c -l0.0.0.0:1500 -r45.66.77.88:3000 -f30:15 -k"passwd" --mode 0 --mtu 1200
OpenVPN 使用证书认证
本地环境：电信100M Windows7+VMware（lede）
PC IP:192.168.1.3 VMware IP:192.168.1.4
是否该填ip route add 45.66.77.88 via 192.168.1.3 ?

**Comment by wangyu-** [comment]
https://github.com/wangyu-/UDPspeeder/issues/38

https://github.com/wangyu-/UDPspeeder/issues/43

看一下这两个issue,一般发生这个是Iptables的问题或者bind的问题。

建议清空所有iptables后重试，用netstat -nlp确保openvpn bind在 0.0.0.0

**Comment by Hadsital** [comment]
烦请作者移至#55解答 刚才那个问题我重开了 感谢作者回复！
