### ISSUE TITLE
V2的Server端能兼容V1的客户端吗？

### ISSUE THREAD

**Issue by keeno1982** [wangyu-/UDPspeeder#59]
RT，因为路由的client还是V1的，目前还不懂怎么升级，不知道要不要将服务端升级到V2

**Comment by keeno1982** [comment]
@wangyu- 加个问题，最近常出现 socket bind error 这个错误，是因为什么呢

**Comment by wangyu-** [comment]
>V2的Server端能兼容V1的客户端吗？

不能。

>RT，因为路由的client还是V1的，目前还不懂怎么升级，不知道要不要将服务端升级到V2

如果只需要加速游戏，可以继续用v1的，更省资源。 你可以把v2版的binary scp到路由器里面，然后用命令行运行。

>最近常出现 socket bind error 这个错误，是因为什么呢

端口被其他程序占用了
