### ISSUE TITLE
请问一下，这个支持端口段吗？

### ISSUE THREAD

**Issue by cheapssr** [wangyu-/UDPspeeder#6]
在server端运行:
./speeder_amd64 -l0.0.0.0:8855 -r127.0.0.1:7777 -s -d2 -k "passwd"

请问这个可以修改为端口段吗？
用户很多的话，会出什么问题吗？
嗯。。。。。。酸酸乳加速
可以和锐速，bbr之类的共存吗？
锐速加速tcp
UDPspeeder加速UDP
感觉好完美呢

进一步是疑问
请看下面的组建
客户端--国内中转服务器--香港服务器
如果这样组建网络的话
udpspeed应该怎么操作呢

**Comment by wangyu-** [comment]
>请问这个可以修改为端口段吗？
你说的是-l那里改成多端口还是-r那里改成多端口？
UDPspeeder本身只支持一个端口。但是如果你要-l监听多个端口可以iptables半办到：
`iptables -t nat -A PREROUTING -p udp -m multiport --dport 4000:5000 -j REDIRECT --to-ports <udp_speeder_port>`
如果你要-r监听多个端口。有2个办法：
1.启动多个UDPspeeder服务
2.用UDPspeeder+openvpn，然后通过openvpn的ip来访问多个端口。

>用户很多的话，会出什么问题吗？
大问题不会有，设计上用的是epoll纯异步，不管多少连接都只有一个进程和一个线程。

不知道你说的很多是多少。几百个基本可以肯定不会有问题，如果再多，达到几千个。我也想知道。

能想到的问题有：
1.UDPspeed处理`-t `选项用了一个map来避免大量的定时器。map的复杂度是o(logN)，N是被延迟发送的数据包的数目。如果处理成千上万个连接logN的复杂度可能不够优秀。

2.`-t`(还有`-j`)选项本质上是把数据包存起来以后发送，这个做任何优化都无法避免。如果连接过多，内存不够大，`-t`过大可能会爆内存。 （1，2可以靠调小 -t的参数来解决。但是抵御突发丢包的能里会变弱）

3.单个UDPspeed不能利用多cpu,开多个UDPspeeder可以解决。

4.部分参数得针对高并发调整一下。`conn_clear_ratio`和`conn_clear_interval`。一个是过期连接垃圾回收时检查的连接的比例，另一个是回收的周期。

>可以和锐速，bbr之类的共存吗？
没问题。互不影响。甚至还有办法叠加（比如用udpspeeder+openvpn）。

>客户端--国内中转服务器--香港服务器

和`客户端-->香港服务器`的方案没有本质区别。只是你说的方案经过2次中转，普通的方案经过了1次中转。

哪条线路丢包严重，就在中间串个udpspeeder。为了最好的效果可以`客户端--国内中转服务器` 和`国内中转服务器--香港服务器`中间都加上udperspeeder。 但是，实际用起来，可能只要在`国内中转服务器--香港服务器`中间加上udpspeeder就足够了

**Comment by cheapssr** [comment]
感谢你解释的很详细。。。
客户端的话。。老毛子路由器固件已经支持UDPspeeder了，嘿嘿。
（这个可以以后讨论，先搞清楚服务器端）
然后。。。我一脸懵逼。。。。
我搭建了酸酸乳的服务器，主要是游戏用途
一步步来，，先搞清楚服务器如何配置
***********************************************

已经搭建好的酸酸乳服务器
每个用户分配一个端口，然后服务器要给所有的用户端口加速
用户端口从10000起，65535结束（设置的比较大，其实完全用不了这么多）
那么，，，-l和-r。。是不是都要监听全部的端口？
-l防火墙可以解决
-r的话，100个用户，，启动100个udpspeeder服务吗？？服务器估计撑不住啊。

openvpn不熟悉。。我比较熟悉酸酸乳。。

**Comment by wangyu-** [comment]
>每个用户分配一个端口，然后服务器要给所有的用户端口加速
用户端口从10000起，65535结束（设置的比较大，其实完全用不了这么多）

我想问一下你这个是怎么实现的。SSR本身支持监听多个端口吗？

我不太明白为什么要给一个用户分配一个端口，SSR本身不能用一个端口支持多个用户吗？我也不太明白你的服务器是怎么部署的，按我的理解你可能需要给每个用户开一个SSR进程。能不能贴一下具体的配置，如果有敏感信息，可以发到我的gmail邮箱(profile里可以找到)，具体问题具体分析一下。

**Comment by cheapssr** [comment]
嗯嗯，已经发送邮件了。
