### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by keytouch** [wangyu-/UDPspeeder#62]
Many Thanks to @wangyu- 's work. But I found that it can't listen or work over ipv6. Hope that IPv6 Support can be implemented, so it can also speed up udp traffic over ipv6 (udp).

**Comment by wangyu-** [comment]
duplicate with:

https://github.com/wangyu-/UDPspeeder/issues/56

I will eventually implement this, in a low priority, since IPv6 has a very low deployment ratio.

**Comment by wangyu-** [comment]
Supported since 20180706.
