### ISSUE TITLE
我有几个问题

### ISSUE THREAD

**Issue by windrunner414** [wangyu-/UDPspeeder#63]
1.如果我想 pptp l2tp openvpn都加速，是不是就要kcptun和udpspeeder并联？
2.能不能在服务端限制多倍发包？因为要给别人用，防止被调高导致流量耗的太多。。。

**Comment by wangyu-** [comment]
> 2.能不能在服务端限制多倍发包？因为要给别人用，防止被调高导致流量耗的太多。。。

自己修改源码加入相关限制。或者你自己写个脚本，在后台检测到了用过高的参数启动的UDPspeeder就杀掉。

> 1.如果我想 pptp l2tp openvpn都加速，是不是就要kcptun和udpspeeder并联？

看不懂`pptp l2tp openvpn都加速`和`kcptun和udpspeeder并联`有什么关联。请你认真描述一下。

**Comment by windrunner414** [comment]
pptp好像是tcp的？

**Comment by wangyu-** [comment]
我查了一下

pptp除了会用tcp协议以外，还要用到一个协议号为47的协议，非tcp也非udp，kcptun和udpspeeder都无法中转它的流量。

**Comment by windrunner414** [comment]
记得是tcp还有gre 所以数据不是tcp传输的数据咯？
那就不用pptp好了

**Comment by windrunner414** [comment]
记得是tcp还有gre 所以不是tcp传输的数据咯？
那就不用pptp好了
