### ISSUE TITLE
请问udpspeed直接加速**R怎么做呢

### ISSUE THREAD

**Issue by keeno1982** [wangyu-/UDPspeeder#66]
@wangyu- 四个问题哈，烦请回复
1.原始的ssr流量不能直接套上udpspeed加速吗？
2.ssr的udp流量需要另外分离出来？
3.ssr的服务端和客户端的udp流量都需要分离？
4.如何分离，有教程吗？

**Comment by wangyu-** [comment]
>1.原始的ssr流量不能直接套上udpspeed加速吗？

不能

> 2.ssr的udp流量需要另外分离出来？

这东西本来就是监听在一个udp端口+一个tcp端口的，不存在分离的问题。不过大概就是你说的意思吧。你要做的只是用UDPspeeder转发udp端口之后，再用其他方法把tcp端口也转发了。

>3.ssr的服务端和客户端的udp流量都需要分离？

你看下面连接里的具体命令。

>4.如何分离，有教程吗？

方法很多，这里面有kcptun+udpspeeder转发***r的具体命令：

https://github.com/wangyu-/UDPspeeder/blob/master/doc/README.zh-cn.md#udpspeeder--kcptunfinalspeed---同时加速tcp和udp流量

你也可以用tinyFecVPN,一个程序同时能转发tcp和udp。

**Comment by keeno1982** [comment]
感谢回复，刚看了教程，有个问题。我现在已经用了kcptun在加速TCP流量了，客户端本地转发端口是111，是不是ssr的设置不需要变动，直接套上udpspeed就行了？意思是kcptun和udpspeed两个要一起跑，udpspeed才能成功，单跑udpspeed是不行的？

**Comment by wangyu-** [comment]
>直接套上udpspeed就行了

我不知道你说的套上是什么意思。你用连接里的命令就可以了。鉴于你已经用kcptun转发了tcp，你只要做UDP的部分就可以了。

>意思是kcptun和udpspeed两个要一起跑，udpspeed才能成功，单跑udpspeed是不行的？

socks5方式单跑udpspeeder不行。redir方式可以单跑udpspeeder。

**Comment by wangyu-** [comment]
>直接套上udpspeed就行了

我不知道你说的套上是要给kcptun套上还是给**r的udp套上。建议你照着教程做，就不会有问题。

**Comment by keeno1982** [comment]
@wangyu- 不好意思，不懂专业术语啊。
我当前ssr server的端口是443，现在已经是用kcptun在加速443端口了，是不是用udpspeed也同样直接去加速443端口，然后本地客户端不管是kcptun和udpspeed都必须转发到同一个端口如666让ssr使用？如果单跑udpspeed是不是就会失败呢，意思是把kcptun关掉以后只留udpspeed进程

**Comment by wangyu-** [comment]
>然后本地客户端不管是kcptun和udpspeed都必须转发到同一个端口如666让ssr使用？

就是这个意思。

>如果单跑udpspeed是不是就会失败呢，意思是把kcptun关掉以后只留udpspeed进程

一般情况下单跑会失败。除非是用s**-redir做客户端。

**Comment by keeno1982** [comment]
@wangyu- 感谢，成功了，打开chrome的quic后udpspeed就开始跑出log了。一直用kcptun的思维去想udpspeed的连接方式，想单线调试看看单纯udpspeed的使用效果，没想到是需要两个一起开才能用，纠结好久终于解决！
