### ISSUE TITLE
问下openvpn+UDPspeeder配置问题

### ISSUE THREAD

**Issue by lixiaominggit** [wangyu-/UDPspeeder#67]
openvpn 配置完成，能正常上网，现在要加入UDPspeeder,  openvpn的配置文件加入下面的参数就可以吗？

fragment 1200       ##### very important    you can turn it up a bit. but, the lower the safer
mssfix 1200         ##### very important

sndbuf 2000000      ##### important
rcvbuf 2000000      ##### important
txqueuelen 4000     ##### suggested

**Comment by lixiaominggit** [comment]
忽略端口问题，加入UDPspeeder  openvpn 的配置文件的修改主要在哪几点？

**Comment by lixiaominggit** [comment]
这个是我的配置文件内容：
port 1194

proto udp

dev tun

ca ca.crt
cert server.crt
key server.key  # This file should be kept secret

dh dh2048.pem

server 10.8.0.0 255.255.255.0

ifconfig-pool-persist ipp.txt

push "redirect-gateway def1 bypass-dhcp"

keepalive 10 120

tls-auth ta.key 0 # This file is secret

cipher AES-256-CBC

comp-lzo no

max-clients 50

persist-key
persist-tun

status openvpn-status.log

log-append  openvpn.log

verb 3

mute 20

explicit-exit-notify 1

**Comment by lixiaominggit** [comment]
外网服务器：centos7
本人电脑: mac
本地UDPspeeder  在虚拟机上，用的是您提供的那个镜像

**Comment by wangyu-** [comment]
>openvpn 配置完成，能正常上网，现在要加入UDPspeeder, openvpn的配置文件加入下面的参数就可以吗？

差不多。不过不能保证一定可以用。

>加入UDPspeeder openvpn 的配置文件的修改主要在哪几点？

主要就是你刚才贴出来的那几行。

下面这2个配置经过我测试，在Linux上和windows上是没问题的：

https://github.com/wangyu-/UDPspeeder/blob/master/doc/udpspeeder_openvpn.md
https://github.com/wangyu-/UDPspeeder/wiki/win10系统UDPspeeder-OpenVPN的完整设置

你自己比对一下。或者直接用我的配置。

**Comment by wangyu-** [comment]
>这个是我的配置文件内容：
port 1194

你照那个windows的设置一下，基本上就可以了。我没有mac，没在mac上测试过，不知道会不会有什么不同。应该没有。

**Comment by lixiaominggit** [comment]
谢谢
