### ISSUE TITLE
如何才能在后台运行呀！

### ISSUE THREAD

**Issue by wolfid1** [wangyu-/UDPspeeder#7]
就算是加了&之后，SSH窗口一关，程序就结束了!!

**Comment by wangyu-** [comment]
查一下tmux或者screen或者nohup的用法。

或者查一下rc.local的用法，把speeder设置成开机自动启动。

**Comment by wangyu-** [comment]
>就算是加了&之后，SSH窗口一关，程序就结束了!!

这是linux程序的默认行为。

**Comment by wolfid1** [comment]
谢谢，我试试开机启动

**Comment by wolfid1** [comment]
开机启动这样果然选出，现在发生一个奇怪的问题，

./speeder_x86  -l 103.74.1**.1**:8855 -r 127.0.0.1:1701 -s -d2 -k "passwd"  --report 10
这样启动服务后，客户机怎么也连不上，我客户端这边用下面的nc命令试探端口是打开的，但是服务器上看不到任何的数据流量，之前可以连接的时候服务端，一直能看到流量，用NC试探端口的时候，服务器上都能看到数据流。请问有可能 是什么原因造成的呢？
nc -vuz 103.74.1**.1** 8855

**Comment by wolfid1** [comment]
是我防火墙问题，不好意思了，一切ok,正在测试对掉包率的改善，非分感谢你的软件

**Comment by wangyu-** [comment]
@wolfid1 你的client运行在什么机器上。 用的是哪种加速方案，可以告知一下吗。

**Comment by wolfid1** [comment]
@wangyu- 一台7026芯片的路由器
另外，-d2  是不是可以通过增大数值，更一步抑制掉包？
可能是服务器太渣，现在还是有掉包，只是好一些了

**Comment by wangyu-** [comment]
>另外，-d2 是不是可以通过增大数值，更一步抑制掉包？

可以，如果只是游戏的话-d4 -d5都可以，但是流量也翻了几倍。不要用来下载东西。

可以尝试一下调大或调小-t选项。默认是20，代表2毫秒。

>可能是服务器太渣

这个关系不大，再烂的服务器也能通过多倍发包明显改善。就算你的服务器有10%的掉包，这么高的掉包率网页已经没法打开了，游戏也没法玩了。

10%掉包的话，发3倍的包，正常情况下可以把掉包率降到0.1%，四倍的包可以降到0.01%，基本上就等于不掉包了。

>现在还是有掉包，只是好一些了

你是怎么知道现在还有掉包的，是靠玩游戏感觉出来的还是看udp2raw的发送报告看出来的？你的游戏可能本身即使用了tcp又使用了udp，所以不能靠感觉来判断。

丢包率的计算方法：

在client和server上分别把发送报告打开。对比一下两边的数字，两边的差的绝对值就是丢失的包的数量，然后再除以两边中比较大的那个数就是丢包率。不带`include dup`的那一列算出来的是加速后的丢包率，带`include dup`的那一列算出来的是加速前的丢包率。有`client-->server`和`server-->client `两个方向，可以分别算出上行和下行的丢包率。
```
[2017-09-07 04:33:49][INFO]client-->server: 480992,961984(include dup); server-->client 681729,1300101(include dup)
[2017-09-07 04:34:00][INFO]client-->server: 481001,962002(include dup); server-->client 681740,1300123(include dup)
```


>一台7026芯片的路由器

你是自己搭建的环境还是用lede里面做的那个集成版？

如果是自己搭建的环境你是按照Readme里面的哪个图配置的？

详细说下两边的配置，多提供点信息，信息越多越好。

**Comment by wangyu-** [comment]
>可能是服务器太渣

也可能是你本地的运营商对udp限速了，因为速度就限制在那么多，发得越多丢包率越高。

如果确认udp有限速，可以udp2raw+udpspeeder一起用。

**Comment by wolfid1** [comment]
用的是毛子固件最面集成的。
现在在阿里云上用，发现一个问题，只要udpspeeder 上有数据，瞬间断网。重启后恢复正常，不在上面传输VPS能一直通，一有数据，马上掉线

**Comment by wangyu-** [comment]
>现在在阿里云上用，发现一个问题，只要udpspeeder 上有数据，瞬间断网
你的意思是说之前在别的vps上用是正常的？

>VPS能一直通，一有数据，马上掉线
什么掉线了。VPS整个掉线了，SSH也不能访问了？

**Comment by wolfid1** [comment]
@wangyu-  我是用的L2TP连接服务器，不用 UDPspeeder 可以PING通任何地方，可以上网
通过 UDPspeeder  连接服务器之后，很奇怪，可以PING测试 VPN连接的的网关IP ，也就是vps的拨号内网地址，但是除此之外那么怕PING   VPS的 ETH0上的地址，VPS 瞬间掉线 SSH也不能连，不通PING通，跟死了一样，在阿里后台查看服务器是运行的。

**Comment by wolfid1** [comment]
@wangyu- 不知道是不是阿里防火墙能识别这样的封包，我还有台韩国的云服务器上运行是正常的，只是感觉PING好像稍稍要变大，在这台路由器上，直接PING 服务器要比通过VPN之后ping小大概10ms

**Comment by wangyu-** [comment]
>但是除此之外那么怕PING VPS的 ETH0上的地址，VPS 瞬间掉线 SSH也不能连，不通PING通，跟死了一样，在阿里后台查看服务器是运行的

不清楚了，但是我觉得UDPspeeder没有能力把VPS搞掉线。它做的只是转发个数据。


>不知道是不是阿里防火墙能识别这样的封包。
不太可能。这个项目发布没有多久，而且我在发包时做了混淆。从外界看不出来有多倍发包。

>我是用的L2TP连接服务器

我不确定L2TP的协议能不能支持udpspeeder。 有人报告L2TP不能用，见 #4。

我查了一下，这个协议貌似不止用了一个UDP端口，不知你是否有把这些端口都映射过来。

最好能截图贴一下两边的配置，现在我还是不清楚你到底是怎样用UDPspeeder的。我手上没有能刷毛子固件的路由器。

**Comment by wolfid1** [comment]
@wangyu- 另外就是你说的配置问题，等于是我没用你readme中的图，用L2TP+udpspeeder 实际上就可以即加速 TCP 也加速UDP 只是所有流量全走的  udpspeeder  也就是被双倍发包了，不过我玩游戏流量不大，也就无所谓。
还有就是软件能否提供比如 1.1倍 1.5 倍这样的配置，在网上看到有些服务器是会识别过多异常的数据的，而且阿里这种轻在高峰时才会轻微掉包的VPS 应该也用不着2倍这样的发包

**Comment by wolfid1** [comment]
L2TP 可以用的，我在其它服务器上用着正常的，L2TP本身是只用一个单口的，不需要工作端口用 IPSec方式才有其它工作端口

**Comment by wolfid1** [comment]
能否加我QQ ，给你发详细图  24686577

**Comment by wangyu-** [comment]
>还有就是软件能否提供比如 1.1倍 1.5 倍这样的配置

现在用的是多倍发包的方案，多倍只能是整数倍。

要发1.5倍包只能等以后的FEC功能了，但是不要期望太高。用FEC基本必然要引入额外的延迟。现在的方案对玩游戏来说是最有效的。1.5倍包这种功能，面向的主要是看视频这种大流量应用。

**Comment by BH4WHN** [comment]
将 ./speeder_amd64 -l0.0.0.0:8855 -r127.0.0.1:7777 -s -d2 -k "passwd"
放在rc.local里会出错导致之后的其他脚本无法运行，现在只能把它放在文件的最后一行。。
原因分析：rc.local文件开头#!/bin/sh  -e  中的-e参数应该是遇到某行指令或脚本出错就暂停执行之后的脚本。尝试把-e改成-x尝试将自启动中的错误行写入日志，发现确实是udpspeeder造成的其他脚本无法自启动。将脚本改写成.sh文件或nohup模式问题一样存在。

**Comment by wangyu-** [comment]
@BH4WHN 

你有没有用 `&`

加入` ./speeder_amd64 -l0.0.0.0:8855 -r127.0.0.1:7777 -s -d2 -k "passwd" &`，重新试一下。

不用`&`，只有等speeder退出以后，后面的命令才能执行。

nohup在`rc.local`中不需要，虽然加上也没问题。但是无论如何一定要用`&`

**Comment by BH4WHN** [comment]
@wangyu- 谢谢指点，确实是结尾要加&的问题。实测已经没有问题了

**Comment by wolfid1** [comment]
经测试。启动的时候 如果不加& 程序会阻止路由器重启。 重启和关机命令都是无效的，加了&就一切正常了
包括加入启动项启动也是一样的

**Comment by EasonSummer** [comment]
@wangyu- 应该能放在systemctl 开机启动 吧

**Comment by wangyu-** [comment]
@EasonSummer 没研究过。可能需要用脚本包装一下才能用systemctl。

**Comment by EasonSummer** [comment]
`[Unit]
Description=udp Service
                                                                                                                                      
[Service]
Type=oneshot
ExecStart=/root/speeder_amd64 -l0.0.0.0:8585 -r127.0.0.1:7777 -s -d3 -k "passwd" &
StandardOutput=syslog
StandardError=inherit
 
[Install]
WantedBy=multi-user.target`

**Comment by wangyu-** [comment]
>还有就是软件能否提供比如 1.1倍 1.5 倍这样的配置，在网上看到有些服务器是会识别过多异常的数据的，而且阿里这种轻在高峰时才会轻微掉包的VPS 应该也用不着2倍这样的发包

现在最新版本的已经能1.1倍和1.5倍发包了。
