### ISSUE TITLE
大佬，为何现在我开游戏服务端没反应了？

### ISSUE THREAD

**Issue by LockVer** [wangyu-/UDPspeeder#72]
![image](https://user-images.githubusercontent.com/3351118/32895798-3ccc0968-cb1c-11e7-818b-df520b4612ab.png)
如图，V1和V2都试过了，参数之前能用，昨天重装了次系统，装成CENTOS 6.8了，然后重新安装好SS和KCP，然后安装好这些之后打开UDPSPEEDER，客户端设置一样，打开游戏完全没反应了。。游戏也没连上。。就好像完全没有连接一样。。。是什么情况呢？

**Comment by LockVer** [comment]
另外，SS可以使用。

**Comment by LockVer** [comment]
错了，是CENTOS 7

**Comment by wangyu-** [comment]
你既然昨天都调试通了，自己研究一下吧。

对照一下程序的参数，和iptables-save的内容，看有什么区别没有。

**Comment by LockVer** [comment]
@wangyu- 我刚才重新装回centos 6.5，现在可以了。我想问下那个 -d 的参数，和丢包率有什么关系吗？是不是丢包越严重这个参数设置的越大呢？

**Comment by wangyu-** [comment]
-d1就是两倍发包，-d2是三倍发包。

你看一下：

https://github.com/wangyu-/UDPspeeder/blob/master/doc/README.zh-cn.v1.md

**Comment by LockVer** [comment]
@wangyu- 好的。谢谢了。
