### ISSUE TITLE
我的板瓦工OPENVPN没法正常用，怎么弄好

### ISSUE THREAD

**Issue by caryle** [wangyu-/UDPspeeder#76]
求教，谢谢了

**Comment by bao3** [comment]
我的和你 VPS 同一家，不过我的正常使用。与其他服务没区别。你可能需要调整一下 MTU之类的

**Comment by kang000feng** [comment]
@bao3 请问你的open VPN使用的是什么协议？有加混淆吗？还是只加了U D P speeder？

**Comment by bao3** [comment]
@kang000feng 不加混淆，只用 UDPSpeeder

另外你可以不必使用 UDPSpeeder 而直接使用 tinyVPN，更方便。

至于你说的混淆，我只想说，纯安慰作用，因为经过 UDPSpeeder 已经是混淆了。

**Comment by kang000feng** [comment]
@bao3 谢谢你！你是说tiny FeC VPN  ？ 作者release 版的代码里引入了一点限制，只可以当加速器用，不能直接用来“翻出去” 请问这个要怎么解决呢？

**Comment by bao3** [comment]
就只是加速用。实在要却限制，自己修改 tundev.cpp 这里的代码看看
