### ISSUE TITLE
可不可以吧openvpn换成ocserv

### ISSUE THREAD

**Issue by helaobibi** [wangyu-/UDPspeeder#8]
openvpn基本上现在都不用了，ocserv比较主流，ocserv效果也很好，能否使用？

**Comment by wangyu-** [comment]
>openvpn基本上现在都不用了，ocserv比较主流

不是很赞同这点。

>ocserv效果也很好，能否使用？

没用过。我简单看了一下它的网站，问题不大。用它的udp模式

目前已经确定支持的vpn有:openvpn,l2tp,shadowvpn

**Comment by helaobibi** [comment]
谢谢回复，我今天试了下好像ocserv用不起来，请问下有openvpn的搭建教程吗？简单就行了，或者一键包，再次感谢

**Comment by wangyu-** [comment]
>我今天试了下好像ocserv用不起来

我估计这个基本上是你的配置问题。只要是支持UDP协议的VPN，udpspeeder几乎都可以支持。

>请问下有openvpn的搭建教程吗

你参考这篇文章，这个是udp2raw+openvpn的教程。你把udp2raw换成udpspeeder，其他的都一样的：

https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/openvpn_guide.md

证书要自己生成。

**Comment by helaobibi** [comment]
感谢，openvpn证书太麻烦了，索性弄了个l2tp，效果还是不错的，如果要是跑大流量换成udp2raw-tunnel对吧
还有一个小问题，日志里面有个警告，[WARN]huge packet,data len=1425 (>1350).strongly suggested to set a smaller mtu at upper level,to get rid of this warn
应该是mtu值太大了，需要修改什么吗？

**Comment by wangyu-** [comment]
你在server上先找到xl2tpd的conf，一般是/etc/xl2tpd/xl2tpd.conf。

在里面找到pppoptfile这一行，这一行一般指向一个叫options.XXXX的文件。

然后你打开这个options.XXXX文件，加入：

```
mtu 1200
mru 1200
```

理论上只要改server的就可以，实际上以免出问题，我建议你两边都改。

**Comment by wangyu-** [comment]
>如果要是跑大流量换成udp2raw-tunnel对吧

udp2raw应对的是UDP qos，不是加速器。暂时先不要拿这个跑大流量，效果一般，也挤占别人带宽。

以后会做对大流量的支持，先等等吧。

**Comment by helaobibi** [comment]
好的，我主要是玩吃鸡~~感觉很稳，谢谢

**Comment by WANG-lp** [comment]
这个配合openvpn udp模式穿..墙 实际效果怎么样

**Comment by wangyu-** [comment]
>这个配合openvpn udp模式穿..墙 实际效果怎么样

抱歉，墙相关的问题不能解答，自己实验下吧。
