### ISSUE TITLE
新部署了个服务器，目前服务端不返回日志，无法判断是否有作用

### ISSUE THREAD

**Issue by sunpf** [wangyu-/UDPspeeder#81]
阿里云香港节点 服务器段只显示这一点信息，就没反应了
root@iZj6c5dh77a6fzttc2qjs2Z:/usr/local/bin# ./speederv2 -s -l0.0.0.0:4097 -r127.0.0.1:31011  -f2:4 -k "01" --mode 0 log-level 5 --log-position --report 5
[2017-11-19 14:09:34][INFO]argc=14 ./speederv2 -s -l0.0.0.0:4097 -r127.0.0.1:31011 -f2:4 -k 01 --mode 0 log-level 5 --log-position --report 5
[2017-11-19 14:09:34][INFO][misc.cpp,func:print_parameter,line:253]jitter_min=0 jitter_max=0 output_interval_min=0 output_interval_max=0 fec_timeout=8 fec_data_num=2 fec_redundant_num=4 fec_mtu=1250 fec_queue_len=200 fec_mode=0
[2017-11-19 14:09:34][INFO][tunnel.cpp,func:tunnel_server_event_loop,line:387]now listening at 0.0.0.0:4097

**Comment by fun5rt** [comment]
同样疑问。

**Comment by wangyu-** [comment]
你加上--report 5之后多等一会，看一下日志里有没有显示收到数据。

另外有人反映把路由器里的插件升级到3.7.3之后UDPspeeder不能用了，也许是路由器插件的问题。

https://github.com/wangyu-/UDPspeeder/issues/78

**Comment by fun5rt** [comment]
加了--report 10，也是不出日志，除了日志还有其他的测试方法么？
![image](https://user-images.githubusercontent.com/1532923/32988262-67e7e1dc-cd3b-11e7-911b-264b9cf61f78.png)

**Comment by wangyu-** [comment]
日志这样，说明server没有收到client的任何连接，UDPspeeder没有生效。

server需要收到client的连接后,`--report`才会有数据出来。

**Comment by sunpf** [comment]
估计可能是路由器插件的问题，等更新吧

**Comment by wangyu-** [comment]
>日志这样，说明server没有收到client的任何连接，UDPspeeder没有生效。

另外我再提醒一下，必须得有UDP流量，server才能收到client的连接。你得打开使用UDP的游戏试一下，server那才会有结果。

**Comment by fun5rt** [comment]
除了游戏之外有什么网页可以测试udp么？

**Comment by wangyu-** [comment]
网页不行。可以goolge一下nc/ncat,用nc/ncat的udp模式发送数据测一下。

**Comment by fun5rt** [comment]
@wangyu- 请教下，梅林路由器上的UDPspeeder 的report如何去看？

**Comment by wangyu-** [comment]
@fun5rt 问一下插件作者

**Comment by LockVer** [comment]
的确我现在升级到3.7.3之后好像udpspeeder全失效了。。

**Comment by w12928293** [comment]
@fun5rt  直接用手机打开youtube的app，成功加速的话会有日志输出。梅林3.7.3的时候我看日志没输出，我怀疑没效果，暂时换到3.7.0了，udpspeeder正常。
