### ISSUE TITLE
老哥，请教一个问题。。谢谢。。

### ISSUE THREAD

**Issue by LockVer** [wangyu-/UDPspeeder#86]
有没有可能让TCP走SS1然后UDP走SS2呢，这样网页走大流量高ping的美国服务器，而udp走低带宽低ping的香港服务器。。

**Comment by wangyu-** [comment]
https://github.com/wangyu-/UDPspeeder/issues/73

我刚刚提醒过你，不要短时间开大量的新ISSUE占版面。

**Comment by wangyu-** [comment]
已经是一周以内的第五个ISSUE了。

**Comment by LockVer** [comment]
不好意思，之后有问题我就在已经关闭的issue里面@你。

**Comment by wangyu-** [comment]
你可以把旧的reopen。

>有没有可能让TCP走SS1然后UDP走SS2呢，这样网页走大流量高ping的美国服务器，而udp走低带宽低ping的香港服务器。。

这个完全可以。但是你得学会自己配置s***-redir和iptables规则。

**Comment by LockVer** [comment]
@wangyu- 哦哦。。好的。之后有问题我再reopen吧。

**Comment by LockVer** [comment]
@wangyu- 请问一下，如果在网络条件比较好的情况下，比如谷歌云以及香港阿里云等延迟低且不怎么丢包的服务器上面搭建SS，需要使用udpspeeder吗？会有作用吗？还是说必须那种丢包严重的服务器才会有效果？

**Comment by wangyu-** [comment]
只要有丢包就能被降低。比如10%降低到0.1%，1%降低到0.01%之类

至于效果是否明显，以自己的测试为准。
