### ISSUE TITLE
效果不错，请教调mtu的方法。

### ISSUE THREAD

**Issue by w12928293** [wangyu-/UDPspeeder#88]
[2017-11-23 02:56:23][WARN]huge packet,data len=1365 (>1350).strongly suggested to set a smaller mtu at upper level,to get rid of this warn
 [2017-11-23 02:56:23][WARN]huge packet,data len=1365 (>1350).strongly suggested to set a smaller mtu at upper level,to get rid of this warn
 [2017-11-23 02:56:23][WARN]huge packet,data len=1365 (>1350).strongly suggested to set a smaller mtu at upper level,to get rid of this warn
 [2017-11-23 02:56:23][WARN]huge packet,data len=1365 (>1350).strongly suggested to set a smaller mtu at upper level,to get rid of this warn

以前一直用的v2，效果很明显，后来听作者说玩游戏用v1效果最好，就想试试v1，但是一直报mtu错误，试着修改了vps的网卡mtu，没效果，请教下作者，这个mtu需要怎么解决。

**Comment by wangyu-** [comment]
如果你用的是udpspeeder+vpn,可以在vpn里调。否则现在不建议用V1了。

改网卡的mtu无效。

V2版用我推荐的游戏参数，效果和v1是一样的。

**Comment by w12928293** [comment]
@wangyu- 感谢作者解答。

我是udpspeeder+ssr，那我暂时继续用v2。

昨晚上把梅林的插件退回到3.7.0，udpspeederV2运行正常了，跟小伙伴试完了下吃鸡，效果显著，之前游戏匹配完卡loading应该是插件哪有点问题，PS：3.7.0没有添加高级参数的地方，那我不添加-q1是不是也没关系？

再次对作者的付出表示感谢！

**Comment by wangyu-** [comment]
>3.7.0没有添加高级参数的地方，那我不添加-q1是不是也没关系？

不加-q1会引入0~8毫秒不等的延迟。你可以在路由器插件里，尝试把`-q1`偷偷填到别的参数后面，也许能骗过插件界面，把`-q1`加上。

如果实在不能用-q1可以尝试下面的参数(最多1毫秒的延迟)：
```
./speederv2 -s -l0.0.0.0:4096 -r127.0.0.1:7777   -k "passwd" --mode 0 -f2:4 --timeout 1
./speederv2 -c -l0.0.0.0:3333 -r44.55.66.77:4096 -k "passwd" --mode 0 -f2:4 --timeout 1
```

更多信息可以看：

https://github.com/wangyu-/UDPspeeder/wiki/推荐设置

**Comment by w12928293** [comment]
@wangyu-  多谢作者回复。晚上到家通过吃鸡对比了好几次udpspeeder的参数，感觉f2:4确实有效果。

后来我去看日志的时候发现，连接总是很快被cleared，这个和kcptun的stream open/closed一样属于正常情况吗？还是说哪里出了问题？

[0m[32m[2017-11-23 14:24:30][INFO][123.122.2.59:38078]new conv a210e6e5,fd 10 created,fd64=4294967660
[0m[32m[2017-11-23 14:24:42][INFO][123.122.2.59:38078]new conv d7058b14,fd 12 created,fd64=4294967661
[0m[32m[2017-11-23 14:24:42][INFO][123.122.2.59:38078]new conv 8d731090,fd 15 created,fd64=4294967662
[0m[32m[2017-11-23 14:24:44][INFO][123.122.2.59:38078]new conv a182c05e,fd 16 created,fd64=4294967663
[0m[32m[2017-11-23 14:25:55][INFO][123.122.2.59:38078]new conv 7cf6d454,fd 17 created,fd64=4294967664
[0m[32m[2017-11-23 14:26:51][INFO]conv 54e88f10 cleared
[0m[32m[2017-11-23 14:26:52][INFO]conv 58429580 cleared
[0m[32m[2017-11-23 14:26:53][INFO]conv ab2cd94b cleared
[0m[32m[2017-11-23 14:27:49][INFO]conv a182c05e cleared
[0m[32m[2017-11-23 14:27:51][INFO]conv 8d731090 cleared
[0m[32m[2017-11-23 14:28:55][INFO]conv 7cf6d454 cleared
[0m[32m[2017-11-23 14:28:57][INFO]conv d7058b14 cleared

**Comment by wangyu-** [comment]
>这个和kcptun的stream open/closed一样属于正常情况吗

差不多。一般是正常的。
