### ISSUE TITLE
速率最大能跑多少？

### ISSUE THREAD

**Issue by sdysj** [wangyu-/UDPspeeder#9]
有测试例子吗？电信 100M 宽带 kcptun 最大只能30Mbps。

**Comment by wangyu-** [comment]
首先，不建议在大流量的场景下用Udpspeeder。

>有测试例子吗？

从原理上，100Mbps宽带用`-d1` 最大可以跑50Mbps，用`-d2`最大33Mbps。以此类推。

20Mbps移动，用`-d1`实测，确实能跑10Mbps。

**Comment by sdysj** [comment]
测试了一下 xTun + UDPSpeeder，效果比 kcpraw 差一点，20Mbps左右，CPU使用率大了点，不错期待改进。

**Comment by wangyu-** [comment]
>测试了一下 xTun + UDPSpeeder，效果比 kcpraw 差一点，20Mbps左右，CPU使用率大了点，不错期待改进。

UDPspeeder跟kcptun/kcpraw比，优势在能加速udp，加速tcp时候更侧重延迟和响应，更适用于游戏、网页、语音。kcptun的优势是大流量tcp，比如下载和看视频。

在大流量又只需要TCP的情况下，UDPspeeder基本上是比不过kcptun的。

>CPU使用率大了点

你的CPU可能是xTun占的，在我的单核的Vultr 2.5美元小鸡上，跑满移动的20Mbps带宽，cpu占用是10%左右。

**Comment by sdysj** [comment]
我说的是在 OrangePi(ARMv7) 上的 CPU 使用率，大概65%左右，比 kcptun-raw 40% 高了点而已，没什么特别大问题，xTun大概 15% 左右挺意外的，再套上 udp2raw-tunnel 解决一下某些 UDP 流量限流问题，如果两个项目能合并就最好了，不过只是我的想法不用太在意。

**Comment by wangyu-** [comment]
>再套上 udp2raw-tunnel 解决一下某些 UDP 流量限流问题

Xtun本身有加密，用udp2raw可以把加密调低，建议用 `--cipher-mode xor` `--auth-mode simple`。如果坚持用默认的AES加密，可以尝试汇编加速版的(udp2raw_arm_asm_aes)。

>如果两个项目能合并就最好了，不过只是我的想法不用太在意。

合并和分开各有优势吧。如果选合并的方案，可能还得再集成一个内置的vpn用起来才能特别方便。分开有利于自由组合，暂时先这样吧。

**Comment by sdysj** [comment]
用 vultr 东京测试 d1 最高能跑5M/s，很爽， 不过 d1 上行也降一半了。
