### ISSUE TITLE
关于kcptun和udpspeeder串联的使用方法

### ISSUE THREAD

**Issue by dxtests** [wangyu-/UDPspeeder#91]
kcptun把tcp流量转成udp加速之后在经过udpspeeder加速理论上是不是比kcptun单独加速更快一点?

kcptun和udpspeeder串联使用是不是就不需要kcptun的服务端了? 因为在kcptun的客户端里填写的服务端地址是udpspeeder的客户端监听端口?  具体配置是kcptun加速为fast2 加密为aes 密码123456 udpspeeder是按照官方默认配置的 可是我这样配置无法正常访问 原先并联是可以正常访问的 具体是哪里配置错误了吗？

**Comment by wangyu-** [comment]
>kcptun和udpspeeder串联使用是不是就不需要kcptun的服务端了? 因为在kcptun的客户端里填写的服务端地址是udpspeeder的客户端监听端口?

我觉得你对udpspeeder和kcptun的工作方式有严重误解。建议多补充一下基础知识。

**Comment by wangyu-** [comment]
你参考下这个文章：

https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/kcptun_step_by_step.md

虽然是udp2raw的，但是udpspeeder也类似。


>kcptun把tcp流量转成udp加速之后在经过udpspeeder加速理论上是不是比kcptun单独加速更快一点?

有可能，但是如果不是很懂的话，还是别折腾了。

**Comment by wwxs972** [comment]
很好

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
