### ISSUE TITLE
UDPspeeder里有没有类似udp2raw中--conf-file的指令啊？

### ISSUE THREAD

**Issue by Se7enMuting** [wangyu-/UDPspeeder#97]
UDPspeeder里有没有类似udp2raw中--conf-file的指令啊？喜欢用配置文件，特别是用来开机自启动方面有配置文件比较方便

**Comment by wangyu-** [comment]
没有

duplicate with : https://github.com/wangyu-/UDPspeeder/issues/68

**Comment by zhfreal** [comment]
建议加一个--conf-file，这样写systemd、init之类的启动脚本更方便。
很久之前我改了个版本支持--conf-file自用，记得大部分代码都有，只是被屏蔽了。@wangyu-
